### DISCUSSION TITLE
How do you use artist art priority from pull #2266 ?

### DISCUSSION THREAD

**Discussion by hugalafutro** [navidrome/navidrome#2334] [Q&A] [answered]
Hi,
I am using Jellyfin organized music collection, and I don't even get the grey star as default artist picture, just empty space, and error on clicking it, the Artist view has no option to show grid either.

I have created spotify app and added the relevant config entries (ND_SPOTIFY_ID, ND_SPOTIFY_SECRET) to my docker-compose.yml, but the spotify dashboard reports it hasn't been accessed.

I've seen https://github.com/navidrome/navidrome/pull/2266, but it's not documented in the https://www.navidrome.org/docs/usage/configuration-options/ so I tried to add it like so to no avail: `ND_ARTISTARTPRIORITY: external, artist.*, album/artist.*`

my docker-compose.yml
```
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_LASTFM_APIKEY: ${NAVI_LAST_API}
      ND_LASTFM_SECRET: ${NAVI_LAST_SECRET}
      ND_SPOTIFY_ID: ${NAVI_SPOT_ID}
      ND_SPOTIFY_SECRET: ${NAVI_SPOT_SECRET}
      ND_ARTISTARTPRIORITY: "external, artist.*, album/artist.*"
      ND_ENABLEGRAVATAR: true
    volumes:
      - "./data_nd:/data"
      - "/shares/nfs/media/music:/music:ro"
```

Regardless of what I do all I get in logs is: `Could not resize image. Will return image as is" artID=ar-b54d4993b9a835a3fdf39e415620bbde_0 error="image: unknown format" size=300`

What am I doing wrong? Artist images already exist in each folder named `folder.jpg` since that's what JF uses, but not a single one of those show in navidrome. So I'm trying to force it to download from spotify (or last.fm, where I added my own api key to avoid throttling). Sorry if I'm missing something obvious, literally spun up navidrome stack 1st time ever half an hour ago.

**Comment by deluan** [comment]
> Could not resize image. Will return image as is" artID=ar-b54d4993b9a835a3fdf39e415620bbde_0 error="image: unknown format" size=300

This message is just a warning, informing that Navidrome was not able to resize the image, but in this case, it just sends the image as is to the client. We need more (debug) logs to figure out where it is getting the image from, as Spotify images are usually compatible with Navidrome and it should be able to resize it with not issues. It also helps disabling the ImageCache while troubleshooting cover art issues (`ND_IMAGECACHESIZE="0"`)

Anyway, if you have the images in the folders as `folder.jpg`, why not change `ND_ARTISTARTPRIORITY` to something like `folder.jpg, external`? This would make Navidrome look first for a `folder.jpg`.

**Reply by hugalafutro** [reply]
I assumed it's just what I've seen in the pull and I can only change the order, didn't think I can put my own filename in there. At work now so won't get to try until tomorrow, but I will disable the image cache and adjust the `ND_ARTISTARTPRIORITY` and report how it went when I get home. Thanks for the suggestion!

**Reply by hugalafutro** [reply]
Ok, I deleted all ND data to start from scratch, adjusted environment vars like discussed and still no dice for the artist images. 
```
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_LOGLEVEL: debug
      ND_LASTFM_APIKEY: ${NAVI_LAST_API}
      ND_LASTFM_SECRET: ${NAVI_LAST_SECRET}
      ND_SPOTIFY_ID: ${NAVI_SPOT_ID}
      ND_SPOTIFY_SECRET: ${NAVI_SPOT_SECRET}
      ND_ARTISTARTPRIORITY: "folder.jpg, external"
      ND_ENABLEGRAVATAR: true
      ND_IMAGECACHESIZE: 0
    volumes:
      - "./data_nd:/data"
      - "/shares/nfs/media/music:/music:ro"
```

I enabled debug log and have seen this:
```
navidrome  | time="2023-04-28T07:05:30Z" level=debug msg="Found artist artwork" artID=ar-b1dd10efa6a2761536d12edc20edeca9_0 elapsed=1.1ms path="/music/Black Sabbath/artist.nfo" requestId=60a046471579/YbMP0iTv7t-000196 source=fromArtistFolder username=sammael
```

so looks it tries to read JF's .nfo file instead of the picture. This is with including `folder.jpg` in the `ND_ARTISTARTPRIORITY` (have tried `folder.*` as well with no effect)

edit: this is what's in the directory
![image](https://user-images.githubusercontent.com/30209689/235079351-046a32c8-dd32-43eb-aef1-890656c6d0c3.png)
