### DISCUSSION TITLE
Help with Spotify and Last.fm Integration

### DISCUSSION THREAD

**Discussion by shumancw** [navidrome/navidrome#2469] [Q&A]
Can someone help me with what might be wrong with my .toml file? I'm trying to add the Last.fm and Spotify integration.

Debian 12.1
Navidrome 0.4.93
Installed to:
/opt/navidrome
/var/lib/navidrome

/var/lib/navidrome/navidrome.toml:
```
MusicFolder = "/zoom/audio/Music"
#LastFM.ApiKey = 13xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#LastFM.Enabled = true
#LastFM.Language = "en"
#LastFM.Secret = acxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#Spotify.ID = 7axxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#Spotify.Secret = fexxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
I have the Last.fm and Spotify lines commented out since Navidrome fails to load without. Is my syntax wrong or have I completely misunderstood something?

**Comment by metalheim** [comment]
Please try this syntax:

```toml
MusicFolder = "/zoom/audio/Music"
[LastFM]
	ApiKey = 13xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Enabled = true
	Language = "en"
	Secret = acxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[Spotify]
	ID = 7axxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Secret = fexxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

That's how i got it working on my navidrome instance :)
Note: All these "nested" configuration options must by at the end of your toml file.
