### DISCUSSION TITLE
Navidrome 0.50 Docker doesn't show playlists

### DISCUSSION THREAD

**Discussion by RandomBloke85** [navidrome/navidrome#2647] [Q&A] [answered]
I switched from 0.48 local install to 0.50 Docker on an ubuntu 22.04 server. Now, my playlists are gone. Any hint to bring them back are appreciated.

docker-compose.yml

```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
     ND_CONFIGFILE: "/data/navidrome.toml"
    volumes:
      - "/docker/navidrome/data:/data"
      - "/mnt/Music:/music:ro"
```

navidrome.toml

```
AutoImportPlaylists = true
PlaylistsPath = './Playlists'
ScanSchedule = '@every 1h'
LogLevel = 'debug'
ImageCacheSize = '200MB'
RecentlyAddedByModTime = true
CoverArtPriority = 'embedded, cover.*, folder.*, front.*'
EnableDownloads = false
AuthRequestLimit = 3
AuthWindowLength = '20s'
```

I've tried a couple of variations in PlaylistsPath like "/local/Playlists", same in single quotes, full local path, but all with no luck.
