### DISCUSSION TITLE
Create an admin user: Error: Unauthorized

### DISCUSSION THREAD

**Discussion by evirci** [navidrome/navidrome#2677] [Q&A]
Hi, i have already installed Navidrome in a docker in OpenMediaVault.
When i arrive at the point to create an admin user, the system tell error: Error: Unauthorized.
By shell i can login with the user.
Can anyone help me solve this?

this is the code of docker
```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1002:100 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/srv/dev-disk-by-uuid-46abbcf6-25fd-485c-85e4-adba8fc0342e/musica:/data"
      - "/srv/dev-disk-by-uuid-46abbcf6-25fd-485c-85e4-adba8fc0342e/musica:/music:ro"
```
thank you for the support
