### DISCUSSION TITLE
Add Radio button missing

### DISCUSSION THREAD

**Discussion by C8opmBM** [navidrome/navidrome#2822] [Q&A]
Hey,
Somehow my radio button is missing, I cannot add any stations.
What could have caused this?
I've searched online and it seems I should have had a button in the radios section.
Somehow mine doesnt have any.

![x](https://github.com/navidrome/navidrome/assets/60513190/a1f11dca-e7bd-4c29-9aeb-f200ed1bdb87)

Everything works as expected, but for the radios section.

My docker compose:

```
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    profiles:
      - media-request
    networks:
      - arrs
    expose:
      - 4533
    user: ${PUID}:${PGID}
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: "@weekly"
      ND_LOGLEVEL: info
      #ND_SESSIONTIMEOUT: "288h"
      ND_BASEURL: ""
      ND_REVERSEPROXYUSERHEADER: "Remote-User"
      ND_REVERSEPROXYWHITELIST: "0.0.0.0/0"
      ND_LASTFM_ENABLED: true
      ND_LASTFM_APIKEY: ${ND_LASTFM_APIKEY}
      ND_LASTFM_SECRET: ${ND_LASTFM_SECRET}
      ND_LASTFM_LANGUAGE: "en"
      ND_SPOTIFY_ID: ${ND_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${ND_SPOTIFY_SECRET}
    restart: unless-stopped
    volumes:
      - ${CONFIGDIR}/navidrome/config:/data
      - ${DATADIR}/data/media/music:/music:ro
```

LE: found out - _Adds a new internet radio station. Only users with admin privileges are allowed to call this method._
