### DISCUSSION TITLE
'EventStream error' every 5 seconds when behind traefik

### DISCUSSION THREAD

**Discussion by andzno1** [navidrome/navidrome#2951] [Q&A]
When using Navidrome behind traefik everything seems to work just fine. I can browse my whole music library and I can listen to my music. But when I open the browser console I am seeing an `EventStream error` every five seconds. 

This gets printed into the console:
```
GET https://navidrome.*******.***/api/events?jwt=********************************************************** net::ERR_CONNECTION_CLOSED 200 (OK)
```

And this is an example onerror event ([related code location](https://github.com/navidrome/navidrome/blob/9cc0cc2e93d6e75e0b2fdf86c4edbd6712dffd8d/ui/src/eventStream.js#L38)):

```json
{
  "isTrusted": true,
  "type": "error",
  "target": {
    "url": "https://navidrome.*******.***/api/events?jwt=**********************************************************",
    "withCredentials": false,
    "readyState": 0,
    "onopen": null,
    "onmessage": null,
    "onerror": {},
    "CONNECTING": 0,
    "OPEN": 1,
    "CLOSED": 2,
    "close": {},
    "addEventListener": {},
    "dispatchEvent": {},
    "removeEventListener": {}
  },
  "currentTarget": {
    "url": "https://navidrome.*******.***/api/events?jwt=**********************************************************",
    "withCredentials": false,
    "readyState": 0,
    "onopen": null,
    "onmessage": null,
    "onerror": {},
    "CONNECTING": 0,
    "OPEN": 1,
    "CLOSED": 2,
    "close": {},
    "addEventListener": {},
    "dispatchEvent": {},
    "removeEventListener": {}
  },
  "eventPhase": 2,
  "bubbles": false,
  "cancelable": false,
  "defaultPrevented": false,
  "composed": false,
  "timeStamp": 189877,
  "srcElement": {
    "url": "https://navidrome.*******.***/api/events?jwt=**********************************************************",
    "withCredentials": false,
    "readyState": 0,
    "onopen": null,
    "onmessage": null,
    "onerror": {},
    "CONNECTING": 0,
    "OPEN": 1,
    "CLOSED": 2,
    "close": {},
    "addEventListener": {},
    "dispatchEvent": {},
    "removeEventListener": {}
  },
  "returnValue": true,
  "cancelBubble": false,
  "NONE": 0,
  "CAPTURING_PHASE": 1,
  "AT_TARGET": 2,
  "BUBBLING_PHASE": 3,
  "composedPath": {},
  "initEvent": {},
  "preventDefault": {},
  "stopImmediatePropagation": {},
  "stopPropagation": {}
}
```

The related Navidrome server log looks like this (`###.###.###.###` is traefik's IP in the `public` docker network (bridge)):
```
time="2024-04-11T23:11:35Z" level=debug msg="Client added to EventStream broker" newClient="yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy (******* - ###.###.###.###:42698 - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)" numActiveClients=2
time="2024-04-11T23:11:37Z" level=debug msg="Removed client from EventStream broker" client="zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz (******* - ###.###.###.###:42698 - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)" numActiveClients=1
time="2024-04-11T23:11:40Z" level=debug msg="Started new EventStream connection" client="zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz (******* - ###.###.###.###:37342 - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)" requestId=************/**********-****** username=*******
```

My compose file looks like this:
```yaml
name: navidrome
services:
  navidrome:
    image: deluan/navidrome:0.51.1
    container_name: navidrome
    restart: unless-stopped    
    user: 1000:1000
    ports:
      - 4533:4533
    networks:
      - public
    environment:
      ND_CONFIGFILE: /data/navidrome.toml
    volumes:
      - ./data:/data
      - /media/audio/Musik:/music:ro
    labels:
      traefik.enable: true
      traefik.http.services.navidrome-svc.loadbalancer.server.port: 4533
      traefik.http.routers.navidrome.entrypoints: websecure
      traefik.http.routers.navidrome.rule: Host(`navidrome.*******.***`)
networks:
  public:
    external: true
```

My entrypoint configuration looks like this:
```yaml
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        certResolver: production
        domains:
          - main: *******.***
            sans:
              - '*.*******.***' # The first asterisk is not redacted, it's a wildcard
```

Can somebody point me in the right direction what may be causing this? Is it related to the random(?) ports (in this example `42698`, `37342`) that are being used for every new connection?
