### DISCUSSION TITLE
Docker External NFS Volume (Slow) vs Docker Internal Volume (Lightning Fast)

### DISCUSSION THREAD

**Discussion by StoneEngineer** [navidrome/navidrome#3253] [Q&A]
I would prefer connecting Navidrome to MariaDB, but it is what it is.
My Docker Swarm has multiple worker nodes, which have access to common NFS share. When placing SQLite navidrome.db and cache folder on NFS Mount, it is quite slow. Initial import scan of 3K albums requires more than 24h.
```
services:
  navidrome:
    volumes:
      - /mnt/nfs_nas_pv_swarm/navidrome/data:/data
```
The same library is scanned in minutes when using docker native volume. 
```
services:
  navidrome:
    volumes:
      - navidrome:/data
```
Unfortunately in this case navidrome.db and cache folder are located within the swarm node where Navidrome is running. Since there are multiple Docker Swarm nodes, common NFS share mount would be preferable.
I get those errors only when using external volume:
```
time="..." level=error msg="Error accessing image cache" error="context deadline exceeded" id='...' size=300
time="..." level=warning msg="Error warming cache" error="error caching id='...': context deadline exceeded"
time="..." level=warning msg="Error warming cache" error="error caching id='...': data not found"
```
Navidrome has full access to both volumes and creates sqlite database and cache folder by itself during initialization. Navidrome docker service works on single node (deploy -> replicas: 1). In case of node failure Navidrome is restarted on another healthy node.

Hope somebody can advise how to solve this issue.
