### DISCUSSION TITLE
How to run a second instance of Navidrome using docker?

### DISCUSSION THREAD

**Discussion by IO101010** [navidrome/navidrome#3280] [Q&A]
I saw a comment online that multiple Navidrome instances can be run in parallel. I tried to do this by duplicating the Navidrome directory that holds the data/ dir as well as the docker-compose.yml. Then I:

Changed the docker-compose.yml file to point to the newly copied data dir, a different folder for the music library and I changed the port number. When I run the container, the web page never loads at the port I set in the .yml file. Am I missing something?

**Comment by deluan** [comment]
The two instances need to use different ports (ND_PORT) and you don't need different `docker_compose.yaml` files, you can put everything in one. Example:

This assumes you have two data folders under the same folder as where the docker-compose.yaml file is.
Notice the different ports: One in 4533 and the other in 4534. 
Also notice that I simplified the compose file, but feel free to customize as per your needs (more options, different folders, users, ...)

```
services:
  nd1:
    image: deluan/navidrome
    ports:
      - "4533:4533"
    environment:
      ND_PORT: 4533
    volumes:
      - "./data1:/data"
      - "/mnt/media/music:/music:ro"
  nd2:
    image: deluan/navidrome
    ports:
      - "4534:4533"
    environment:
      ND_PORT: 4534
    volumes:
      - "./data1:/data"
      - "/mnt/media/music:/music:ro"
```
