### DISCUSSION TITLE
Navidrome copies all my music to its own directory

### DISCUSSION THREAD

**Discussion by seatrout** [navidrome/navidrome#3328] [Q&A] [answered]
Hi: I have set up Navidrome on a linux PC where it working fine. But my music was all stored in a shared folder on a windows PC which is itself mapped to a folder on the linux box. 

So I  put this into my `docker compose.yml`  
```
     environment:
     # Optional: put your config options customization here. Examples:
         ND_SCANSCHEDULE: 1h
         ND_LOGLEVEL: info
         ND_SESSIONTIMEOUT: 24h
         ND_BASEURL: ""
       volumes:
         - "/home/me/ND_data:/data"
         - "/mnt/my_mapped_drive:/music:ro"
```
and the music played fine remotely over my phone, even when I was out of the country. Which was fine. 
But when I returned I discovered that the entire contents of the mapped music drive on my Windows box had been copied to a new `music` subfolder in my Linux home directory. I don't want it there. How can I stop this happening?
