### DISCUSSION TITLE
Seeing Navidrome Login After Authentik Login Page - SSO via OIDC or Proxy Forward Authentication with NPMplus?

### DISCUSSION THREAD

**Discussion by pr0927** [navidrome/navidrome#3352] [Q&A]
Hi all, I recently migrated my entire self-hosted server platform from TrueNAS and Truecharts apps with a Traefik reverse proxy to Proxmox, Debian VMs, Docker containers, and an NPMplus reverse proxy.

One of the things I had been in the midst of implementing was SSO via Authentik for as many apps as possible. Navidrome was one that seems to have escaped this endeavor, but I think some people have succeeded at this (I think!) and am hoping for some assistance.

To my understanding, OIDC is not yet possible for Navidrome, so I'm trying to use the proxy forward authentication in Authentik. After a LOT of trial and error and effort, I was able to get it working where it presents the Authentik login page, but then still presents the Navidrome login page after that.

I was hoping to have the login pass through and check for existing accounts and log into something tied by e-mail address or username (to an Authentik user). Frankly, I'm a bit of a noob on this, not even sure if that's possible from the proxy forward authentication method for Authentik.

Please bear with me as I share bunch of configs and screenshots, would mega-appreciate any guidance!

Here is my current Docker compose for Navidrome:

```
version: "3.9"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    environment:
      - TZ=America/Los_Angeles
      - ND_LOGLEVEL=info
      - ND_SCANSCHEDULE=1h  # Scan every hour
      - ND_SESSIONTIMEOUT=24h
      - ND_ENABLETRANSCODINGCONFIG=true
      - ND_ENABLESHARING=true
      - ND_ENABLESTARRATING=false
      - ND_RECENTLYADDEDBYMODTIME=true
      - ND_BASEURL=https://sonic.mydomain.tld
      - ND_REVERSEPROXYWHITELIST=192.168.0.0/24
      - ND_REVERSEPROXYUSERHEADER="X-authentik-username"
    ports:
      - "4533:4533"
    volumes:
      - /mnt/Media/music:/music:ro
      - /data/navidrome/data:/data
    user: "1000:110000"  # Run as appuser
    restart: unless-stopped
```

Here's my Authentik proxy outpost:

![image](https://github.com/user-attachments/assets/d478cf8b-66ce-4c05-849c-2380c891053f)

Here's the Authentik provider setup:

![image](https://github.com/user-attachments/assets/f8e652b1-6c3d-4db0-a2b7-958e4202aebc)

Here's my Authentik app setup for Navidrome:

![image](https://github.com/user-attachments/assets/0ed34cdf-3c76-4a22-8554-5c433e4dd7c3)

And lastly, here's how my NPMplus is setup:

![image](https://github.com/user-attachments/assets/a8ed8e50-8d22-4a84-b387-3812bd869471)
![image](https://github.com/user-attachments/assets/67294d11-c432-4466-bdda-d683b6f27ea5)

Here's the NPMplus advanced tab (seems smarter to just paste the code):

```
port_in_redirect off;
location / {
    include conf.d/include/always.conf;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    include conf.d/include/proxy.conf;

    auth_request /outpost.goauthentik.io/auth/nginx;
    error_page 401 = @goauthentik_proxy_signin;
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    more_set_headers 'Set-Cookie: $auth_cookie';
    auth_request_set $authentik_username $upstream_http_x_authentik_username;
    auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
    auth_request_set $authentik_email $upstream_http_x_authentik_email;
    auth_request_set $authentik_name $upstream_http_x_authentik_name;
    auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
    proxy_set_header X-authentik-username $authentik_username;
    proxy_set_header X-authentik-groups $authentik_groups;
    proxy_set_header X-authentik-email $authentik_email;
    proxy_set_header X-authentik-name $authentik_name;
    proxy_set_header X-authentik-uid $authentik_uid;
    
    # This section should be uncommented when the "Send HTTP Basic authentication" option is enabled in the proxy provider
    #auth_request_set $authentik_auth $upstream_http_authorization;
    #proxy_set_header Authorization $authentik_auth;
}

location /outpost.goauthentik.io {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    include conf.d/include/proxy-location.conf;
    proxy_pass http://192.168.0.84:580/outpost.goauthentik.io; # ensure the host of this vserver matches your external URL you've configured in authentik

    proxy_set_header X-Original-URL $scheme://$host$request_uri;
    more_set_headers 'Set-Cookie: $auth_cookie';
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
}

location @goauthentik_proxy_signin {
    internal;
    more_set_headers 'Set-Cookie: $auth_cookie';
    return 302 /outpost.goauthentik.io/start?rd=$request_uri;
}
```
