### DISCUSSION TITLE
Support for multiple writing systems in songs metadata

### DISCUSSION THREAD

**Discussion by manusaurio** [navidrome/navidrome#3504] [Ideas]
# Rationale
Some users listen to music not only in foreign languages, but also in writing systems that we either can't read/write or that we find hard to do so. For example, many Japanese songs could be stored as files with metadata written in the Japanese writing system:

```
ALBUMARTIST=阿佐ヶ谷ロマンティクス
ARTIST=阿佐ヶ谷ロマンティクス
TITLE=焦がれ
ALBUM=大人幻想
```

This causes a few problems. Many songs aren't published in any other writing system than their original one. Translating the metadata yourself to a language that uses the alphabet can be really time demanding, which would be alright if you didn't have to lose the original names. It could happen that they get an official «international» version at some point that doesn't match yours (e.g. they might use romaji just to represent the sounds, or they could actually translate the names to something that makes sense in other languages, such as English: 阿佐ヶ谷ロマンティクス could be _Asagaya Romantikkusu, Asagaya Romantics, Romantics of Asagaya_.) Not only that, but you'd be also be screwing up your scrobbles in several ways. And there's yet another issue related to your database: if you get two albums by the same artist with their metadata written in different scripts, the artists will show up as two different entries, one for each, even though, ideally, there should be only one even if some songs are not translated, as some music platforms do.

There's no perfect way to solve any of this (specially the scrobbling part), but allowing metadata to be language-specific could improve things a lot for us. More importantly, it would make the search tool way more useful because we could type in the song title or the artist's name without switching the input method on our device (if that's even an option for us).

# Proposal
Navidrome's interface already shows the option to choose a language. This preference could be taken into consideration when a song or any other type of item is displayed. This could be done with Vorbis Comment:

```
TITLE=砂時計
TITLE_EN=Sunadokei
TITLE_JA=砂時計
ARTIST=林原めぐみ
ARTIST_EN=Megumi Hayashibara
ARTIST_JA=林原めぐみ
ALBUMARTIST=林原めぐみ
ALBUMARTIST_EN=Megumi Hayashibara
ALBUMARTIST_JA=林原めぐみ
ALBUM=VINTAGE DENIM
ALBUM_EN=VINTAGE DENIM
ALBUM_JA=VINTAGE DENIM
```

Notice some values are duplicated. This is because this solution tries to be flexible, and the common `TITLE`, `ALBUM`, etc. tags would also be needed in certain situations.

Assuming the language on your Navidrome server is set to English, Navidrome would take the tags that end with `_EN` to show the previous example like this (following the format `$TITLE - $ARTIST - $ALBUMARTIST - $ALBUM`):
> Sunadokei - Megumi Hayashibara - Megumi Hayashibara - VINTAGE DENIM

Or if it's set to Japanese:
> 砂時計 - 林原めぐみ - 林原めぐみ - VINTAGE DENIM

In this proposal I'll be using two-character codes as specified by ISO 639-1, just for simplicity. I'll also won't be proposing how anything of this would work in ID3 because I find it too restrictive. However, I think something like the `TXXX` frame could be used.

## Default values
If a language-specific tag is missing, then Navidrome would take the value from its non-specific equivalent. E.g.:

```
TITLE=モスキートンはもう聞こえない#2
TITLE_JA=モスキートンはもう聞こえない#2
TITLE_EN=Can't Hear Mosquitone Any More #2
ARTIST=toe
ALBUMARTIST=toe
ALBUM=For Long Tomorrow
```
This would be displayed in English as
> Can't Hear Mosquitone Any More #2 - toe - toe - For Long Tomorrow

...because there's no `ARTIST_EN` tag, but there's an `ARTIST` tag.

## Grouping
By default, Navidrome would use the common tags that aren't language-specific (`ARTIST`, `ALBUMARTIST`, `ALBUM`) to group into artist and album entries, as it does now. In other words, language-specific tags are not used to create new entries, they are only used to add information to them:

```
TITLE=灼熱の恋
TITLE_EN=Shakunetsu no Koi
ARTIST=林原めぐみ
ARTIST_JA=林原めぐみ
ALBUMARTIST=林原めぐみ
ALBUMARTIST_JA=林原めぐみ
ARTIST_EN=Megumi Hayashibara
ALBUMARTIST_EN=Megumi Hayashibara
ALBUM=スレイヤーズ MEGUMIXXX
```

```
TITLE=灼熱の恋
TITLE_EN=Shakunetsu no Koi
ARTIST=林原めぐみ
ARTIST_JA=林原　めぐみ
ALBUMARTIST=林原めぐみ
ALBUMARTIST_JA=林原　めぐみ
ARTIST_EN=Megumi Hayashibara
ALBUMARTIST_EN=Megumi Hayashibara
ALBUM=スレイヤーズ MEGUMIXXX
```
Notice the white space in the second entry, in the Japanese values. These two files together would be part of a single album, **スレイヤーズ MEGUMIXXX** by **林原めぐみ**, because they share common values in their `ALBUM` and `ALBUMARTIST` tags. However, the artist entry for **林原めぐみ** would end up with two associated names in Japanese, from the `_JA` tags, **林原めぐみ** and **林原　めぐみ**. It would still be a single entry for the artist, but with different associated names. For visual aid:
```yaml
artist:
    name: 林原めぐみ    # ARTIST & ALBUMARTIST from both songs (used as a «primary key», sort to speak)
    names_ja:
        - 林原めぐみ          # ARTIST_JA & ALBUMARTIST_JA from 1st song
        - 林原　めぐみ         # ARTIST_JA & ALBUMARTIST_JA from 2nd song
    names_en:
        - Megumi Hayashibara  # ARTIST_EN & ALBUMARTIST_EN from both songs
```

Also, the metadata from just one file should be needed to create an association between a default name and its language-specific ones. So if I had two files with the following metadata:

```
TITLE=灼熱の恋
TITLE_EN=Shakunetsu no Koi
ARTIST=林原めぐみ
ARTIST_JA=林原めぐみ
ALBUMARTIST_JA=林原めぐみ
ARTIST_EN=Megumi Hayashibara
ALBUMARTIST_EN=Megumi Hayashibara
ALBUM=スレイヤーズ MEGUMIXXX
```

```
TITLE=Give a reason
ARTIST=林原めぐみ
ALBUMARTIST=林原めぐみ
ALBUM=スレイヤーズ MEGUMIXXX
```

The result would be one album entry for **スレイヤーズ MEGUMIXXX** and one artist entry for **林原めぐみ**. The entry for this artist would be associated to the name **Megumi Hayashibara** in English. Adding the equivalent to every file is allowed but redundant.

```yaml
album:
    artist: 林原めぐみ
    name: スレイヤーズ MEGUMIXXX
    songs:
        - ...path to 灼熱の恋
        - ...path to Give a reason
```

```yaml
artist:
    name: 林原めぐみ
    names_ja:
        - 林原めぐみ            # ARTIST_JA & ALBUMARTIST_JA from the 1st song
    names_en:
        - Megumi Hayashibara  # ARTIST_EN & ALBUMARTIST_EN from the 1st song
    albums:
        - スレイヤーズ MEGUMIXXX
```

## Indexing/searching
Searching for a title would take _all_ languages into account, as some streaming platforms do. So, if typed in «Mosquitone» and the language of my interface was set to Japanese, モスキートンはもう聞こえない#2 by toe should be listed among the results anyway.

## Support for multiple artists
It could happen that a file specifies names for multiple artists:

```
ARTIST=林原めぐみ
ARTIST=鈴木真仁
```
While there's no perfect solution for this, I can think of three.

#### Force the user to make their language-specific tags follow the same order as the base ones
```
ARTIST=林原めぐみ
TITLE=乙女の祈り
ARTIST=鈴木真仁
ARTIST_EN=Megumi Hayashibara
DATE=2020
ARTIST_EN=Masami Suzuki
```

In this example, **Megumi Hayashibara** is an English version of **林原めぐみ** and **Masami Suzuki** is an English version of **鈴木真仁**. Further `ARTIST_EN` tags would be ignored. Only two are allowed here because there are only two `ARTIST`s.

#### Allow the user to add language-specific tags after a base one has been specified
```
ARTIST=林原めぐみ
ARTIST_EN=Megumi Hayashibara
TITLE=乙女の祈り
ARTIST=鈴木真仁
DATE=2020
ARTIST_EN=Masami Suzuki
```

The first `ARTIST` tag here is **林原めぐみ**, so the first `ARTIST_EN` tag is associated with it. This would also allow to add multiple language tags for the same base key within the same file:

```
ARTIST=林原めぐみ
ARTIST_EN=Megumi Hayashibara
ARTIST_JA=林原めぐみ
TITLE=乙女の祈り
ARTIST_JA=林原　めぐみ
ARTIST=鈴木真仁
ARTIST_JA=鈴木真仁
DATE=2020
ARTIST_EN=Masami Suzuki
```
**林原めぐみ** and **林原　めぐみ** are two versions in Japanese for the `ARTIST` **林原めぐみ**, notice the white space. The result would be as follows, regarding the artists' names:
```yaml
artist:
    name: 林原めぐみ
    names_ja:
        - 林原めぐみ
        - 林原　めぐみ
    names_en:
        - Megumi Hayashibara
```
```yaml
artist:
    name: 鈴木真仁
    names_ja:
        - 鈴木真仁
    names_en:
        - Masami Suzuki
```

#### Single language-specific tags, following a specific format for parsing
```
ARTIST=林原めぐみ
ARTIST=鈴木真仁
ARTIST_EN=[林原めぐみ]Megumi Hayashibara[鈴木真仁]Masami Suzuki
ARTIST_JA=[林原めぐみ]林原めぐみ[林原めぐみ]林原　めぐみ[鈴木真仁]鈴木真仁[鈴木真仁]鈴木　真仁
TITLE=乙女の祈り
```
(Just a vague idea of how it could be.) Considering that you could use other files with single artists to achieve the same effect, this would not come up very often.

## Scrobbling
Some people like myself have a lot of music in «foreign» writing systems, and I couldn't possibly add translated tags to all of them. However, just adding e.g. the ALBUMARTIST and ALBUM tags in the English alphabet would help a lot to find them.

The problem is that this proposed system, as it is described so far, might scrobble this:
```
TITLE=砂時計
ARTIST=林原めぐみ
ARTIST_EN=Megumi Hayashibara
ALBUMARTIST=林原めぐみ
ALBUMARTIST_EN=Megumi Hayashibara
ALBUM=VINTAGE DENIM
```
like this:
> 砂時計 - Megumi Hayashibara - Megumi Hayashibara - VINTAGE DENIM

While I would prefer if it was kept entirely in Japanese:
> 砂時計 - 林原めぐみ - 林原めぐみ - VINTAGE DENIM

That way it would not «screw up» my scrobbles, and I would still be able to look up the artists without writing in Japanese.

For this, I would consider a «Scrobble without translations» option, to only use the `ARTIST`, `ALBUMARTIST`, `TITLE`, and `ALBUM` tags.
