### DISCUSSION TITLE
Way to edit ffmpeg transcoding configs via a config file

### DISCUSSION THREAD

**Discussion by back-lacking** [navidrome/navidrome#3700] [Ideas]
Basically, what the title says. 
Enabling the `EnableTranscodingConfig` in navidrome is most time imo not a great idea. 
However, there are some times where i would want to change the command or bitrate of a transcoding setting. While I can just temporarily enable ``EnableTranscodingConfig` , change the config, and then disable `EnableTranscodingConfig`, that is inconvenient. 

Some way I'm thinking of is to have the transcoding settings set to a yaml file. below are some ideas im thinking of for this
### separate yaml file
```yaml
transcodings:
  name: "Opus audio"
    command: "ffmpeg -i %s -ss %t -map 0:a:0 -b:a %bk -v 0 -c:a libopus -f opus -"
    bitrate: 128
    target_format: "opus"
  name: "AAC audio"
    command: "ffmpeg -i %s -ss %t -map 0:a:0 -b:a %bk -v 0 -c:a aac -f adts -"
    bitrate: 256
    target_format: "aac"
  name: "MP3 audio"
    command: "ffmpeg -i %s -ss %t -map 0:a:0 -b:a %bk -v 0 -f mp3 -"
    bitrate: 192
    target_format: "mp3"
```
### within config 
```toml
TranscodingConfigFile=/path/to/file
```
### docker compose implementation
```yaml
environment:
  ND_TRANSCODINGCONFIGFILE: /transcoders.yaml
  ...
volumes:
  - "/host/path/of/transcoders.yaml:/transcoders.yaml"
  ...
```
