### DISCUSSION TITLE
How to prevent Navidrome from merging author & artists tags?

### DISCUSSION THREAD

**Discussion by DameGAD** [navidrome/navidrome#3901] [Q&A] [answered]
I tried multiple things in a config file but none of it works:

Tags.Author.Ignore = true

Tags.Artist.Aliases = ['tpe1', 'artist', '©art', 'iart']
Tags.Author.Aliases = ['author']

Navidrome keeps displaying author tags as artists. It results in the listing of thousands and thousands of artists that shouldn't exist.

**Comment by deluan** [comment, marked as answer]
This won't work, as AUTHOR is not mapped as its own tag, it is by default an alias to ARTIST:
```toml
Tags.Author.Ignore = true
```
This would work, but see comments below. You don't need to define `Tags.Author` if you just want to get rid of it:
```toml
Tags.Artist.Aliases = ['tpe1', 'artist', '©art', 'iart']
Tags.Author.Aliases = ['author'] # actually not needed to ignore tag author.
```
Notes: Are you using 0.55.1? You need to do a **full** scan after changes to Tags and PIDs. Have you done that?
