### DISCUSSION TITLE
Album unexpectedly split into 1+rest albums

### DISCUSSION THREAD

**Discussion by jboxman** [navidrome/navidrome#4029] [Q&A] [answered]
I'm using `0.54.4 (73ccfbd8)`, Docker install.

I can't make heads or tails of this. For several albums, I have this:

<img width="985" alt="Screenshot 2025-04-24 at 17 39 26" src="https://github.com/user-attachments/assets/95f65106-e69e-4b09-afae-960379f2906f" />

But at least according to Mp3tag, the album and album art names are the same:

<img width="1599" alt="Screenshot 2025-04-24 at 17 38 21" src="https://github.com/user-attachments/assets/cb37f715-cad1-457b-a31c-e663295a8dae" />

What might I want to look at to figure out why this album is getting split into 2 albums?

Thanks!

**Comment by kgarner7** [comment]
https://www.navidrome.org/docs/faq/#-i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist

> For a “Various Artists” compilation, the Part Of Compilation tag (TCMP=1 for id3, COMPILATION=1 for FLAC) must be set, for all tracks.

**Reply by jboxman** [reply]
@kgarner7, but this is what I have:

> For a single-artist album with a different artist name for each track (for example “Alice feat. Bob” , “Alice feat. Carol”), the Album Artist tags must be the same (“Alice”) for all tracks.

The _Album Artist_ is set to `Various Artists` for all of these tracks; See attached image above. Moreover, `TCMP=1` is not set on any of these tracks, yet 13/14 tracks are grouped into an album, and 1/14 into an album.

So I'm not clear on what is happening here. The description is at odds with what I'm seeing locally. I've confirmed there aren't any extra spaces or other characters in any of the fields, the album name and `Various Artists` are exactly identical.

I have plenty of other `Various Artists` style albums, but only a few are split incorrectly. 95% of them are grouped as I'd expect. None of them use `TCMP=1`. None of them are split incorrectly in Apple Music or elsewhere, only here.

Thanks.

Same album in Apple Music, all 14 tracks present:

<img width="1664" alt="Screenshot 2025-05-05 at 15 34 21" src="https://github.com/user-attachments/assets/ae2c93d9-e81e-4da7-819b-0c00224901af" />

**Reply by metalheim** [reply, marked as answer]
No you're right, either tcmp=1 or same albumartist works.

My best guess is that there some hidden junk tags. Can you check mp3tag - select all files - right click - extended tags?

**Reply by jboxman** [reply]
@metalheim, I see this:

<img width="635" alt="Screenshot 2025-05-05 at 17 02 05" src="https://github.com/user-attachments/assets/8b217bea-9363-4367-94d8-3538a7d5c232" />

**Reply by metalheim** [reply]
Different date and origyear can cause an album split with default PID configuration 

https://www.navidrome.org/docs/usage/pids/#default-configuration

**Reply by jboxman** [reply]
@metalheim, nuking any unusual tags including MB's seems to have fixed this, thanks!

**Comment by metalheim** [comment]
Please update navidrome, your version is 4 months old and there were 4 new releases after that (including an important security update in v0.54.5 and a major rework of how Tag metadata is interpreted in v0.55)

**Comment by philpem** [comment]
I've just had this with `navidrome:latest` on Docker, which gave me 

I had some production music albums which ended up split into three -- one for each track version. That type of music is sold for use in TV and radio productions and tends to include full tracks and 30 or 10-second and sting edits on the same CD.

What I found is that the `VERSION` tag in my FLAC files was being interpreted as part of the album PID. I'm not sure this is right because `VERSION` seems to be for tracks, but `ALBUMVERSION` is for albums:

https://github.com/navidrome/navidrome/blob/ddab0da207525b521b23d898275e5cec59166eb5/resources/mappings.yaml#L83-L85

For me the workaround was to put this in my configuration toml:

```toml
# Bring in track versions as a field (useful for Production Music)
Tags.Version.Aliases = ["version"]
Tags.Version.MaxLength = 50
Tags.Version.Album = false
Tags.Version.Split = ["; ", " / "]

# Don't use the trackversion as part of the albumversion
# default from https://github.com/navidrome/navidrome/blob/master/resources/mappings.yaml
Tags.albumversion.Aliases=["albumversion", "musicbrainz_albumcomment", "musicbrainz album comment"]

# Support Discogs release ID
Tags.discogs_release_id.Aliases = ['discogs_release_id']
Tags.discogs_release_id.Album = true

# Album PID. Use Musicbrainz Album ID, fall back to Discogs, fall back to albumartistid+album+albumversion+releasedate.
# Unlike the default - does not use the VERSION tag.
PID.Album = 'musicbrainz_albumid|discogs_release_id|albumartistid,album,albumversion,releasedate'
```
