### DISCUSSION TITLE
Help getting Traefik to route to Navidrome (without forwardauth)

### DISCUSSION THREAD

**Discussion by mikeymop** [navidrome/navidrome#4085] [General]
I am having trouble getting Navidrome to trust my reverse proxy. Is it required to authenticate the reverse proxy with Navidrome?

In my first naive approach I just forwarded the service but was getting a 404 page. At first I thought it was the base url, so I overrode the base url with my CNAME record. This started yielding 500 errors for bad gateway.

I read this in the docs:
> This option is unnecessary for most reverse proxy setups, only for authenticating reverse proxies.

I had originally considered it not necessary. However I couldn't reach the service unless I forwarded the ports and reached from my LAN directly.

I tried to setup the Reverse proxy whitelist with [0.0.0.0/0](https://www.navidrome.org/docs/usage/reverse-proxy/#traefik-with-forwardauth) but got a 500 Bad Gateway.

In noticed the logs in traefik
> time="2025-05-20T04:16:58Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 192.168.64.6:5433: connect: connection refused"

Looking at the Traefik network I have
traefik: 192.168.64.3
navidrome: 192.168.64.6

So the logs check out. I tried whitelisting the Traefik IP and even the gateway without any luck. I understand the reverse proxy whitelist can be a comma separated list so I tried with `ND_REVERSEPROXYWHITELIST: "192.168.64.3"`.

I understand Traefik may change ip addresses, so I tried a cidr range instead, ending my attempts at `ND_REVERSEPROXYWHITELIST: "0.0.0.0/0,192.168.64.0/24"` however navidrome is still refusing connections from Traefik.

I would expect, since it's an unauthenticated request, it would allow the proxy to pass my request through unauthenticated and show me the login page.

So I have to use ForwardAuth or the BasicAuth Traefik plugin listed in the reverse proxy docs?
I'd prefer to do no authenticate and use Navidromes authenticate to start, and then once I know everything is working put oauth2-proxy in front of it.

I've even tried using `@` for the proxy whitelist hoping to disable the trust proxy entirely.

Could someone help me get this working without FordwardAuth? Or is it required?

Visual:
```mermaid
graph TD
subgraph lan["My LAN"]
  pc["My desktop"]
end
subgraph srv["server"]

subgraph net["docker-net:traefik_default"]
  traefik["Traefik"]
  navidrome["Navidrome"]
end
end

pc -->|"tls:443"| traefik
traefik --x|"http:4533"| navidrome
```

My configuration:
```yaml
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    # ports:
    #  - 4533:4533
    restart: unless-stopped
    environment:
      ND_BASEURL: "https://music.example.com/"
      ND_LOGLEVEL: "debug"
      ND_ENABLESHARING: true
      ND_ENABLESTARRATING: true
      ND_LASTFM_APIKEY: ***
      ND_LASTFM_SECRET: ***
      ND_PORT: 4533
      ND_REVERSEPROXYWHITELIST: "0.0.0.0/0,192.168.64.0/24"
      ND_PROMETHEUS_ENABLED: true
      
    labels:
      - traefik.enable=true
      - traefik.http.routers.navidrome.entrypoints=web
      - traefik.http.routers.navidrome.rule=Host(`music.example.com`)

      - traefik.http.routers.navidrome.service=navidrome
      - traefik.http.services.navidrome.loadbalancer.server.port=4533
      # tls
      - traefik.http.routers.navidrome-secure.tls=true
      - traefik.http.routers.navidrome-secure.tls.certresolver=staging
      - traefik.http.routers.navidrome-secure.entrypoints=websecure
      - traefik.http.routers.navidrome-secure.rule=Host(`music.example.com`)
      - traefik.http.services.navidrome-secure.loadbalancer.server.port=4533
      - traefik.http.routers.navidrome-secure.service=navidrome

    networks:
      - traefik_default
    volumes:
      - "/srv/Data1/navidrome/data:/data"
      - "/srv/Data1/media/music:/music:ro"
networks:
  traefik_default:
    external: true
```

**Comment by metalheim** [comment]
Ypu commemted out the Port mapping in your compose file. You need to map a port on the container, otherwise nothing can connect to the navidrome container!

Also, check the loadbalancer port that you configured

**Reply by mikeymop** [reply]
I usually keep the port mapping commented for my memory once I test an application. Usually I dont have to expose ports to route through Traefik over a docker network.

I do expose the ports for access over my LAN without the reverse proxy.

I can tell the request is reaching Navidrome because Traefik logs the request and the connection refused response.

**Reply by metalheim** [reply]
The only way to be sure is to check navidrome's logs.
If theres no trace of the requests inside the container, something is off with the container/proxy setup.

**Comment by CrazyVito11** [comment]
I use Traefik as well on my server and I don't have any issues with it.

I did notice this, was this line directly copied from the Traefik logs? Because if so, it might still be trying to connect to the wrong port. _(`5433` instead of `4533`)_
![image](https://github.com/user-attachments/assets/b22ff0d3-1f2e-48ac-a4d7-56588322c022)

In case it might help, here is my working Docker compose configuration.

```yaml
services:
  navidrome:
    image: deluan/navidrome:0.56.1
    restart: unless-stopped
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    networks:
      - default
      - traefik-reverse-proxy
    environment:
      ND_SCANNER_ENABLED: false
      ND_SCANNER_SCHEDULE: 0
      ND_SCANNER_SCANONSTARTUP: true
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 72h
      ND_BACKUP_PATH: "/backup"
      ND_BACKUP_SCHEDULE: "59 23 * * *" # Daily at 23:59
      ND_BACKUP_COUNT: 30 # Keep for ~1 month
      ND_BASEURL: "https://${BASE_URL:-navidrome.localhost}"
      ND_LASTFM_APIKEY: "${LASTFM_APIKEY}"
      ND_LASTFM_SECRET: "${LASTFM_SECRET}"
    volumes:
      - "./backup:/backup"
      - "./data/navidrome-data:/data"
      - "${MUSIC_LIBRARY_PATH:-./data/music}:/music:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-reverse-proxy"
      - "traefik.http.routers.navidrome-https.rule=Host(`${BASE_URL:-navidrome.localhost}`)"
      - "traefik.http.routers.navidrome-https.entrypoints=https"
      - "traefik.http.routers.navidrome-https.tls=true"
      - "traefik.http.routers.navidrome.rule=Host(`${BASE_URL:-navidrome.localhost}`)"
      - "traefik.http.routers.navidrome.entrypoints=http"
      - "traefik.http.routers.navidrome.tls=false"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"

networks:
  traefik-reverse-proxy:
    name: traefik-reverse-proxy
    external: true
```
