### ISSUE TITLE
Navidrome Docker-Container creates large resolv.conf

### ISSUE THREAD

**Issue by quotengrote** [navidrome/navidrome#1179]
### Description

After a few Days(>10) the Navidrome docker-Container creates large(>50Gb) resolv.conf.

### Expected Behaviour

...

### Platform information

 - Navidrome version: 0.43.0 (d9f26826)
 - Browser and version: Vivaldi | 4.0.2312.25 (Stable channel) (64-Bit)

### Docker-Compose
```
version: '3'
services:
######## navidrome-mg ########
  navidrome-mg:
    container_name: "navidrome-mg"
    image: deluan/navidrome:latest
    restart: always
    environment:
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_MUSICFOLDER=/music
      - ND_DATAFOLDER=/data
      - ND_TRANSCODINGCACHESIZE=500MB
      - ND_IMAGECACHESIZE=100MB
      - ND_AUTOIMPORTPLAYLISTS=false
      - ND_BASEURL=/mg
      - ND_ENABLESTARRATING=false
      - ND_ENABLEGRAVATAR=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - musik_smb_mg:/music:ro
      - data:/data
    networks:
      - nw_proxy_traefik
    labels:
      - traefik.http.routers.navidrome-mg.rule=Host(`audio.XXXXXX.net`)&&PathPrefix(`/mg`)
      - traefik.enable=true
      - traefik.http.routers.navidrome-mg.tls=true
      - traefik.http.routers.navidrome-mg.tls.certresolver=resolver_letsencrypt
      - traefik.http.routers.navidrome-mg.entrypoints=entry_https
      - traefik.http.services.navidrome-mg.loadbalancer.server.port=4533
    ports:
      - "4533:4533"


######## Volumes ########
volumes:
  data:
  musik_smb_mg: # Verzeichnis in restic aus Backup ausnehmen!
    driver: local
    driver_opts:
      type: "cifs"
      o: "user=navidrome,password=XXXXXXXXXXXXX"
      device: "//192.168.2.36/musik/Musik"
######## Networks ########
networks:
  nw_proxy_traefik:
    external: true

```

### Additional information

![2021-06-14 13_38_33-Greenshot](https://user-images.githubusercontent.com/38253905/121887117-9eac5200-cd16-11eb-8ac9-de17a9dc0e2c.png)

![2021-06-14 13_40_08-Greenshot](https://user-images.githubusercontent.com/38253905/121886931-60af2e00-cd16-11eb-893e-15f335d3d2eb.png)
