### ISSUE TITLE
"Database could not be opened!" when starting navidrome as docker

### ISSUE THREAD

**Issue by Igeljaeger** [navidrome/navidrome#1313]
### Description
This error occurs when I follow the Docker instructions of Navidrome after already having it used for a normal install on my RPi4. Where is it looking for the Database and can I declare a path? Why doesn't it create a new one?
```
time="2021-08-30T11:11:26Z" level=error msg="Error disabling foreign_keys" error="unable to open database file: no such file or directory"
time="2021-08-30T11:11:26Z" level=error msg="Database could not be opened!" error="unable to open database file: no such file or directory"
```

```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "music.jaeger.website"
      ND_CONFIGFILE: "/data/navidrome.toml"
    volumes:
      - "navidrome:/data:rw"
      - "/home/pi/navidrome/navidrome.toml:/data/navidrome.toml:rw"
      - "/home/pi/navidrome/music:/music:ro"

volumes:
  navidrome:
```

### Expected Behaviour

For it to create a new database instead of looking for an existing one.

### Steps to reproduce

1. Install Navidrome manually
2. run it
3. stop it
4. Install Navodrome for Docker
5. run it

### Platform information

 - Navidrome version: 0.45.1
 - Operating System: Raspbian GNU/Linux 10 (buster) aarch64
