### ISSUE TITLE
Metadata scanner SIGSEGV

### ISSUE THREAD

**Issue by possessedbysatan** [navidrome/navidrome#1349]
### Description

Navidrome crashes during initial folder scan.

### Expected Behaviour

To finish scanning my music folder without any issues.

### Steps to reproduce

1. Literally I just modified a little the recommended docker-compose.yml, ran `docker-compose up -d` it and then Navidrome crashed.

### Platform information

 - Navidrome version: 0.45.1 (c55e6590) and 0.45.1-SNAPSHOT (f2ed3f2d)
 - Browser and version: Chromium 92, though I don't think this matters since Navidrome crashes even before being used.
 - Operating System: Docker armv7 image (tested against both :latest and :develop tags as of 18/Sep)

### Additional information

Any other information that may be relevant or give context to the problem.

 - Host: Raspberry Pi4B+Arch Linux ARMv7
 - Logs: Crashlog for :develop tag 
[crash.log](https://github.com/navidrome/navidrome/files/7190918/crash.log)
 - Client used: Chrome/DSub

Docker-compose file:
```
  navidrome:
    image: deluan/navidrome:develop
    container_name: navidrome
    environment:
      - PGID=1000
      - PUID=1000
      - ND_SCANINTERVAL=6h
      - ND_LOGLEVEL=trace
      - GODEBUG="netdns=go"
    volumes:
      - /redacted:/data
      - nfsshare:/music:ro #docker nfs volume
```

From the logs it seems Navidrome's metadata scanner crashes when reading a very specific set of files, but I tried playing every one of them through VLC and all of them seem to be fine. `file` doesn't report anything strange as well.

Edit: I already tried using env variable as described here: https://github.com/navidrome/navidrome/issues/588 - it didn't work.
