### ISSUE TITLE
[Question] How do I link the ND_PLAYLISTSPATH to an external folder?

### ISSUE THREAD

**Issue by BobWs** [navidrome/navidrome#1493]
Hi,
Sorry probably not a bug, but I was wondering how do I link `ND_PLAYLISTSPATH` to an external folder.

I have tried linking `ND_PLAYLISTSPATH` to a external playlist folder that reside in my `docker-media folder` but then nothing happens. The playlist aren't imported by navidrome, but when I copy the playlist-folder into my music-folder than it works.

I would like to keep the playlist-folder for navidrome separated from my music-folder, because my music-folder is the same folder that is used bij iTunes.

This is how I configured navidrome on docker on a Synology NAS.
```
version: '3.8'

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1030:100 # should be owner of volumes
    ports:
      - 4533:4533
    volumes:
      - '/volume1/docker/navidrome/data:/data'
      - '/volume2/music/iTunes/iTunes Media/Music:/music:ro'
      - '/volume1/docker-media/playlists:/playlists:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/TZ:/etc/timezone:ro'
    security_opt:
      - no-new-privileges:true
    env_file: /volume1/docker/navidrome/navidrome.env
    environment:
      - PUID=1030
      - PGID=100
    restart: always
    network_mode: "bridge"
```
and then I have entered this in the env file `ND_PLAYLISTSPATH=playlists`
But unfortunately it is not working. Can you tell me what I'm doing wrong?
