### ISSUE TITLE
panic: chi: routing pattern must begin with '/' in '""/auth'

### ISSUE THREAD

**Issue by plague-doctor** [navidrome/navidrome#1647]
### Description

I get this when my navidrome starts... Never had a single problem with ND... 

```
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                          Version: 0.47.5 (86fe1e3b)
time="2022-03-08T07:05:38Z" level=warning msg="ScanInterval is DEPRECATED. Please use ScanSchedule. See docs at https://navidrome.org/docs/usage/configuration-options/"
time="2022-03-08T07:05:38Z" level=warning msg="Setting ScanSchedule" schedule="@every 24h0m0s"
time="2022-03-08T07:05:38Z" level=info msg="goose: no migrations to run. current version: 20211105162746\n"
time="2022-03-08T07:05:38Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
time="2022-03-08T07:05:38Z" level=info msg="Creating Image cache" maxSize="100 MB" path=/data/cache/images
time="2022-03-08T07:05:38Z" level=info msg="Finished initializing cache" cache=Image elapsedTime="414.211µs" maxSize=100MB
time="2022-03-08T07:05:38Z" level=info msg="Starting scheduler"
time="2022-03-08T07:05:38Z" level=info msg="Scheduling periodic scan" schedule="@every 24h0m0s"
time="2022-03-08T07:05:38Z" level=info msg="Setting Session Timeout" value=24h
time="2022-03-08T07:05:38Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=20s
panic: chi: routing pattern must begin with '/' in '""/auth'
goroutine 14 [running]:
github.com/go-chi/chi/v5.(*Mux).handle(0xc0002420a0, 0xc000181b18, {0xc000200e30, 0xea2a5a}, {0x21c6fe0, 0xc0003a0060})
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:390 +0x309
github.com/go-chi/chi/v5.(*Mux).Mount(0xc0002102a0, {0xc000200e30, 0x7}, {0x21c4d80, 0xc000210360})
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:318 +0x273
github.com/go-chi/chi/v5.(*Mux).Route(0xc000181d50, {0xc000200e30, 0x7}, 0xc000181d40)
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:271 +0xf8
github.com/navidrome/navidrome/server.(*Server).initRoutes(0xc0002022a0)
	/github/workspace/server/server.go:74 +0x10d2
github.com/navidrome/navidrome/server.New({0x21eccd8, 0xc00022e090})
	/github/workspace/server/server.go:29 +0x77
github.com/navidrome/navidrome/cmd.CreateServer({0x0, 0x0})
	/github/workspace/cmd/wire_gen.go:32 +0x65
github.com/navidrome/navidrome/cmd.startServer.func1()
	/github/workspace/cmd/root.go:77 +0x2c
github.com/oklog/run.(*Group).Run.func1({0x20ffcb8, 0x20ffcc0})
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x2f
created by github.com/oklog/run.(*Group).Run
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0x22f
```
My docker-compose (running in swarm):
```
version: "3.8"

services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    networks:
        - proxy
    volumes:
      - /mnt/docker/docker-volumes/navidrome:/data
      - /mnt/music:/music:ro
    environment:
      - ND_SCANINTERVAL=24h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=""
    deploy:
        labels:
          - "traefik.enable=true"
[...]
```

### Platform information

 - Navidrome version: 0.47.5 
 - Operating System: docker deluan/navidrome:latest
