### ISSUE TITLE
No import of playlists

### ISSUE THREAD

**Issue by superfunk2000** [navidrome/navidrome#1721]
### I have the following configuration:

**Here are all MP3's in one folder:**
Windows Share: \\\Server\Multimedia\Musik

**The playlists are here:**
\\\Server\Multimedia\Musik\playlisten

**This share is mounted on Ubuntu:**
//Server/Multimedia/Musik /mnt/music cifs credentials=/etc/ms06-credentials,file_mode=0777,dir_mode=0777 0 0

### My docker-compose.yaml looks like this:

```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "45133:4533"
    restart: always
    environment:
      ND_SCANSCHEDULE: "@daily"
      ND_LOGLEVEL: "info"
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_MUSICFOLDER: "/music"
      ND_PLAYLISTSPATH: "/playlisten"
      ND_SPOTIFY_ID: "********************************"
      ND_SPOTIFY_SECRET: "********************************"
      ND_LASTFM_APIKEY: "********************************"
      ND_LASTFM_SECRET: "********************************"
      ND_LASTFM_LANGUAGE: "de"
      ND_ENABLEGRAVATAR: "true"
    volumes:
      - "./data:/data"
      - "/mnt/music:/music:ro"

```

### Log:
```
navidrome    |  _   _             _     _
navidrome    | | \ | |           (_)   | |
navidrome    | |  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
navidrome    | | . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
navidrome    | | |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
navidrome    | \_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
navidrome    |                           Version: 0.47.5 (86fe1e3b)
navidrome    |
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="goose: no migrations to run. current version: 20211105162746\n"
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Creating Image cache" maxSize="100 MB" path=/data/cache/images
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Starting scheduler"
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Scheduling periodic scan" schedule=@daily
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Setting Session Timeout" value=24h
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=20s
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Mounting Native API routes" path=/api
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Mounting Subsonic API routes" path=/rest
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Mounting LastFM Auth routes" path=/api/lastfm
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Mounting ListenBrainz Auth routes" path=/api/listenbrainz
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Mounting WebUI routes" path=/app
navidrome    | time="2022-05-04T05:41:16Z" level=info msg="Navidrome server is ready!" address="0.0.0.0:4533" startupTime=28.4ms
navidrome    | time="2022-05-04T05:41:17Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/data/cache/transcoding
navidrome    | time="2022-05-04T05:41:17Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime="475.211µs" maxSize=100MB
navidrome    | time="2022-05-04T05:41:17Z" level=info msg="Finished initializing cache" cache=Image elapsedTime=280.8ms maxSize=100MB
navidrome    | time="2022-05-04T05:41:34Z" level=info msg="Loading translations" languages="[bg ca cs da de eo es fa fi fr it ja nl pl pt ru sl sv th tr uk zh-Hans zh-Hant]"
```

The MP3's are all displayed correctly in Navidrome, but no playlists are imported.
No errors appear in the log.

What am I doing wrong?
