### ISSUE TITLE
Playlists missing!

### ISSUE THREAD

**Issue by dl-lim** [navidrome/navidrome#1775]
I'm a little devastated as some playlists I spent hours curating just disappeared!

I host Navidrome via docker (see docker-compose below), and for the most part it runs well. I had a power outage the other day and naturally, the server restarted normally when it came back. I didn't check to see if the playlists were still there immediately after (it has been 8 days since that outage). I'm not even sure if that was the culprit.

Now, I look at playlists and found that everything was missing. All my playlists are empty. I may have done some rescanning but not moved any files in between. Where and how are playlists stored and what could I do to prevent this sort of thing?

```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: "33:33"
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
    volumes:
      - "/srv/navidrome/data:/data"
      - "/srv/musicfolder:/music:ro"
```
