### ISSUE TITLE
Navidrome not honoring ND_TRANSCODINGCACHESIZE

### ISSUE THREAD

**Issue by dodedodo** [navidrome/navidrome#1778]
### Description
I set navidrome's transcoding cache size in docker environmental variables (500MB). This seems to take effect because the value is reflected in navidrome's console log. The cache size is also reduced to 500MB when the navidrome process starts. 

However, navidrome does not maintain that cache size limit throughout its runtime. It simply grows till the disk is full. After restarting the process the cache is cut back to 500MB, and then starts to grow again. 

### Expected Behaviour
I'd expect navidrome to manage its cache size throughout the process lifecycle. Possibly in some lifo-type cache. 

### Steps to reproduce

1. Run navidrome in docker (deluan/navidrome:0.47.5) 
2. Set env variable `ND_TRANSCODINGCACHESIZE` to `500MB`. I'm using docker-compose to accomplish this
``` yaml
version: "3.8"
services:
  navidrome:
    container_name: "navidrome"
    image: deluan/navidrome:0.47.5
    restart: always
    user: 1000:1000 # should be owner of bind-mounts.
    expose:
      - "4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_COVERARTPRIORITY: "cover.*, folder.*, front.*, embedded"
      ND_DEFAULTTHEME: "Spotify-ish"
      ND_SPOTIFY_ID: "REDACTED"
      ND_SPOTIFY_SECRET: "REDACTED"
      ND_LASTFM_SECRET: "REDACTED"
      ND_LASTFM_APIKEY: "REDACTED"
      ND_LASTFM_LANGUAGE: "en"
      ND_UIWELCOMEMESSAGE: "REDACTED"
      ND_TRANSCODINGCACHESIZE: "500MB"
    volumes:
      - "./data:/data"
      - "./music:/music"

...
```
3. Run the container (`docker compose up`), and observe the logs. It'll state that the transcoding cache size is indeed set at 500MB. 
4. Transcode >500MB in files. I use symfonium (android) to 'offline cache' some artists. 
5. Observe the transcoding cache. It'll be over 500MB. (`du -hs ./data/cache/transcoding`)
6. Restart the docker container and observe the cache size again. It'll be trimmed back to <500MB. 

### Platform information

 - Navidrome version: deluan/navidrome:0.47.5
 - Browser and version: n/a. Using app. 
 - Operating System: Docker on x86. Alpine linux host OS. 

### Additional information

Any other information that may be relevant or give context to the problem.
 - I'm running navidrome behind a traefikv2 reverse proxy. But that shouldn't affect this issue.
 - Client used: Symfonium android app. It has the option to transcode everything it streams / downloads. I'm using the 'offline cache' feature to test this.
