### ISSUE TITLE
Set Listenbrainz-API URL or Integration of Maloja scrobble (or custom scrobble)

### ISSUE THREAD

**Issue by iluvatyr** [navidrome/navidrome#1838]
Since this is an open-source project, why not make it possible to scrobble to any service I want to (also selfhosted). 
I am running a maloja instance, and therefore it would be perfect to have native integration also for their API.

 But since this project is already able to scrobble to last.fm and listenbrainz, it means that the necessary code is actually already there, so it is very easy to add the option to change the URL it scrobbles to. Many services can be selfhosted (listenbrainz, maloja). Therefor it is necessary to be able to switch the URL it scrobbles to, while the actual scrobbling code can remain untouched, as these services already are compliant with the listenbrainz api.
 
 A simple environment variable with the Listenbrainz API-KEY and one for the Listenbrainz-URL, with the default URL being set to the standard listenbrainz url it scrobbles to right now, would suffice without changing anything for existing users.
EXAMPLE:
 ND_LISTENBRAINZ_ENABLED: "true"
 ND_LISTENBRAINZ_URL: "https://my-selfhosted-scrobbler.mydomain.com"
 ND_LISTENBRAINZ_APIKEY: "a8zasfjfaut89ajsdkazu8a9873uaasdjffhga83wzhansdzua98asdnaduw8"

From what I see, I think the only necessary step is to have a environment variable that would change the apiBaseUrl = "https://api.listenbrainz.org/1/" in line 14 :
https://github.com/navidrome/navidrome/blob/a56d5bc8503bc984d24c2642fa323ac854fff0ef/core/agents/listenbrainz/client.go

Sidenote: I'd like to also note, that it is somehow inconsistent, that the API-Key for Last.fm  or spotify can be added via environment variables, but the listenbrainz can only be enabled, and then the API-Key has to be added through the Personal settings. Maybe there is some reasoning behind I did not get yet.

Greetings

**Comment by jrabensc** [comment]
This would be awesome. If anyone else is waiting for this feature: https://github.com/sentriz/gonic already supports a custom musicbrainz url.

**Comment by metalheim** [comment]
Absolutely makes sense to have this. Someone already made a PR for this #1774

Regarding:
>Sidenote: I'd like to also note, that it is somehow inconsistent, that the API-Key for Last.fm or spotify can be added via environment variables, but the listenbrainz can only be enabled, and then the API-Key has to be added through the Personal settings. Maybe there is some reasoning behind I did not get yet.

There is perfect reasoning for this. The spotify/last.fm integrations that you can set via config/env variables are only used for **metadata enhancements** (artist images, artist bio, top songs, radio). That means one API-key can be used for all users, it doesn't harm.

The last.fm/listenbrainz connection you setup for your user will only be used for this specific user. Because you would want to scrobble *your own listening history* only to *your* lastfm/listenbrainz account. But another user would want to scrobble to its own lastfm/listenbrainz account.

**Comment by iluvatyr** [comment]
Thanks for letting me know. I actually used the search function but didnt find anything, Now when I search I find the other Issues. Sorry for that. anyway. Good that theres a pull request! Hope it gets merged soon

**Comment by deluan** [comment]
Closed by #1774

**Comment by jrabensc** [comment]
Did anyone make this work?
I'm getting this error when setting up the token: `ListenBrainz could not be linked: Invalid token.`

This is my docker-compose file:

```
   environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_AUTOIMPORTPLAYLISTS: "false"
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_SPOTIFY_ID: xxx
      ND_SPOTIFY_SECRET: xxx
      ND_LISTENBRAINZ_ENABLED: "true"
      ND_LISTENBRAINZ_BASEURL: http://xxx:42010/apis/listenbrainz
      ND_LOGLEVEL: "info"
      ND_SCANNER_GENRESEPARATORS: ","
```
