### ISSUE TITLE
Loss of playlist information when 'transferring' install from linux to docker

### ISSUE THREAD

**Issue by althonich** [navidrome/navidrome#1916]
### Description

After installing Navidrome for docker, I used "/var/lib/navidrome" as the data volume path. What's peculiar is that the songs in the playlist do show for a fraction of a second, then I get hit with "No results found".

### Expected Behaviour

I had expected for the playlist to be populated with the songs I had put in my playlist earlier

### Steps to reproduce

1. Install Navidrome using the linux install instructions.
2. Did the following commands to 'uninstall' Navidrome as a normal linux install to prepare for running application as docker only: 
``` systemctl stop navidrome.service
systemctl disable navidrome.service
rm /etc/systemd/system/navidrome.service
systemctl daemon-reload
systemctl reset-failed
```
3. Set up docker-compose.yml as following:
```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "/music"
    volumes:
      - "/var/lib/navidrome:/data"
      - "/path/to/Music:/music:ro"
```
4. Connect to the Navidrome server as usual and go to a previously created playlist. It should load for a second before disappearing into the ether! 👻

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: LibreWolf (98.0.2-1)
 - Operating System: Raspbian GNU/Linux 11 (bullseye) with Docker
 - Online client with LibreWolf as previously stated

### Additional information

I followed instructions to 'uninstall' from a post on the Navidrome subreddit. (https://libreddit.de/ianzm8)

I added a song to the playlist and now that is the only song on it. I hope this doesn't mean my playlist is gone now as that took a good amount of time to make!

Good thing I am transferring from Spotify so I can keep track from there and I just have to spend time making the playlist again as I have a gut feeling I just written over whatever data could've been accessed from there. Though I've lost some time here personally, hopefully this will help contribute to making this wonderful software even easier to use for many others!

Now that I have added a song to one of these 'corrupted' playlists, it seems that when I restart Navidrome I don't get that preview with my playlist any more, it just goes straight to my one song I added. I really should've just tested on the playlist with 1 song in it before!
