### ISSUE TITLE
After reinstalling to docker, no non-browser clients recognise the server and cannot connect

### ISSUE THREAD

**Issue by althonich** [navidrome/navidrome#1993]
### Description

After reinstalling Navidrome as a docker application, none of my clients (apart from the normal browser client) recognise the server, giving a number of errors.

### Expected Behaviour

Just for all the clients I used to recognise Navidrome server as my browser has no issue doing so (browsers tested to work well on multiple devices).

### Steps to reproduce

1. Install Navidrome using the linux install instructions.
2. Did the following commands to 'uninstall' Navidrome as a normal linux install to prepare for running application as docker only: 
``` systemctl stop navidrome.service
systemctl disable navidrome.service
rm /etc/systemd/system/navidrome.service
systemctl daemon-reload
systemctl reset-failed
```
3. Set up docker-compose.yml as following:
```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "/music"
    volumes:
      - "/var/lib/navidrome:/data"
      - "/path/to/Music:/music:ro"
```
4. Try to connect to server from another client.

I don't know where this happened or if these steps will reproduce the errors I've been experiencing; but this (following from another issue I had made a month ago) were the last changes I had made before just giving up on making my little music server.

### Platform information

 - Navidrome version: 0.47.5 (86fe1e3b)
 - Browser and version: LibreWolf (v106.0.2-1)
 - Operating System: Raspbian GNU/Linux 11 (bullseye) with Docker
 - Dsub client on Android (Version 5.5.3)
 - Sonixd (Version 0.15.3 (0.15.3))

### Additional information

Any other information that may be relevant or give context to the problem.

 - I followed instructions to 'uninstall' from a post on the Navidrome subreddit. (https://libreddit.de/ianzm8)
 - Screenshots of errors: (Sonixd and dSub respectively)
![Screen Shot 2022-11-15 at 5 32 35 am](https://user-images.githubusercontent.com/73888096/201771453-fe40bc88-e72a-47a8-87f9-2b9b947aa717.png)
![signal-2022-11-15-054049](https://user-images.githubusercontent.com/73888096/201771463-4a7eff4d-fe6d-4888-8477-a57ee7e10d99.png)
