### ISSUE TITLE
[Bug]: Wrong MusicFolder from config file

### ISSUE THREAD

**Issue by RodolfoFigueroa** [navidrome/navidrome#2274]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

No matter the value of `MusicFolder` set in `navidrome.toml`, Navidrome always tries to scan `/music`.

### Expected Behavior

For Navidrome to scan the folder set in `MusicFolder`

### Steps To Reproduce

1. Set `MusicFolder` in `navidrome.toml` file.
2. Start Navidrome.
3. Navidrome will try to read `/music`.

### Environment

```markdown
- OS:Debian 11
- Browser: N/A
- Client: N/A
```

### How Navidrome is installed?

Docker

### Configuration

```toml
MusicFolder = "/data2/media/music"
DataFolder = "/data"
CoverArtPriority = "embedded"
LogLevel="trace"
```

```
version: "3"
services:
    navidrome:
        image: deluan/navidrome:latest
        container_name: navidrome
        restart: unless-stopped
        user: 1000:1000
        ports:
            - 4533:4533
        environment:
            - PUID=1000
            - PGID=1000
            - ND_CONFIGFILE=/navidrome.toml
        volumes:
            - /docker/appdata/navidrome:/data
            - /srv/dev-disk-by-uuid-173e0c09-7fd6-490d-b35a-df78889e818f/data/media/music:/data1/media/music
            - /srv/dev-disk-by-uuid-6c701ffa-9385-43a9-b37f-704f50282a8c/data/media/music:/data2/media/music
            - /home/<user>/docker/navidrome/navidrome.toml:/navidrome.toml
```

### Relevant log output

```shell
navidrome  | Loaded configuration from '/navidrome.toml': &conf.configOptions{
navidrome  |     ConfigFile:                       "/navidrome.toml",
navidrome  |     Address:                          "0.0.0.0",
navidrome  |     Port:                             4533,
navidrome  |     MusicFolder:                      "/music",
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
