### ISSUE TITLE
[Bug]: HTTP 416 on Symfonium Offline

### ISSUE THREAD

**Issue by vbabiy** [navidrome/navidrome#2287]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.49.3

### Current Behavior

Server is throwing 416 errors on file downloads in Symfonium

### Expected Behavior

File to download

### Environment

```markdown
- OS: Ubuntu 20.04
- Client: Latest Symfonium
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/nas/Media/Music/Library'
TranscodingCacheSize = '150MiB'
LogLevel = 'DEBUG'
ScanSchedule = '@every 1h'
EnableSharing = true

[Scanner]
Extractor = 'ffmpeg'

[Prometheus]
Enabled = true
MetricsPath = '/metrics_vb_zone_9192010'
```

### Relevant log output

```shell
Mar 29 11:45:47 navidrome navidrome[298]: time="2023-03-29T11:45:47Z" level=warning msg="HTTP: GET http://<server>/rest/stream.view?id=037c13627017d1906675f9b877d8111c&u=vbabiy&t=[REDACTED]&s=[REDACTED]&v=1.13.0&c=Symfonium&f=json" elapsedTime=1ms httpStatus=416 remoteAddr=10.10.100.134 requestId=navidrome/OCuvAPT3s6-238134 responseSize=33 userAgent="Symfonium/4.3.0 (Linux;Android 13)"
Mar 29 11:50:20 navidrome navidrome[298]: time="2023-03-29T11:50:20Z" level=warning msg="HTTP: GET http://<server>/rest/stream.view?id=ee7f8bacccdfd2a6af2cc956414c3602&u=vbabiy&t=[REDACTED]&s=[REDACTED]&v=1.13.0&c=Symfonium&f=json" elapsedTime=2.1ms httpStatus=416 remoteAddr=10.10.100.134 requestId=navidrome/OCuvAPT3s6-238576 responseSize=33 userAgent="Symfonium/4.3.0 (Linux;Android 13)"
```

### Anything else?

I am get some music but others fail.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
