### ISSUE TITLE
[Bug]: With certain folder strictures, unable to recreate docker image when pulling newest version

### ISSUE THREAD

**Issue by emes81** [navidrome/navidrome#2310]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.1 (not the latest - the problem is with the update itself!)

### Current Behavior

My folder structure looks like this:

    volumes:
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/config0/navidrome/data:/data
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/media/music-all/music-archive:/music/archive:ro
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/media/music-all/music-main:/music/main:ro
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/media/music-all/music-mixes:/music/mixes:ro

There are further folders located under /music-all (however, I do not want these in my Navi library. I also do not want to change the folder structure and re-scan, as that would involve the loss of playlists.)

When I go into Portainer, Containers, click Recreate and select "Re-pull image", I get the following error message:

Failure
Duplicate mount point: /music

This has occurred since the Navidrome version no. that implemented local artist images (apologies, can't find the version number). Previously, recreation + pull latest successfully updated Navidrome. 

### Expected Behavior

The "Duplicate mount point: /music" error should not occur; alll three mounts should be recognised as subfolders within /music

### Steps To Reproduce

1.  In Portainer, install Navidrome docker container with folder structure as noted above
2.  The error message noted above will be shown

### Environment

```markdown
- OS: Open Media Vault 6.3.7-1
- Browser: Firefox 111.0.1 on Fedora 37
- Client: N/A
```

### How Navidrome is installed?

Docker

### Configuration

```yml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome

    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      - PUID=1000
      - PGID=100
      - ND_LASTFM_ENABLED=false
      - ND_LISTENBRAINZ_ENABLED=false
      - ND_ENABLEEXTERNALSERVICES=false
      - ND_COVERARTPRIORITY=embedded, folder.*, cover.*, front.*
      - ND_SCANSCHEDULE=1h
      - ND_DATAFOLDER=/data
      - ND_ENABLECOVERANIMATION=true
      - ND_ENABLESHARING=true
      - ND_LOGLEVEL=info  
      - ND_SESSIONTIMEOUT=24h
      - ND_ENABLETRANSCODINGCONFIG=true
      - ND_IMAGECACHESIZE=500MB
      - ND_AUTOIMPORTPLAYLISTS=false
      - ND_DEFAULTTHEME=Spotify-ish
      - ND_ENABLECOVERANIMATION=false
      - ND_ENABLESTARRATING=false
      - ND_ENABLEFAVOURITES=true
      - ND_DEVACTIVITYPANEL=true
      - ND
      - ND_COVERJPEGQUALITY=100


    volumes:
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxxx/config0/navidrome/data:/data
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxxx/media/music-all/music-archive:/music/archive:ro
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxxx/media/music-all/music-main:/music/main:ro
      - /srv/dev-disk-by-uuid-xxxxxxxxxxxxx/media/music-all/music-mixes:/music/mixes:ro
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
