### ISSUE TITLE
[Bug]: artist not being updated in some cases

### ISSUE THREAD

**Issue by rombat** [navidrome/navidrome#2373]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

In some cases, it seems that artist is not updated.

Let's say I don't have any tracks by the artist Nujabes.

1. I add an album, _samurai champloo music record: departure_, where Nujabes is the artist of some tracks, but not the album artist.
2. Navidrome scans the collection. No artist id is created / set for those Nujabes tracks. So far, that's ok.
3. I add a new album, _Metaphorical Music_, by Nujabes, thus with Nujabes as album artist.
4. Navidrome scans the collection: artist id is created for Nujabes, this artist has now a page where I can see this album, but **only** this album, not the one added in **1.**

If i do all this, but this time by doing steps in this order: 3, 4, 1, 2 => on the artist's page, I can see all the albums where it has done track(s), while not necessarily being the album artist.

### Expected Behavior

I expect to see all albums of the artist on its page, regardless how/when I've added them and wether or not the artist is the album artist

### Steps To Reproduce

see above

### Environment

```markdown
- OS:Ubuntu
- Browser: Firefox
- Client:browser
```

### How Navidrome is installed?

Docker

### Configuration

```yaml
version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: "@every 5h"
      ND_LOGLEVEL: info
      ND_BASEURL: ""
      ND_AUTOIMPORTPLAYLISTS: "false"
      ND_ENABLECOVERANIMATION: "false"
      ND_COVERARTPRIORITY: "embedded, folder.*, cover.*, front.*, external"
      ND_SPOTIFY_ID: REDACTED
      ND_SPOTIFY_SECRET: REDACTED
      ND_IMAGECACHESIZE: "5GB"
      ND_ENABLESHARING: "true"
      ND_DEFAULTTHEME: "Nord"
      ND_SUBSONICARTISTPARTICIPATIONS: "true"
    volumes:
      - "./data:/data"
      - "./data/music:/music:ro"
      
networks:
    default:
        external:
            name: personal-services
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
