### ISSUE TITLE
[Bug]: When replacing a low quality file with a higher quality version all data is reset

### ISSUE THREAD

**Issue by saxobroko** [navidrome/navidrome#2482]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.49.3

### Current Behavior

 For example if there's a 192kbps mp3 file, and you replace it with a flac. Navidrome won't recognise they're the same and removes them from playlists, removes their play counts and ratings.

### Expected Behavior

Recognise they're the same and merge history, or copy it

### Environment

```markdown
- OS: Windows 11 22H@ (OS Build 22621.1992)
- Browser: Firefox 116.0.2 (64-bit)
- Client: Feishin 0.3.0
```

### How Navidrome is installed?

Package

### Configuration

```toml
MusicFolder = "/volume1/Morpheus/Media/Music"
DefaultLanguage = "en"
EnableTranscodingConfig = "true"
ND_SPOTIFY_ID = "secret"
ND_SPOTIFY_SECRET = "secret"
```

### Anything else?

May be related to #1226 and #1660 

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
