### ISSUE TITLE
[Bug]: Can't change password since SSO implementation

### ISSUE THREAD

**Issue by khalimerot** [navidrome/navidrome#2494]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

When trying to change navidrome password from user settings for subsonic client, it tells me my password are not maching, and refuse to change it.

Old password (from before authelia implementation) is still working for subsonic client

I have double, triple check my password and they were the same.

/rest/* and /share/* are whitelisted in authelia

My reverse proxy in Nginx Reverse Proxy Manager.

I also tried with another admin user to change the password, and i have the same error.

### Expected Behavior

Changing password in user settings, must work.

### Environment

```markdown
- OS:Unraid 6.12.3
- Browser: Chrome
- Client:Webbrowser
```

### How Navidrome is installed?

Docker

### Relevant log output

```shell
2023/08/26 07:53:22 Updating user: Errors: map[currentPassword:ra.validation.passwordDoesNotMatch]
time="2023-08-26T07:53:22Z" level=warning msg="HTTP: PUT http://xxxx.xxxx.xx/api/user/0b28d003-8588-4429-8b5f-cc9c4b93bfff" elapsedTime="467.315µs" httpStatus=400 remoteAddr="172.18.0.1:43000" requestId=6bbb13b2036f/frOmu19tEU-000256 responseSize=67
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by khalimerot** [comment]
It seems it was a problem related to my database.
I had another problem with client registration (symfonium) i reported on their forum.

I had to remove all players from the database manually, and since, the registration problem, and password change seems to work...

https://support.symfonium.app/t/navidrome-cant-register/2369/3

**Comment by C8opmBM** [comment]
hey, could you please share your authelia config and how you integrated navidrome?

I use authelia for immich, outline, OCIS and portainer, but couldn't find any working tutorial for navidrome.
Thanks!

**Comment by khalimerot** [comment]
Hi, i'm using nginx proxy manager:

NPM CONFIG : 

```
location /authelia {
internal;
set $upstream_authelia http://**authelia_local_IP:port**/api/verify;
proxy_pass_request_body off;
proxy_pass $upstream_authelia;    
proxy_set_header Content-Length "";

# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
client_body_buffer_size 128k;
proxy_set_header Host $host;
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr; 
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 4 32k;

send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;
}

location / {
set $upstream_app $forward_scheme://$server:$port;
proxy_pass $upstream_app;

auth_request /authelia/api/verify;
auth_request_set $target_url https://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $email $upstream_http_remote_email;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header Remote-User $user;
proxy_set_header Remote-Email $email;
proxy_set_header Remote-Groups $groups;

error_page 401 =302 https://**authelia.domain.fqdn**/?rd=$target_url;

client_body_buffer_size 128k;

proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

**set_real_ip_from 172.20.0.0/16; #Docker network IP RANGE
set_real_ip_from 172.18.0.0/16; #Docker network IP RANGE**

real_ip_header CF-Connecting-IP;
real_ip_recursive on;

}
```
Authelia config : 

```
  rules:
    ## Rules applied to everyone
    - domain: 'navidrome.icka.eu'
      policy: bypass
      resources:
      - '^/rest([/?].*)?$'
      - '^/share([/?].*)?$'
```

```
    - domain: 'navidrome.icka.eu'
      policy: one_factor
      subject:
        - 'group:Navidrome'
```

i'm using a Synology as directory server.

**Comment by khalimerot** [comment]
oh, and about the bug, it wasn't a bug, it was me being stupid.

I didn't read, and think it was asking me to type the new password twice as i'm used to.

But istead it ask for the old password, and the new.

**Comment by C8opmBM** [comment]
Great that you solved it then :))

And thanks for your reply.

So, just to make sure, there is no cliend id setup needed for navidrome, similar to this below?

Example

```
identity_providers:
  oidc: xxxx
    clients:
      - id: immich
        description: My Photos
        secret: xxxx
        sector_identifier: ''
        public: false
        authorization_policy: two_factor
        consent_mode: implicit
        audience: [immich]
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://xxxx
          - https:/xxxx
          - app.immich:/
          - https:/xxxx/api/oauth/mobile-redirect
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
```
