### ISSUE TITLE
[Bug]: Desktop Notifications unavailable in Icecat Browser

### ISSUE THREAD

**Issue by jessienab** [navidrome/navidrome#2509]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 (8b93962f)

### Current Behavior

When attempting to enable desktop notifications in the [IceCat web browse](https://en.wikipedia.org/wiki/GNU_IceCat)r (which is simply a reskin and reconfiguration of legal text, taken from a direct Firefox ESR code export), the option is greyed out with the following error text:
This browser does not support desktop notifications or you are not accessing Navidrome over https

Please see this old screenshot (I took a year ago) showcasing how notifications work fine with Firefox. This is my own self-hosted Navidrome running, over HTTPS, using nginx as reverse proxy.

![Screenshot_2022-05-11_17-52-53](https://github.com/navidrome/navidrome/assets/99688442/ab5a08b4-c5f4-41e2-b4e0-c3a94e5c9ad8)

* This issue is still present in the near-latest IceCat release I am testing with, 102.13.0esr (64-bit)
* I have tested as well with a completely new IceCat profile, with no change in behaviour.
* I have test by faking the user agent to a Firefox user agent, with no change.
* I have NOT blocked new requests for notifications, in about:preferences.

![Screenshot_2023-09-04_23-19-53](https://github.com/navidrome/navidrome/assets/99688442/84ee5b68-2744-4978-a245-07706ff6a07d)

### Expected Behavior

The toggle for Desktop Notifications should be available for people using IceCat, or perhaps other browsers outside the mainstream scope, whether they are forks or otherwise.

### Steps To Reproduce

1. Compile or download a precompiled copy of the IceCat web browser. The easiest method is compiling using the [AUR build](https://aur.archlinux.org/packages/icecat), since FSF *still* does not provide newer prebuilts beyond 60.7.0
2. Login to your navidrome instance that is hosted on HTTPS
3. Go to profile, Personal (upper left)
4. Check if Desktop Notifications are enabled

### Environment

```markdown
- OS: Arch Linux , kernel 6.4.12-arch1-1
- Browser: GNU IceCat 102.13.0esr (64-bit)
- Client: Navidrome WebUI
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
Address = '127.0.0.1'
Port = '12345'
LogLevel = 'INFO'
BaseUrl = '/navidrome'
MusicFolder = '/Music/'
DataFolder = '/home/user/.config/navidrome'
ScanSchedule = '@every 24h'
TranscodingCacheSize = '1024MiB'
ImageCacheSize = '1024MiB'
EnableTranscodingConfig = 'true'
EnableDownloads = 'true'
EnableFavourites = 'true'
LastFM.Enabled = 'false'
ListenBrainz.Enabled = 'false'
Prometheus.Enabled = 'false'
EnableLogRedacting = 'true'
EnableCoverAnimation = 'false'
CoverJpegQuality = '80'
UILoginBackgroundUrl = 'example.com'
```

### Relevant log output
There is no relevant log output for this, other than this blurb which contains the User Agent and any other related call information from the browser. The HTTP call is irrelevant I feel.

```shell
DEBU[0019] HTTP: GET http://example.com/navidrome/rest/getCoverArt?u=user&t=[REDACTED]&s=[REDACTED]&f=json&v=1.8.0&c=NavidromeUI&id=id&_=2022-07-09T04%3A55%3A05Z&size=300  elapsedTime=882ms httpStatus=200 remoteAddr=192.168.0.2 requestId=userPC/AF0FH7HC2e-000038 responseSize=7155 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
