### ISSUE TITLE
[Bug]: some times some song stuck

### ISSUE THREAD

**Issue by aaronsuns** [navidrome/navidrome#2530]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

589cdcd5bc90

### Current Behavior

navidrome version:
```
deluan/navidrome                                                              latest    589cdcd5bc90   7 months ago    153MB
```
started with docker compose
```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_COVERARTPRIORITY: cover.*, folder.*, front.*, embedded
    volumes:
      - "/data2/navidrome_data:/data"
      - "/data2/music:/music:ro"

```

Problem:

Most song works fine,but some song stuck there, could not find any error in server log while this happen, looks like a client issue, for a working flow, after rest/stream call there should be a api/song/<long hash id>  call, but for the stuck one, there is no api/song/xxx call.
![Screenshot from 2023-09-19 20-08-38](https://github.com/navidrome/navidrome/assets/2472284/cae81830-ebc7-45af-8db8-8eab3edbd69c)

### Expected Behavior

song should not stuck, a better way would be even if a song is stuck, skip it play next song, otherwise the playlist is useless.

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
