### ISSUE TITLE
[Bug]: Default opus reencoding is unseekable

### ISSUE THREAD

**Issue by RubenTeixeira** [navidrome/navidrome#2563]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3 SNAPSHOT (2cd4358)

### Current Behavior

When requested by client application (Synfonium on this instance), the transcodes to the default OPUS format of the tracks are unseekable, meaning you can't fast forward or rewind. The behaviour of the client is unpredictable on this situation and they can even restart the stream when clicking on FF or R.
I configured the server to force the player in question to use the following reencode command:
`ffmpeg -i %s -map 0:a -b:a %bk -v 0 -c:a libopus -f ogg -`
Efectively encapsulating the track in a OGG, which fixed the issue. This is fine, but it would be great if this was normal behaviour, otherwise one will have to configure every player for every user to use this transcoding command.

### Expected Behavior

Being able to seek through transcoded tracks using default server configuration.

### Steps To Reproduce

1. Default server configuration
2. Configure client to a maximum bitrate of 128Kb/s
3. Try to seek to the middle of the track as soon as the stream starts

### Environment

```markdown
- OS: Debian 11
- Client: Synfonium (5.9.0) and Substreamer (6.0.43)
```

### How Navidrome is installed?

Built from sources

### Configuration

```toml
MusicFolder = '/var/media/NAS/MUSIC'
LogLevel = 'WARN'
Address = 'localhost'
DefaultTheme = 'Spotify-ish'
SearchFullString = 'true'
RecentlyAddedByModTime = 'false'
PasswordEncryptionKey = 'redacted'
EnableStarRating = 'false'
TranscodingCacheSize = '256MiB'
EnableTranscodingConfig = 'true'
ScanSchedule = '@every 12h'
EnableSharing = 'true'
SubsonicArtistParticipations = 'true'
CoverJpegQuality = '100'
EnableCoverAnimation = 'false'
OnlyAlbumArtists = 'false'
Scanner.ArtistSeparators = ';/,&'
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
