### ISSUE TITLE
[Bug]: Non-ascii characters in album name cause Unknown Album

### ISSUE THREAD

**Issue by mneuburg-livefront** [navidrome/navidrome#2617]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

An album tag **Shakespeare’s Restless World** results in Navidrome displaying the album as **[Unknown Album]**, and so does an album tag **James Joyce’s Ulysses**. I'm guessing that this is due to the "smart apostrophe" in the album name, as this is a non-ascii character.

### Expected Behavior

All my other album titles (hundreds, maybe thousands) are correctly portrayed in Navidrome. I would have expected these two albums to have their correct names as well.

### Steps To Reproduce

Tag a song with the album name  **Shakespeare’s Restless World** and have Navidrome index it. Look at your albums thru the web interface. You will not see this album; instead, you will see  **[Unknown Album]**.

### Environment

```markdown
- OS: Mac OS 10.13.6
- Browser: Safari 17.1 (19616.2.9.11.7) on Mac OS 14.1.1
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/Volumes/TomThumb/music'
ScanSchedule = '@every 12h'
EnableExternalServices = false
DataFolder = '/Volumes/Humlet/Users/matt/navidrome'
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
