### ISSUE TITLE
Unix socket not able to be used by any user other than navidrome user

### ISSUE THREAD

**Issue by chennin** [navidrome/navidrome#2625]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.0 (fee0f40a)

### Current Behavior

Nginx running as not-root, not-navidrome, cannot connect to the Navidrome socket because the permissions on the socket are 755 and owned by the navidrome user. I receive a 502 Bad Gateway in my browser.

```sh
musicstream@<server>:~$ systemctl --user restart container-navidrome.service
musicstream@<server>:~$ ls -l navidrome/socket/
total 0
srwxr-xr-x 1 musicstream musicstream 0 Nov 17 10:38 navidrome.sock
```

### Expected Behavior

Access via browser does not throw a 502

### Steps To Reproduce

Set Navidrome up to listen on a Unix socket.  Try to access the socket as not-root and not the same user Navidrome is running as, such as via Nginx proxy.

### Environment

```markdown
- OS: Ubuntu 22.04.3
- Browser: Firefox 119.0.1 on Arch Linux
- Client: n/a
```

### How Navidrome is installed?

Docker

### Configuration

```toml
LogLevel = 'INFO'
#ScanSchedule = '* */12 * * *'
ScanSchedule = '@every 8h'
TranscodingCacheSize = '150MiB'
AuthWindowLength = "60s"
Prometheus.Enabled = true
Prometheus.MetricsPath = "/metrics"
ReverseProxyWhitelist = "10.0.2.100/32"
UILoginBackgroundUrl = "https://i.imgur.com/bS1dPE8.jpg"
Address = "unix:/data/socket/navidrome.sock"


Navidrome is run via podman with systemd integration:

ExecStart=/usr/bin/podman run --cidfile=%t/%n.ctr-id --cgroups=no-conmon --rm --sdnotify=conmon --replace -d --userns=keep-id --name navidrome --user 1015:1016 -v /home/musicstream/music:/music -v /home/musicstream/navidrome:/data -e ND_CONFIGFILE=/data/navidrome.toml docker.io/deluan/navidrome:latest


Nginx proxy upstream is configured as:


upstream music {
#  server 127.0.0.1:4533;
  server unix:/run/music-socket/navidrome.sock;
  keepalive 2;
  zone upstreams 2M;
}


You may notice the paths don't match; I'm omitting the full path setup, but nginx can see it:


~# docker-compose  exec nginx ls -Al /run/music-socket/navidrome.sock;
srwxr-xr-x 1 1015 1016 0 Nov 17 10:10 /run/music-socket/navidrome.sock
```

### Relevant log output

```shell
Loaded configuration from '/data/navidrome.toml': &conf.configOptions{
    ConfigFile:                   "/data/navidrome.toml",
    Address:                      "unix:/data/socket/navidrome.sock",

time="2023-11-17T15:30:03Z" level=info msg="----> Navidrome server is ready!" address="unix:/data/socket/navidrome.sock" startupTime=40.1ms tlsEnabled=false

2023/11/17 10:14:52 [crit] 125#125: *177 connect() to unix:/run/music-socket/navidrome.sock failed (13: Permission denied) while connecting to upstream, client: <ip>, server: music.<server>, request: "GET /favicon.ico HTTP/2.0", upstream: "http://unix:/run/music-socket/navidrome.sock:/favicon.ico", host: "music.<server>", referrer: "https://music.<server>/app/"
```

### Anything else?

From `man 7 unix`:

```
   Pathname socket ownership and permissions
       [...]

       On Linux, connecting to a stream socket object requires write permission on that socket;
```

Please change the default socket permission, or let it be configurable.

Re: https://github.com/navidrome/navidrome/issues/1477#issuecomment-1489255140 : Set; 777?; It is.

*Workaround*

Yes, it works if I manually set the permissions to 777.  And this is a poor workaround, but since I am using systemd I can use it to set the permissions every time in the unit file:

```
ExecStartPost=/usr/bin/sleep 1
ExecStartPost=/usr/bin/chmod 777 /home/musicstream/navidrome/socket/navidrome.sock
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
