### ISSUE TITLE
[Bug]: ND does not respest LastFM.Enabled = false

### ISSUE THREAD

**Issue by gerroon** [navidrome/navidrome#2634]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

develop

### Current Behavior

I disabled LastFm integration, and it still tries to connect to Last fm for various stuff

### Expected Behavior

It should not connect to LasrFM

### Environment

```markdown
- OS: Debian
- Browser: Firefox
```

### How Navidrome is installed?

Docker

### Configuration

```toml
# This is just an example! Please see available options to customize Navidrome for your needs at
# https://www.navidrome.org/docs/usage/configuration-options/#available-options

LogLevel = 'DEBUG'
ScanSchedule = '@every 48h'
TranscodingCacheSize = '150MiB'
LastFM.Enabled = false
RecentlyAddedByModTime = true
CoverArtPriority = cover.*, cover*.*, album.*, folder.*, front.*, embedded, external
AutoImportPlaylists = false
```

### Relevant log output
You can see it tries to connect to LF sites. I block them in my proxy that is why it cant connect them, regardless it should not query them anway.

```shell
navidrome_1  | time="2023-11-18T23:54:17Z" level=error msg="Error calling LastFM/album.getInfo" album="NonStop[www.Az-Side.com]" error="Get \"https://ws.audioscrobbler.com/2.0/?album=NonStop%5Bwww.Az-Side.com%5D&api_key
=[REDACTED]&artist=A.Nagilbaz%5Bwww.Az-Side.com%5D&format=json&lang=en&mbid=&method=album.getInfo\": dial tcp 0.0.0.0:443: connect: connection refused" mbid= requestId=1ca0f328ffb9/CFJTiZ73aL-000028 username=USER
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
