### ISSUE TITLE
[Bug]: 0.50.0 (latest) docker image not running on archs different than linux/amd64

### ISSUE THREAD

**Issue by mrapacz** [navidrome/navidrome#2636]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version
0.50.0 i.e. the latest docker image, sha:
`2cf4442b0099a5810cfaf2aa0a6718ced41222d3c41551a8dbc4949a885bb089`

- https://hub.docker.com/layers/deluan/navidrome/0.50.0/images/sha256-2cf4442b0099a5810cfaf2aa0a6718ced41222d3c41551a8dbc4949a885bb089?context=explore
- https://hub.docker.com/layers/deluan/navidrome/latest/images/sha256-2cf4442b0099a5810cfaf2aa0a6718ced41222d3c41551a8dbc4949a885bb089?context=explore
### Current Behavior

Pulling and running the `deluan/navidrome:latest` image results in an error:
```
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
```
If you inspect the [:latest docker image page](https://hub.docker.com/layers/deluan/navidrome/latest/images/sha256-2cf4442b0099a5810cfaf2aa0a6718ced41222d3c41551a8dbc4949a885bb089?context=explore), the os/arch associated with the image is:
`linux/amd64`
The previous versions also ran fine on other architectures.
The [docs](https://www.navidrome.org/docs/installation/docker/) say `Docker images are available for the linux/amd64, linux/arm/v6, linux/arm/v7 and linux/arm64 platforms. They include everything needed to run Navidrome.`

### Expected Behavior

My docker stack upgraded the image automatically, I expected to keep running navidrome as I did up until now.

### Steps To Reproduce

(On raspberry pi - or anything else that's `aarch64`)
Follow the instructions specified in the docs - https://www.navidrome.org/docs/installation/docker/

### Environment

```markdown
- OS: Running ubuntu server on raspberry pi 4
- Browser: Firefox
- Client: Docker
```

### How Navidrome is installed?

Docker

### Configuration
The default setup from the docs:
```yaml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/path/to/data:/data"
      - "/path/to/your/music/folder:/music:ro"
```

### Relevant log output

```shell
Attaching to navidrome_navidrome_1
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
navidrome_navidrome_1 exited with code 1
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
navidrome_1  | standard_init_linux.go:228: exec user process caused: exec format error
```

### Anything else?

Downgrading to **0.49.3** seems to be the temporary workaround (works smooth for me).

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
