### ISSUE TITLE
[Bug]: Random Error in Logs

### ISSUE THREAD

**Issue by kobayashi90** [navidrome/navidrome#2735]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.2

### Current Behavior

Recently started to throw an Error after boot, generates to make the same error after awhile.

### Expected Behavior

Well not throwing an error.

### Steps To Reproduce

Either happend after adding an Playlist without any Track in it or after adding an artist image into my media (/music) folder.
Not sure what exactly caused it.

### Environment

```markdown
- OS: Docker
- Browser: Lastest Firefox
- Client: NavidromeUI Web
```

### How Navidrome is installed?

Docker

### Configuration

```toml
"Env": [
            "ND_SESSIONTIMEOUT=24h",
            "ND_SCANSCHEDULE=24h",
            "ND_TRANSCODINGCACHESIZE=0",
            "ND_ENABLEFAVOURITES=false",
            "ND_MAXSIDEBARPLAYLISTS=2",
            "ND_ENABLEUSEREDITING=false",
            "ND_ENABLESTARRATING=false",
            "ND_BASEURL=",
            "ND_SCANNER_EXTRACTOR=ffmpeg",
            "ND_ENABLETRANSCODINGCONFIG=false",
            "ND_LASTFM_ENABLED=false",
            "ND_AUTOIMPORTPLAYLISTS=false",
            "ND_ENABLELOGREDACTING=true",
            "ND_DEVAUTOLOGINUSERNAME=Guest",
            "ND_DEVACTIVITYPANEL=false",
            "ND_LOGLEVEL=info",
            "ND_ENABLESHARING=true",
            "ND_LISTENBRAINZ_ENABLED=false",
            "ND_IMAGECACHESIZE=50GB",
            "ND_AUTHREQUESTLIMIT=10",
            "ND_DEFAULTTHEME=Spotify-ish",
            "ND_ENABLEDOWNLOADS=false",
            "ND_DEFAULTLANGUAGE=en",
            "ND_ENABLEGRAVATAR=false",
            "ND_ENABLEEXTERNALSERVICES=false",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "ND_MUSICFOLDER=/music",
            "ND_DATAFOLDER=/data",
            "ND_PORT=4533",
            "GODEBUG=asyncpreemptoff=1"
```

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference

 

 -> github.com/deluan/rest.(*Controller).GetAll

 ->   /go/pkg/mod/github.com/deluan/rest@v0.0.0-20211101235434-380523c4bb47/controller.go:52

    github.com/deluan/rest.GetAll.func1

      /go/pkg/mod/github.com/deluan/rest@v0.0.0-20211101235434-380523c4bb47/handlers.go:27

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server/nativeapi.getPlaylist.func1.1

      /github/workspace/server/nativeapi/playlists.go:32

    github.com/navidrome/navidrome/server/nativeapi.getPlaylist.func2

      /github/workspace/server/nativeapi/playlists.go:42

    github.com/navidrome/navidrome/server/nativeapi.(*Router).routes.func1.(*Router).addPlaylistTrackRoute.func4.1

      /github/workspace/server/nativeapi/native_api.go:113

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5.(*Mux).routeHTTP

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5.(*Mux).ServeHTTP

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73

    github.com/go-chi/chi/v5.(*Mux).Mount.func1

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.JWTRefresher.func1

      /github/workspace/server/auth.go:261

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server/nativeapi.(*Router).routes.func1.Authenticator.func2.1

      /github/workspace/server/auth.go:250

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/chain.go:31

    github.com/go-chi/chi/v5.(*Mux).routeHTTP

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5.(*Mux).ServeHTTP

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73

    github.com/go-chi/chi/v5.(*Mux).Mount.func1

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.jwtVerifier.jwtVerifier.Verify.func1.func2

      /go/pkg/mod/github.com/go-chi/jwtauth/v5@v5.1.1/jwtauth.go:72

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.authHeaderMapper.func1

      /github/workspace/server/auth.go:178

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.requestLogger.func1

      /github/workspace/server/middlewares.go:33

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.loggerInjector.func1

      /github/workspace/server/middlewares.go:64

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5/middleware.(*Compressor).Handler-fm.(*Compressor).Handler.func1

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/middleware/compress.go:213

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.clientUniqueIDMiddleware.func1

      /github/workspace/server/middlewares.go:156

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.serverAddressMiddleware.func1

      /github/workspace/server/middlewares.go:175

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.(*Server).initRoutes.robotsTXT.func4.1

      /github/workspace/server/middlewares.go:75

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/navidrome/navidrome/server.(*Server).initRoutes.Heartbeat.func3.1

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/middleware/heartbeat.go:21

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5/middleware.Recoverer.func1

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/middleware/recoverer.go:45

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5/middleware.RealIP.func1

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/middleware/realip.go:36

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5/middleware.RequestID.func1

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/middleware/request_id.go:76

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/cors.(*Cors).Handler-fm.(*Cors).Handler.func1

      /go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/unrolled/secure.(*Secure).Handler-fm.(*Secure).Handler.func1

      /go/pkg/mod/github.com/unrolled/secure@v1.13.0/secure.go:203

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/chain.go:31

    github.com/go-chi/chi/v5.(*Mux).routeHTTP

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444

    net/http.HandlerFunc.ServeHTTP

      /usr/local/go/src/net/http/server.go:2136

    github.com/go-chi/chi/v5.(*Mux).ServeHTTP

      /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:90

    net/http.serverHandler.ServeHTTP

      /usr/local/go/src/net/http/server.go:2938

    net/http.(*conn).serve

      /usr/local/go/src/net/http/server.go:2009

    created by net/http.(*Server).Serve in goroutine 59

      /usr/local/go/src/net/http/server.go:3086
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
