### ISSUE TITLE
[Bug]: Jukebox mode under Windows

### ISSUE THREAD

**Issue by korzhyc** [navidrome/navidrome#2767]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.2

### Current Behavior

Navidrome successfully launches mpv:
```
[   0.048][v][cplayer] audio ready
[   0.048][v][cplayer] starting audio playback
[   0.048][v][cplayer] playback restart complete @ 0.000000, audio=playing, video=eof (paused)
```
That's all, no action. mpv is pending. Subsonic client freezes at the beginning of playback. 

### Expected Behavior

Proper socket check under Windows.

### Environment

```markdown
- OS: Windows Server 2022
- Browser: -
- Client: DSub 5.5.3, Ultrasonic 4.8.0
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
LogLevel = 'info'
DataFolder = '.\data'
MusicFolder = 'F:\Music'
Jukebox.Enabled = true
Jukebox.Devices = [
  ['realtek_spdif', 'wasapi/{eebf0aab-21a9-4d68-8759-22f533c960e7}']
]
MPVPath = 'C:\Srv\Navidrome\jukebox\mpv.com'
```

### Relevant log output

```shell
time="2024-01-06T01:50:19+03:00" level=error msg="error or timeout waiting for control socket" error="timeout reached: 3s" socketname="C:\\Users\\MusicSvc\\AppData\\Local\\Temp\\mpv-ctrl-38aef8102d918d23bc960e9c439c1a6d.socket"
```

### Anything else?

https://github.com/natefinch/npipe/blob/v2/README.md

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
