### ISSUE TITLE
[Bug]: Upgrade to 0.51.0 Failed to apply new migrations

### ISSUE THREAD

**Issue by metalheim** [navidrome/navidrome#2805]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0 (fd61b29a)

### Current Behavior

After migrating from docker tag `pr-2719` to `0.51.0` navidrome fails to start and throws fatal error:

```
Version: 0.51.0 (fd61b29a)
time="2024-01-22T08:28:23Z" level=fatal msg="Failed to apply new migrations" error="error: found 1 missing migrations:\n\tversion 20231209211223: /github/workspace/db/migration/20231209211223_alter_lyric_column.go"
```

### Expected Behavior

Migrations are applied correctly, disregarding which version was previously installed.

### Steps To Reproduce

1. deploy container from tag `pr-2719`
2. Change docker-compose to tag `0.51.0` 
3. docker-compose up
4. navidrome fails to start and throws fatal error "Failed to apply new migrations" (see full error above)

### Environment

```markdown
- OS: Synology OS DSM 7.0
```

### How Navidrome is installed?

Docker

### Configuration

```yaml
navidrome:
      container_name: navidrome
      restart: unless-stopped
      image: deluan/navidrome:0.51.0
      volumes:
         - /volume2/nasdata/Music/:/music/Music:ro
         - /volume2/nasdata/HörbücherHörspiele:/music/HörbücherHörspiele
         - /volume2/nasdata/Podcasts:/music/Podcasts
         - /volume1/docker/navidrome:/data
      ports:
         - 4533:4533
      environment:
         - ND_CONFIGFILE=/data/navidrome.toml
         - TZ=Europe/Berlin
         - PUID=1026
         - PGID=101
      logging:
         driver: "json-file"
         options:
            max-size: "10m"
```

### Relevant log output
```
Version: 0.51.0 (fd61b29a)
time="2024-01-22T08:28:23Z" level=fatal msg="Failed to apply new migrations" error="error: found 1 missing migrations:\n\tversion 20231209211223: /github/workspace/db/migration/20231209211223_alter_lyric_column.go"
```

### Anything else?

For now, i switched back to build with tag `pr-2719`

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
