### ISSUE TITLE
[Bug]: Lyrics are displayed repeatedly

### ISSUE THREAD

**Issue by xinruoyusixian** [navidrome/navidrome#2815]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0 (fd61b29a)

### Current Behavior

When switching music continuously, the lyrics display area will display the lyrics of the previous switched song, and the lyrics that are currently playing will also be displayed. I took a screenshot of the screen recording (in the link below) showing what went wrong
当连续切换音乐的时候，歌词显示区域会显示之前的被切换歌的歌词，并且也会显示当前播放的歌词。我截取了一段录屏，里面展示了出现问题的画面

https://github.com/navidrome/navidrome/assets/20371229/3f0a144f-761a-43c9-aa64-2f7bf85281da

### Expected Behavior

Normally, the lyrics of the switched song should not be displayed, and only the lyrics that are currently playing should be displayed

### Steps To Reproduce

Switch to the next lyric when a song is not finished, or switch songs continuously

### Environment

```markdown
- OS:centso7
- Browser:chrome 120
- Client:webUI
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
# This is just an example! Please see available options to customize Navidrome for your needs at
# https://www.navidrome.org/docs/usage/configuration-options/#available-options
#启动命令 ./navidrome --configfile ./navidrome.toml 
MusicFolder = "/mnt/sda2/Public/Music"  #存储音乐库的文件夹。可以是只读的
DataFolder =  "/mnt/sda2/Configs/Navidrome"  #用于存储应用程序数据 （DB） 的文件夹
CacheFolder = "/mnt/sda2/Configs/Navidrome/cache"  #用于存储缓存数据（转码、图像等）的文件夹
LogLevel = "info"  #日志级别。用于故障排除。可能的值：error、warn、info、debug、trace
Address = "0.0.0.0" #服务器将绑定到的地址。 可以是 IPv4 或 IPv6。还支持 Unix 套接字文件的 unix：/path/to/file
BaseUrl = ""  #用于在代理后面配置 Navidrome 的基本 URL（例如：/music、https://music.example.com）
Port = 4533  #Navidrome 将使用的 HTTP 端口
DefaultLanguage = "zh-Hans"  #设置从新浏览器登录时 UI 使用的默认语言。此值必须与 resources/i18n 中的某个文件名匹配。例如：对于简体中文，它必须是 zh-Hans（区分大小写）
#转码相关
TranscodingCacheSize = "1000MB"  #转码缓存的大小。设置为“0”以禁用缓存
SessionTimeout = "24h"  #Navidrome 在关闭 Web UI 空闲会话之前将等待多长时间
ImageCacheSize = "1000MB"  #图像（艺术作品）缓存的大小。设置为“0”以禁用缓存
EnableTranscodingConfig = "TRUE"  #在 UI 中启用转码配置A
#高级选项
EnableSharing = 'TRUE'  #启用共享功能
#TLSCert = ""  #TLS 证书文件的路径，其中应包含签名链（如果有）
#TLSKey = ""  #TLS 密钥文件的路径
#UILoginBackgroundUrl = 'random music image from Unsplash.com'  #更改登录页面中使用的背景图像
UIWelcomeMessage = "外奥康姆"  #在登录屏幕添加欢迎消息
#AuthRequestLimit  = 5  #在 AuthWindowLength 期间，可以从单个 IP 处理多少个登录请求。设置为 0 可禁用限制
AuthWindowLength = "20s"  #身份验证速率限制的窗口长度
#AutoImportPlaylists = 'TRUE'  #启用/禁用 .m3u 播放列表自动导入
CoverArtPriority = 'cover.*, folder.*, front.*, embedded, external'  #配置顺序以查找封面艺术图像。使用特殊的嵌入值从音频文件中获取嵌入的图像
ArtistArtPriority = 'artist.*, album/artist.*, external'  #配置顺序以查找艺术家图像。
#CoverJpegQuality = 75  #设置调整大小的封面艺术图像的 JPEG 质量百分比
#DefaultDownsamplingFormat = 'opus'  #客户端请求缩减采样时要转码的格式（指定不带格式的 maxBitrate）

#DefaultTheme = 'Dark'  #设置 UI 从新浏览器登录时使用的默认主题。此值必须与 UI 中的某个选项匹配
#EnableArtworkPrecache = 'TRUE'  #启用新添加音乐的图像预缓存
#EnableCoverAnimation = 'TRUE'  #控制 UI 中的播放器是否对专辑封面进行动画处理（旋转）
#EnableDownloads = 'TRUE'  #在UI中启用该选项以从服务器下载音乐/专辑/艺术家/播放列表
#EnableExternalServices = 'TRUE'  #将此设置为 'FALSE' 可完全禁用所有外部集成
EnableFavourites = 'TRUE'  #在UI中为歌曲/专辑/艺术家启用切换“Heart”/“Loved”（映射到Subsonic Clients中的“Star”/“Starred”）
#EnableGravatar = 'FALSE'  #使用 Gravatar 图像作为用户配置文件图像。需要填写用户的电子邮件
#EnableLogRedacting = 'TRUE'  #是否应在日志中编辑（隐藏）敏感信息（如令牌和密码）
#EnableMediaFileCoverArt = 'TRUE'  #如果设置为 'FALSE'，则在请求歌曲 CoverArt 时将返回专辑 CoverArt
#EnableReplayGain = 'TRUE'  #在UI中启用ReplayGain选项

EnableStarRating = 'TRUE'  #在 UI 中启用 5 星评级
EnableUserEditing = 'TRUE'  #使普通用户能够编辑其详细信息并更改其密码
#FFmpegPath = ""  #ffmpeg 可执行文件的路径。当 Navidrome 找不到它，或者您想使用特定版本时使用它
#GATrackingID = "" # (disabled) 将基本信息发送到您自己的 Google Analytics（分析）帐户。 必须采用 UA-XXXXXXXX 格式
#IgnoredArticles = "The El La Los Las Le Les Os As O A"  #对艺术家进行排序/索引时忽略的文章列表
#Jukebox.Enabled = 'FALSE'  #启用自动存储塔模式（在服务器硬件上播放音频） 详情请点击这里
#Jukebox.Devices = ""  #(auto detect) 自动存储塔可以使用的设备列表。详情请点击这里
#Jukebox.Default = ""  #(auto detect)用于自动存储塔模式的设备（如果有多个 Jukebox.Devices 条目）。详情请点击这里
#LastFM.ApiKey = 'Navidrome project’s shared ApiKey'  #Last.fm ApiKey
#LastFM.Enabled = 'TRUE'  #将此设置为 'FALSE' 以完全禁用 Last.fm 集成
#LastFM.Language = "en"  #用于从 Last.fm 检索传记的语言的两个字母代码
#LastFM.Secret = 'Navidrome project’s shared Secret'  #Last.fm 共享密钥
#ListenBrainz.BaseURL = 'https://api.listenbrainz.org/1/  #设置此选项可覆盖默认的 ListenBrainz 基 URL（适用于 Maloja* 等自托管解决方案）
#ListenBrainz.Enabled = 'TRUE'  #将此设置为 'FALSE' 可完全禁用 ListenBrainz 集成
#MaxSidebarPlaylists = '100'  #设置 UI 边栏中显示的最大播放列表数量。请注意，非常大的数字可能会导致 UI 性能问题。
#MPVPath = "" # (search in PATH) mpv 可执行文件的路径。用于自动存储塔模式
#PasswordEncryptionKey = '-  #用于加密数据库中的密码的密码。详情请点击这里
#PlaylistsPath = ".:**/**" #从何处搜索和导入播放列表。可以是文件夹/glob 的列表（在 Windows 上用 ：（或 ;）分隔）。路径必须相对于 MusicFolder
#Prometheus.Enabled = 'FALSE'  #使用 Prometheus 指标启用额外终端节点。
#Prometheus.MetricsPath = "/metrics"  #Prometheus 指标的自定义路径。可用于阻止未经授权的指标请求。
#RecentlyAddedByModTime = 'FALSE'  #使用按“最近添加”排序时音乐文件的修改时间。否则，使用导入时间
#ReverseProxyUserHeader = "Remote-User"  #包含来自经过身份验证的代理的用户名的 HTTP 标头
#ReverseProxyWhitelist = ""  #允许使用反向代理身份验证的 IP CIDR 的逗号分隔列表，空表示“全部拒绝”
#Scanner.Extractor = "taglib"  #选择元数据提取器实现。选项：taglib 或 ffmpeg
#Scanner.GenreSeparators = ";/,"  #用于拆分流派标签的分隔符列表
#Scanner.GroupAlbumReleases = 'FALSE'  #“'TRUE'”将具有相同艺术家 + 专辑标题的专辑分组为一张专辑;“'FALSE'”将重新发行（=不同的发行日期）拆分为单独的专辑
#ScanSchedule = "@every 1m"  #使用“cron”语法配置定期扫描。要完全禁用它，请将其设置为“0”
#SearchFullString = 'FALSE'  #匹配可搜索字段中任意位置的查询字符串，而不仅仅是单词边界。适用于单词不以空格分隔的语言
#Spotify.ID = ""  #Spotify 客户端 ID。 如果您想要艺术家图像，则为必填项
#Spotify.Secret = ""  #Spotify 客户端密钥。如果需要艺术家图像，则为必填项
#SubsonicArtistParticipations = 'FALSE'  #请求艺人专辑时，请包括艺人参与的专辑（例如：各种艺人合辑）
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
