### ISSUE TITLE
[Bug]: Jukebox mode cannot be limited on a per-User basis

### ISSUE THREAD

**Issue by mneuburg-livefront** [navidrome/navidrome#2849]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0 (fd61b29a)

### Current Behavior

Once Jukebox mode is turned, _any_ User can make the server machine play music on-site.

### Expected Behavior

I expect to be able to limit Jukebox mode on a per-User basis. This could probably be as simple as ruling that only admin users can use Jukebox mode. I dare not share access to my Navidrome server with others, now that Jukebox mode exists, because any user can suddenly make music come out of my living room speakers at any time of day or night.

My guess is that this is just an oversight and that a fix should be pretty easy. Thanks for considering it!

### Steps To Reproduce

When I make a new non-admin user and log in as that user, I am able, through my Navidrome client, to make the server play in jukebox mode. That should not be possible.

### Environment

```markdown
- OS: MacOS 10.13.6
- Browser: Safari
- Client: iSub
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/Volumes/TomThumb/music'
ScanSchedule = '@every 12h'
EnableExternalServices = false
DataFolder = '/Volumes/Humlet/Users/matt/navidrome'
Jukebox.Enabled = true
MPVPath = '/Applications/mpv.app/Contents/MacOS/mpv'
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
