### ISSUE TITLE
[Bug]: Since version 0.51, search3.view returns blank instead of JSON

### ISSUE THREAD

**Issue by RedKage** [navidrome/navidrome#2862]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1

### Current Behavior

On version 0.51.1 calling:
`http://navidrome/rest/search3.view?query=%22%22&songOffset=0&songCount=1000&albumOffset=0&albumCount=0&artistOffset=0&artistCount=0&u=[REDACTED]&p=[REDACTED]&v=1.13.0&c=Symfonium&f=json`

Returns an empty response with code 200
```
DEBU[0010] HTTP: GET http://navidrome/rest/search3.view?query=%22%22&songOffset=0&songCount=1000&albumOffset=0&albumCount=0&artistOffset=0&artistCount=0&u=[REDACTED]&p=[REDACTED]&v=1.13.0&c=Symfonium&f=json  elapsedTime=33.1ms httpStatus=200 remoteAddr="[REDACTED]" requestId=navidrome/ZxKCjL2dEi-000001 responseSize=0 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```
Note `responseSize=0`

I had this behavior on 0.51.0 as well.

### Expected Behavior

The same database, with version 0.50.2 returns a proper JSON:
```
DEBU[0004] HTTP: GET http://navidrome/rest/search3.view?query=%22%22&songOffset=0&songCount=1000&albumOffset=0&albumCount=0&artistOffset=0&artistCount=0&u=[REDACTED]&p=[REDACTED]&v=1.13.0&c=Symfonium&f=json  elapsedTime=65ms httpStatus=200 remoteAddr="[REDACTED]" requestId=navidrome/svEGraGs6e-000001 responseSize=689400 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```
Note `responseSize=689400`

### Environment

```markdown
- OS: LXC on Alpine
- Client: Symfonium 8.0.0a / cURL
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
LogLevel = 'DEBUG'
ScanSchedule = '@every 1h'
TranscodingCacheSize = '150MiB'
AutoImportPlaylists = true
MusicFolder = '/media/musics'
DataFolder = '/opt/navidrome'
#Address = 'unix:/root/navidrome.sock'
Address = '0.0.0.0'
Port = '80'
EnableExternalServices = false
EnableStarRating = true
EnableFavourites = false
```

### Relevant log output

Full logs attached:
[log 0.50.2.txt](https://github.com/navidrome/navidrome/files/14313543/log.0.50.2.txt)
[log 0.51.1.txt](https://github.com/navidrome/navidrome/files/14313545/log.0.51.1.txt)

### Anything else?

This issue causes Symfonium to crash during sync because it expects a JSON response.
Navidrome on its own on the webui seems to work perfectly fine though.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
