### ISSUE TITLE
[Bug]: Navidrome is splitting an album into multiple albums

### ISSUE THREAD

**Issue by mneuburg-livefront** [navidrome/navidrome#2867]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.0 (fd61b29a)

### Current Behavior

I have an album which Navidrome persists in categorizing into two albums with identical names (Boccherini Cello Concertos).

### Expected Behavior

I expect all songs tagged with the album name Boccherini Cello Concertos to be categorized by Navidrome as a single album.

### Steps To Reproduce

Run Navidrome against a folder containing the two enclosed songs. Navidrome will create two separate albums named called Boccherini Cello Concertos. I can see no justification for this behavior; the tags are completely consistent between the two songs.

### Environment

```markdown
- OS: Mac OS 10.13.6 (17G14042)
- Browser: Safari
- Client: iSub, but it doesn't matter, I've tried several
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/Volumes/TomThumb/music'
ScanSchedule = '@every 12h'
EnableExternalServices = false
DataFolder = '/Volumes/Humlet/Users/matt/navidrome'
Jukebox.Enabled = true
MPVPath = '/Applications/mpv.app/Contents/MacOS/mpv'
```

### Anything else?

[tracks.zip](https://github.com/navidrome/navidrome/files/14323091/tracks.zip)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
