### ISSUE TITLE
[Bug]: Can't read 12 channels wavepack files

### ISSUE THREAD

**Issue by Jerroder** [navidrome/navidrome#2884]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1 (6d253225)

### Current Behavior

Wavepack files which contain 12 channels aren't played, nothing happens when clicking on a track. They are not being transcoded because they technically are compatible format, but downmixing to stereo would work (it work locally with ffmpeg).

### Expected Behavior

The file should be played or transcoded.

### Steps To Reproduce

1. Get a 12 channels wavepack file
2. Try to play it

### Environment

```markdown
- OS: Windows 10 21H2
- Browser: Firefox 123.0

- OS: iOS 17.3.1
- Client: Amperfy
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = "/mnt/Music"
Address = "xxx.xxx.xxx.xxx"
EnableExternalServices = "false"
DataFolder = "/mnt/Music/.navidrome_cache"
CoverArtPriority = "Cover.*, embedded"
EnableTranscodingConfig = "false"
DefaultDownsamplingFormat = "mp3"
```

### Relevant log output

```shell
Feb 25 21:48:21 navidrome navidrome[3684]: time="2024-02-25T21:48:21+01:00" level=info msg="Streaming file" artist="The Cinematic Orchestra" bitRate=0 cached=false format=raw originalBitRate=5398 originalFormat=wv requestId=navidrome/qouLSWkTRy-000455 title="To Build a Home (feat. Patrick Watson)" transcoding=false user=Mike username=Mike
```

### Anything else?

```
Format                                   : WavPack
Format profile                           : 4.16
Format settings                          : Lossless
Duration                                 : 6 min 9 s
Bit rate mode                            : Variable
Bit rate                                 : 5 399 kb/s
Channel(s)                               : 12 channels
Channel layout                           : L R C LFE Lb Rb Lc Rc Cb Ls Rs Tc
Sampling rate                            : 48.0 kHz
Bit depth                                : 24 bits
Compression ratio                        : 0.213
Stream size                              : 238 MiB (100%)
Encoding settings                        : -h -hh -x6 -m
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
