### ISSUE TITLE
[Bug]: "TagLib: Error reading metadata from file. Skipping" => creating "Unknown Album"

### ISSUE THREAD

**Issue by rombat** [navidrome/navidrome#2908]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1

### Current Behavior

I sometimes have an "Unknown Album" created, with (properly tagged) tracks coming from all my library:
![image](https://github.com/navidrome/navidrome/assets/9024503/f8bd926b-7c1c-4e6d-8c37-583ba461fcc0)
Reading the logs, I realized that it was due to the following error:
```
navidrome    | time="2024-03-14T05:43:01Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/04 - Magic One.m4a"
navidrome    | time="2024-03-14T05:43:02Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/06 - Mr General.m4a"
navidrome    | time="2024-03-14T05:43:03Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/10 - Why.m4a"
navidrome    | time="2024-03-14T05:43:04Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/13 - Awake.m4a"
navidrome    | time="2024-03-14T05:43:05Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/03 - Get Ready.m4a"
navidrome    | time="2024-03-14T05:43:06Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/07 - Letter.m4a"
```

Whenever this happens, if I want to fix this, I either have to:

- save the file tags once again to force an update on the next quick scan
- do a full scan (which is too slow with my server. storage is actually located outside the server, it's a s3-compatible storage, mounted with rclone)

### Expected Behavior

Unknown album/Unknow Artist should be only for untagged files

### Steps To Reproduce

I don't really know ho to reproduce that, but [here's](https://www.dropbox.com/scl/fi/l02a08517fxrtb13s83ey/03-Get-Ready.m4a?rlkey=8us20fzl8upbiapkkpuf8w0tk&dl=0) one of those files

### Environment

```markdown
- OS: Ubuntu 20.04
- Browser: Firefox 123.0.1
- Client: Firefox 123.0.1
```

### How Navidrome is installed?

Docker

### Configuration

```yaml
version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: "@every 5h"
      ND_LOGLEVEL: info
      ND_BASEURL: ""
      ND_ENABLECOVERANIMATION: "false"
      ND_COVERARTPRIORITY: "embedded, folder.*, cover.*, front.*, external"
      ND_SPOTIFY_ID: REDACTED
      ND_SPOTIFY_SECRET: REDACTED
      ND_LASTFM_APIKEY: REDACTED
      ND_LASTFM_SECRET: REDACTED
      ND_IMAGECACHESIZE: "5GB"
      ND_ENABLESHARING: "true"
      ND_DEFAULTTHEME: "Nord"
      ND_SUBSONICARTISTPARTICIPATIONS: "true"
      ND_PLAYLISTSPATH: "Music/_navidrome_playlists"
      ND_SEARCHFULLSTRING: "true"
    volumes:
      - "./data:/data"
      - "./data/music:/music:ro"
      
networks:
    default:
        external:
            name: personal-services
```

### Relevant log output

```shell
navidrome    | time="2024-03-14T05:43:01Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/04 - Magic One.m4a"
navidrome    | time="2024-03-14T05:43:02Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/06 - Mr General.m4a"
navidrome    | time="2024-03-14T05:43:03Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/10 - Why.m4a"
navidrome    | time="2024-03-14T05:43:04Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/13 - Awake.m4a"
navidrome    | time="2024-03-14T05:43:05Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/03 - Get Ready.m4a"
navidrome    | time="2024-03-14T05:43:06Z" level=warning msg="TagLib: Error reading metadata from file. Skipping" error="cannot parse file media file" filePath="/music/Music/Musique generale/Orange Street/2002 - Shakin'Up/07 - Letter.m4a"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
