### ISSUE TITLE
[Bug]: No catalogue sync with clementine since 0.50.1

### ISSUE THREAD

**Issue by stonie08** [navidrome/navidrome#2924]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1

### Current Behavior

The player Clementine can't fetch the available music on the navidrome server via the subsonic API anymore. It will say "Fetching Subsonic Library" briefly then just not do anything. Music that has been shown as available before will be removed. Navidrome's log output will not show anything even at "trace" debug level.
Files that were added to an active playlist in a previous version play without any issues, but I can't add any new because there aren't any available.
If I downgrade to 0.49.2, 0.49.3 or 0.50.0 it works without any problems. Upgrading to 0.50.1 and refreshing the library will remove any items from the list.

### Expected Behavior

Refreshing the library in a subsonic compatible player should refresh the library and show the available music

### Steps To Reproduce

1. Install Clementine
2. Go to Tools -> Preferences -> Subsonic
3. Configure demo server: https://demo.navidrome.org user: demo, password: demo and press login, then OK
4. In the left menu -> Internet -> right click on Subsonic -> "Refresh catalogue"
5. Observe that nothing happens. Retry with 0.50.1 or older Navidrome installation which will work fine.

### Environment

```markdown
- OS: Debian Bookworm
- Client: Clementine 1.3.1
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = "/home/library/Music_combined"
ND_LOGLEVEL="trace"
EnableTranscodingConfig = false
EnableDownloads = true
ImageCacheSize = 0
TranscodingCacheSize = 0
BaseUrl = "/nav"
AutoImportPlaylists = false
EnableSharing = true
EnableExternalServices = false
```

### Relevant log output

```shell
Doesn't cause any log output at debug or trace level
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
