### ISSUE TITLE
[Bug]: Jukebox playback graceful shutdown

### ISSUE THREAD

**Issue by korzhyc** [navidrome/navidrome#2978]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.51.1-SNAPSHOT (6dcfe4d4)

### Current Behavior

When I stop Navidrome service while jukebox playback is active, this leads to the following possible outcomes:

Variant 1: mpv process got roughly killed.
Variant 2 (less frequent): mpv got restarted and is left in free flight (until the track ends).

### Expected Behavior

A proper handling of the shutdown command.

### Environment

```markdown
- OS: Windows Server 2022, mpv-0.37.0-x86_64-v3
- Client: DSub 5.5.3, Ultrasonic 4.8.0
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
# shawl add --name "Navidrome" --no-restart --stop-timeout=5000 --log-rotate bytes=524288 --log-cmd-as "Navidrome" --log-dir "c:\Srv\Navidrome\data" --cwd "C:\Srv\Navidrome" --env "MPV_HOME=C:\Srv\Navidrome\jukebox" -- "navidrome.exe"

# navidrome.toml:
LogLevel = 'debug'
DataFolder = '.\data'
MusicFolder = 'F:\Music'
Jukebox.Enabled = true
Jukebox.Devices = [
  ['realtek_spdif', 'wasapi/{eebf0aab-21a9-4d68-8759-22f533c960e7}']
]
MPVPath = 'c:\bin\mpv\mpv.com'
```

### Relevant log output

```shell
---------- Variant 1 ----------
...
time="2024-04-21T18:37:09+03:00" level=debug msg="Unpausing track" [CUT]
time="2024-04-21T18:37:34+03:00" level=info msg="Received termination signal" signal=interrupt
time="2024-04-21T18:37:34+03:00" level=info msg="Stopping HTTP server"
time="2024-04-21T18:37:34+03:00" level=debug msg="Scheduler: stop"
time="2024-04-21T18:37:34+03:00" level=info msg="Closing Database"
time="2024-04-21T18:37:34+03:00" level=info msg="Navidrome stopped, bye."
[EOF]

mpv.log:
...
[   0.114][v][cplayer] audio ready
[   0.114][v][cplayer] starting audio playback
[   0.114][d][ao/wasapi] Thread Resume
[   0.114][d][ao/wasapi] Thread Reset
[   0.114][v][cplayer] playback restart complete @ 0.000018, audio=playing, video=eof
[   1.113][v][ao/wasapi] OnPropertyValueChanged triggered on device {0.0.0.00000000}.{eebf0aab-21a9-4d68-8759-22f533c960e7}
[   1.113][v][ao/wasapi] Changed property: {9855c4cd-df8c-449c-a181-8191b68bd06c},0
[EOF]


---------- Variant 2 ----------
...
time="2024-04-21T18:50:35+03:00" level=info msg="Received termination signal" signal=interrupt
time="2024-04-21T18:50:35+03:00" level=info msg="Stopping HTTP server"
time="2024-04-21T18:50:35+03:00" level=debug msg="Scheduler: stop"
time="2024-04-21T18:50:35+03:00" level=info msg="Hitting end-of-stream, signalling on channel"
time="2024-04-21T18:50:35+03:00" level=debug msg="Track switching detected"
time="2024-04-21T18:50:35+03:00" level=debug msg="Closing resources" [CUT]
time="2024-04-21T18:50:35+03:00" level=debug msg="Switching to next song" queue="#Items: 21, idx: 16, [CUT]"
time="2024-04-21T18:50:35+03:00" level=debug msg="Loading track" [CUT]
time="2024-04-21T18:50:35+03:00" level=debug msg="Executing mpv command" [CUT]
time="2024-04-21T18:50:35+03:00" level=debug msg="Socket found" retries=1 waitTime=121.5ms
time="2024-04-21T18:50:35+03:00" level=debug msg="Unpausing track" [CUT]
time="2024-04-21T18:50:38+03:00" level=info msg="Closing Database"
time="2024-04-21T18:50:38+03:00" level=info msg="Navidrome stopped, bye."
[EOF]
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
