### ISSUE TITLE
[Bug]: Issue with AlbumPlayCountMode normalized

### ISSUE THREAD

**Issue by rombat** [navidrome/navidrome#2998]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.0-SNAPSHOT (544ae90e)

### Current Behavior

There seems to be a weird issue in some cases, probably due to the fact that sometimes, total tracks for an album is not tagged.

Here's the issue:
![image](https://github.com/navidrome/navidrome/assets/9024503/fab8bf39-e1c1-4358-ab33-1e5c5e586a40)
It says here that the album has been played 54 times.
But when I open the album (which is actually just one track, in this case), here's what I get:
![image](https://github.com/navidrome/navidrome/assets/9024503/0548e3a4-c4cb-4cc5-8993-daf00acf47ee)
The track has been played only 4 times.
My guess is that it's probably due to the fact that the file is tagged like that:
![image](https://github.com/navidrome/navidrome/assets/9024503/136d4bf4-92c9-41cc-b277-2d51cc9e993f)
without album total track 

### Expected Behavior

I don't know how it should be handled. I think it's mainly due to the fact that the track is not completely tagged, so it's not _really_ a navidrome issue, but I just wanted to let you know about this

### Steps To Reproduce

[01 - Symphony no. 7.zip](https://github.com/navidrome/navidrome/files/15211966/01.-.Symphony.no.7.zip)
here's the file, if you want to test it

### Environment

```markdown
- OS: Ubuntu
- Browser: Firefox
- Client: Firefox
```

### How Navidrome is installed?

Docker

### Configuration

```yaml
version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:develop
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: "@every 5h"
      ND_LOGLEVEL: info
      ND_BASEURL: ""
      ND_ENABLECOVERANIMATION: "false"
      ND_COVERARTPRIORITY: "embedded, folder.*, cover.*, front.*, external"
      ND_SPOTIFY_ID: REDACTED
      ND_SPOTIFY_SECRET: REDACTED
      ND_LASTFM_APIKEY: REDACTED
      ND_LASTFM_SECRET: REDACTED
      ND_IMAGECACHESIZE: "5GB"
      ND_ENABLESHARING: "true"
      ND_DEFAULTTHEME: "Nord"
      ND_SUBSONICARTISTPARTICIPATIONS: "true"
      ND_PLAYLISTSPATH: "Music/_navidrome_playlists"
      ND_SEARCHFULLSTRING: "true"
      ND_ALBUMPLAYCOUNTMODE: "normalized"
    volumes:
      - "./data:/data"
      - "./data/music:/music:ro"
      
networks:
    default:
        external:
            name: personal-services
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
