### ISSUE TITLE
[Bug]: Replaygain tags stripped from opus

### ISSUE THREAD

**Issue by c0utta** [navidrome/navidrome#2999]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.0

### Current Behavior

Navidrome strips out Replaygain tags when transcoding to opus.  MP3 is fine.

### Expected Behavior

Tags available to be read by applications

### Steps To Reproduce

Using the Web UI, download an opus transcoded file with Replaygain tags and review the tags of the resulting file.

### Environment

```markdown
- OS: Debian 10
- Browser: Edge 124.0.2478.51 (Official build) (64-bit) on Windows 11
- Client: dSub, Symfonium
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder="/mnt"
DevActivityPanel=false
EnableStarRating=false
SessionTimeout="72h"
EnableExternalServices=false
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
