### ISSUE TITLE
[Bug]: Failed to enable the service on Windows, it does not scan the music directory

### ISSUE THREAD

**Issue by Lguos** [navidrome/navidrome#3025]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

I deleted the files and services of version 0.49.3. After re-downloading the latest version of the files, I encountered a problem. Running the program in cmd allows me to open the web page for login, but it does not scan my music directory, and the service creation with nssm also fails to start.
![IMG_4610](https://github.com/navidrome/navidrome/assets/56692532/c820ca79-b4ce-4f36-a47a-35e0537e3acd)
![IMG_4611](https://github.com/navidrome/navidrome/assets/56692532/453fdcbf-2964-470b-9027-71c4757714d2)
![IMG_4612](https://github.com/navidrome/navidrome/assets/56692532/3d8903eb-4cf4-4fb2-aa64-5110d44abbb7)

### Expected Behavior

How am I going to fix it?

### Environment

```markdown
- OS:windows 10
- Browser:edge
- Client:
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
# This is just an example! Please see available options to customize Navidrome for your needs at

LogLevel = 'DEBUG'
ScanSchedule = '@every 1h'
ND_ARTISTARTPRIORITY = 'artist.*, album/artist.*, external'
ND_COVERARTPRIORITY = 'cover.*, folder.*, front.*, embedded, external'
ND_ENABLECOVERANIMATION = 'true'
DefaultTheme = 'Nord'
DefaultLanguage = 'zh-Hans'

# IMPORTANT: Use single quotes for paths in Windows
MusicFolder = 'F:\Music'

# Set this to the path of your ffmpeg executable
FFmpegPath = ' D:\Download\ffmpeg-2023-08-30-git-7aa71ab5c0-full_build\bin\ffmpeg.exe'
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
