### ISSUE TITLE
[Bug]: navidrome log is being spammed with "ReverseProxyWhitelist enabled but no proxy IP found in request context. Please report this error."

### ISSUE THREAD

**Issue by michael-ball** [navidrome/navidrome#3046]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

v0.52.5

### Current Behavior

I have set the "Address" config option to be a unix socket located at "/var/run/navidrome/navidrome.sock". Since enabling this I am getting constant messages in the navidrome log that look like this:

`time="2024-05-24T22:11:06Z" level=error msg="ReverseProxyWhitelist enabled but no proxy IP found in request context. Please report this error."`

I haven't set the "ReverseProxyWhitelist" option in my config so it should be set to whatever the default is.

### Expected Behavior

Logs are not spammed with this message.

### Steps To Reproduce

1. Set Address config option to a unix socket
2. Restart navidrome
3. Observe the navidrome log

### Environment

```markdown
- OS: Raspberry Pi OS (Debian 12.5)
- Browser: N/A
- Client: N/A
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
Address = "unix:/var/run/navidrome/navidrome.sock"
AutoImportPlaylists = true
EnableArtworkPrecache = false
EnableCoverAnimation = false
EnableTranscodingConfig = false
IgnoredArticles = "The El La Los Las Le Les Os As O A Der Die Das"
ImageCacheSize = "0"
LastFM.ApiKey = "redacted"
LastFM.Enabled = true
LastFM.Secret = "redacted"
MusicFolder = "/media/ssd/Music"
SubsonicArtistParticipations = true
TranscodingCacheSize = "0"
```

### Relevant log output

```shell
`time="2024-05-24T22:11:06Z" level=error msg="ReverseProxyWhitelist enabled but no proxy IP found in request context. Please report this error."`
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
