### ISSUE TITLE
[Bug]: ArtistArtPriority not honored

### ISSUE THREAD

**Issue by nothing2obvi** [navidrome/navidrome#3052]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

I'm using a config file and have artist art priority set like this:
```
ArtistArtPriority = "folder.*, artist.*, cover.*, external"
```

However, Navidrome is immediately using Spotify images instead of the `folder.jpg` images I have in certain artist folders. It is also not adding photos for artists who currently have no photos.

To clarify, this is happening for about a third of artists. For the other two thirds, `folder.jpg` works just fine.

I've tried a full scan. I've tried restarting and doing a full scan. What can I do about this? Thanks.

### Expected Behavior

Artist images should refresh and use the `folder.jpg` images I've placed in the artist folders.

### Steps To Reproduce

1. Set ArtistArtPriority as shown above
2. Add `folder.jpg` image to artist folder
3. Do full scan. See that artist image hasn't updated
4. Restart Navidrome
5. Do full scan. See that artist image hasn't updated

### Environment

```markdown
- OS: MacOS Sonoma 14.5 -- Docker Desktop 4.30.0
- Browser: Opera 110.0.5130.35
- Client: Web
```

### How Navidrome is installed?

Docker

### Configuration

```toml
ScanSchedule = "0 6 * * *"
LogLevel = "info"
SessionTimeout = "72h"
MusicFolder = "/music"
DataFolder = "/data"
BaseUrl = "https://navidrome.mydomain.com"
ArtistArtPriority = "folder.*, artist.*, cover.*, external"
CoverArtPriority = "cover.*, folder.*, front.*, embedded, external"
CoverJpegQuality = "100"
EnableArtworkPrecache = "true"
EnableCoverAnimation = "true"
EnableDownloads = "true"
EnableExternalServices = "true"
EnableFavourites = "true"
EnableLogRedacting = "true"
EnableMediaFileCoverArt = "true"
EnableReplayGain = "false"
EnableSharing = "true"
EnableTranscodingConfig = "true"
EnableUserEditing = "true"
IgnoredArticles = "the, a"
PasswordEncryptionKey = "password-here"
PlaylistsPath = "/playlists"
Scanner.Extractor = "taglib"
Scanner.GroupAlbumReleases = "false"
SubsonicArtistParticipations = "false"
TranscodingCacheSize = "10000 MB"
ImageCacheSize = "10000 MB"
UIWelcomeMessage = "Welcome to Navidrome :)"
Spotify.ID = "id-here"
Spotify.Secret = "secret-here"
LastFM.Enabled = "true"
LastFM.ApiKey = "other-id-here"
LastFM.Secret = "other-secret-here"
LastFM.Language = "en"
```

### Anything else?

![Screenshot 2024-05-27 at 1 01 56 AM](https://github.com/navidrome/navidrome/assets/85228035/fbef5c65-a0ea-4a96-881d-9408729f588e)

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
