### ISSUE TITLE
[Bug]: Issue with Song Search in Navidrome

### ISSUE THREAD

**Issue by ironic2** [navidrome/navidrome#3105]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

Hi Navidrome Team,

I have encountered an issue with the search functionality in Navidrome. (GUI) When searching for the song "Yesterday" by The Beatles, the song does not appear correctly in the search results, even though it is present in multiple albums in my library.

Searching via iSub - works fine !!!

Thank you for looking into this issue.

Best regards

### Expected Behavior

more search results!

### Steps To Reproduce

 

Search for "Yesterday" in the Navidrome search bar.
Observe that the song does not appear correctly in the results.
When searching for "Beetles" and then browsing the albums, the song "Yesterday" can be found in multiple albums. However, the search for "Yesterday" returns 13 albums, but they are the wrong albums. Additionally, running a direct SQL query in the database returns the correct results:
SELECT * FROM media_file WHERE title LIKE '%Yesterday%';

The database is large and has been deleted and freshly scanned. Running the following query:

SELECT COUNT(*) FROM media_file WHERE title LIKE '%Yesterday%';
Returns 315 hits, confirming that the song is indeed present in the database but not appearing correctly in the search results.

### Environment

```markdown
Operating System: Ubuntu 22.04
- Proxmox LXC 

Client: W11 :
- Browser: chrome (newest)
```

### How Navidrome is installed?

Built from sources

### Configuration

```toml
MusicFolder = "/mnt/serien/Navidrome"
ImageCache = "/var/lib/navidrome/cache"
PlaylistFolder = "/mnt/serien/Navidrome/playlists"
ScanSchedule = ""   
# ScanInterval = "0"   
MaxWorkerThreads = 8   
ScanTimeout = "480m"  
LogLevel = "debug"
LogFile = "/var/log/navidrome/navidrome.log"
DataFolder = "/var/lib/navidrome"
```

### Anything else?

installation way:
wget https://github.com/navidrome/navidrome/releases/download/v0.52.5/navidrome_0.52.5_linux_amd64.tar.gz -O Navidrome.tar.gz

sudo tar -xvzf Navidrome.tar.gz -C /opt/navidrome/

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
