### ISSUE TITLE
[Bug]: Favourites don't show in web UI but in client

### ISSUE THREAD

**Issue by Sakrecoer** [navidrome/navidrome#3178]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5 (c5560888)

### Current Behavior

When i click on the heart to "favourite" a track in the web UI, it doesn't show in `/app/#/album/starred`

However, the client on my phone will display them

### Expected Behavior

Favourites should show in the web UI

### Steps To Reproduce

1. Pick a track
2. click the heart
3. Click "Favourites" in the sidebar menu
4. Find an empty page
5. Open a connected client
6. Navigate to the favourites
7. Find the newly favoured track in there

### Environment

```markdown
- OS: ubuntu 24.04
- Browser: Firefox 128.0.3 (64-bit)
- Client: Tempo
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = "/media/usb128gb/Navidrome"
ScanSchedule = '@every 8h'
Address = "localhost"
BaseUrl = "https://domain.tld"
AuthRequestLimit = "5"
AuthWindowLength = "25200s"
DefaultTheme = "Spotify-ish"
Scanner.Extractor = "ffmpeg"
```

### Relevant log output

```shell
journalctl -u navidrome.service show no relevant information when favoriting a track or displaying the favourites tab
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
