### ISSUE TITLE
[Bug]: The scan cannot detect the mounted folder and its contents, when i use "mount --bind" to mount my folder 

### ISSUE THREAD

**Issue by LingjieJin** [navidrome/navidrome#3192]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5

### Current Behavior

I have an external hard drive(SSD) that holds all my music files. Now I use the "mount --bind" to mount the music folder in the hard disk under the Navidrome'music folder(/music).
Currently I have found the following problems：
1.After the Navidrome'service started, when I mounted a new folder under the "/music" folder, I used the scanning method of the web interface and could not find the newly added music files.
2.According to the above situation, I restarted the Navidrome service, and the music files in the newly added folder can be found and displayed on the web interface.
After testing later, I found the following situation: In the folder bound by "mount --bind", if a new music file is added, the Navidrome service will not automatically discover it. 

### Expected Behavior

I hope that the folder bound using “mount --bind“” should also be automatically detected.

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Docker

### Configuration

```toml
version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 10m
      ND_LOGLEVEL: debug  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_TRANSCODINGCACHESIZE: "4000M"
      ND_IMAGECACHESIZE: "1000M"
      ND_DEFAULTLANGUAGE: zh-Hans
      ND_UIWELCOMEMESSAGE: "Welcome to King`s Music Server"
    volumes:
      - "/mnt/4t_data/data_2/istore.data/docker.data/navidrome/docker.data:/data"
      - "/mnt/4t_data/data_2/istore.data/docker.data/navidrome/docker.music:/music:ro"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by Szeraax** [comment]
I was unable to reproduce this issue. Can you please simplify or try a different instance and let us know if you can figure anything else out further?

Here are the steps that I took:

1. creating a new dn instance
2. added files to `/mnt/nobu/music/testing`
3. Started instance up for first time
4. Created user and logged in
5. Verified album list included the albums that I copied in
6. Copied a new album and pasted into `/mnt/nobu/music/testing`
7. Ran a "quick scan" from the UI
8. I saw the album get added to the albums view

```yaml
version: "3"
services:
  ndtesting:
    image: deluan/navidrome:latest
    # user: 1000:1000 # should be owner of volumes
    ports:
      - 20018:4533
    restart: always
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: trace
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: /cherisse
    volumes:
      - ./data:/data
      - /mnt/nobu/music/testing:/music:ro
      - /etc/localtime:/etc/localtime:ro
networks: {}
```
