### ISSUE TITLE
[Bug]: Folder not scanned when name starts with "."

### ISSUE THREAD

**Issue by VonKavalier** [navidrome/navidrome#3459]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [ ] I'm using the latest version (your issue may have been fixed already)

### Version

v0.53.2

### Current Behavior

My library folder is stored like that:
```
-> Artist Name
    -> Album Name 1
        -> 01 - Song 1
        -> 02 - Song 2
     -> Album Name 2
        -> 01 - Song 1
        -> 02 - Song 2
```
I recently imported few Slipknot albums, one named `.5_ The Gray Chapter (Special Edition)`.
All the others are perfectly showing up, but this one, even though in the file system, does not appear in the UI.
My guess is that the sync command is skipping "hidden" folders, the ones with a name starting with a "."

### Expected Behavior

I expected the album to show up in Navidrome after a sync.

### Steps To Reproduce

1. import music in a folder which name starts with a "."
2. Sync library
3. Notice that music files inside that folder does not get synced

### Environment

```markdown
- OS: Linux Mint 21.3 Cinnamon
- Browser: Mozilla Firefox 132.0.1 (64-bit)
- Client: Navidrome
```

### How Navidrome is installed?

Package

### Configuration

```toml
# Load configurations from an external config file
ConfigFile = "/var/lib/navidrome/navidrome.toml"
 
# Log level. Useful for troubleshooting. Possible values: error, info, debug, trace
LogLevel = "INFO"

# IP address the server will bind to
Address = "127.0.0.1"

# HTTP port Navidrome will use
Port = "30479"

# Base URL (only the path part) to configure Navidrome behind a proxy (ex: /music)
BaseURL = "/music"

# Configure periodic scans using “cron” syntax. To disable it altogether, set it to "" (empty string)
ScanSchedule = "@every 1m30s"

# Enables transcoding configuration in the UI
EnableTranscodingConfig = "false"

# Size of transcoding cache. Set to 0 to disable cache
TranscodingCacheSize = "150MB"

# Size of image (art work) cache. Set to 0 to disable cache
ImageCacheSize = "100MB"

# Folder to store application data (DB, cache…)
DataFolder = "/var/lib/navidrome/"

# Folder where your music library is stored. Can be read-only
MusicFolder = "/media/fatass/plex/Musique"

# Enable the option in the UI to download music/albums/artists/playlists from the server
EnableDownloads = "true"

#Change background image used in the Login page
UILoginBackgroundUrl = ""

# Add a welcome message to the login screen
UIWelcomeMessage = ""

# Enable image pre-caching of new added music
EnableArtworkPrecache = "true"

# Controls whether the player in the UI will animate the album cover (rotation)
EnableCoverAnimation = "true"

# How long Navidrome will wait before closing web ui idle sessions
SessionTimeout = "24h"

# Set JPEG quality percentage for resized cover art images
CoverJpegQuality = "75"

#Configure the order to look for cover art images. Use special embedded value to get embedded images from the audio files
CoverArtPriority = "embedded, cover.*, folder.*, front.*"

# Match query strings anywhere in searchable fields, not only in word boundaries. Useful for languages where words are not space separated
SearchFullString = "false"

# List of ignored articles when sorting/indexing artists
IgnoredArticles = "The El La Los Las Le Les Os As O A"

# Enable/disable .m3u playlist auto-import
AutoImportPlaylists = "true"

# The default metadata extractor is still ffmpeg but you can use the new taglib extractor
Scanner.Extractor = "taglib"

# Last.FM ApiKey
LastFM.ApiKey = "****"

# Last.FM Shared Secret
LastFM.Secret = "****"

# Two letter-code for language to be used to retrieve biographies from Last.FM
LastFM.Language = "fr"

# Spotify Client ID
Spotify.ID = "****"

# Spotify Client Secret
Spotify.Secret = "****"

# Use Gravatar images as the user profile image. Needs the user’s email to be filled 
EnableGravatar = "false"

# Enable toggling “Heart”/“Loved” for songs/albums/artists in the UI (maps to “Star”/“Starred” in Subsonic Clients)
EnableFavourites = "true"

# Enable 5-star ratings in the UI
EnableStarRating = "true"

# Enable regular users to edit their details and change their password
EnableUserEditing = "true"

# Enable Navidrome to connect to any external service
EnableExternalServices = "true"

# Set the language by default
DefaultLanguage="fr"

# Disable the activity panel that can hang some browsers with >100% CPU usage
# See https://github.com/navidrome/navidrome/issues/1511
DevActivityPanel=false

# Enable the Sharing feature
EnableSharing="false"

# Enable SSOWat authentication for all IP addresses
# If SSOWat didn't authenticate a user, manual login will still work (eg. for API)
ReverseProxyUserHeader = "remote-user"
ReverseProxyWhitelist = "0.0.0.0/0"

# Path to ffmpeg executable. Use it when Navidrome cannot find it, or you want to use a specific version
FFmpegPath = "/usr/bin/ffmpeg"

# Enable/Disable Jukebox mode
#Jukebox.Enabled = true

#MPVPath = "/path/to/mpv"

# List of registered devices, syntax:
#  "symbolic name " - Symbolic name to be used in UI's
#  "device" - MPV audio device name, do mpv --audio-device=help to get a list

#Jukebox.Devices = [
#    # "symbolic name " "device"
#    [ "internal",     "coreaudio/BuiltInSpeakerDevice" ],
#    [ "dac",          "coreaudio/AppleUSBAudioEngine:Cambridge Audio :Cambridge Audio USB Audio 1.0:0000:1" ]
#]

# Device to use for Jukebox mode, if there are multiple entries above.
# Using device "auto" if missing
#Jukebox.Default = "dac"

# Base URL for shared links. Useful when your server address is not a public
#ShareURL = 

# Set imported playlists as public by default
#DefaultPlaylistPublicVisibility = false
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
