### ISSUE TITLE
[Bug]: Enabling LastFM scrobbling failed with "uid not received"

### ISSUE THREAD

**Issue by akhy** [navidrome/navidrome#3467]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.53.3 (13af8ed4)

### Current Behavior

The user presented with JSON error `uid not received` after approving LastFM auth

### Expected Behavior

The user get redirected back to Navidrome with LastFM integration enabled.

### Steps To Reproduce

1. Open user's personal page (e.g. https://navidrome.mydomain/app/#/personal)
2. Enable "Scrobble to Last.fm" toggle
3. Get redirected LastFM auth (in last.fm page)
   - notice that `uid` query param inside `cb` query param seem to be stripped
   - `https://www.last.fm/api/auth?api_key=REDACTED&cb=https://navidrome.REDACTED/api/lastfm/link/callback?uid`
5. Approve the auth
6. LastFM redirected the user back to Navidrome but got presented with `uid not received` JSON error (uid in the URL is blank)

### Environment

```markdown
- OS: linux
- Browser: Firefox
- Client: -
```

### How Navidrome is installed?

Docker

### Configuration

```toml
ND_SCANSCHEDULE     = "30m"
ND_LOGLEVEL         = "warn"
ND_SESSIONTIMEOUT   = "48h"
ND_MUSICFOLDER      = "/data/media/music"
ND_DATAFOLDER       = "/navidrome/data"
ND_CACHEFOLDER      = "/navidrome/cache"
ND_ENABLEGRAVATAR   = "true"
ND_COVERARTPRIORITY = "embedded, cover.*, folder.*, front.*, albumart.*, external"
ND_SPOTIFY_ID       = "xxx"
ND_SPOTIFY_SECRET   = "xxx"
ND_LASTFM_ENABLED   = "true"
ND_LASTFM_APIKEY    = "xyz"
ND_LASTFM_SECRET    = "xyz"
```

### Relevant log output

```shell
time="2024-11-11T02:43:37Z" level=warning msg="HTTP: GET http://navidrome.REDACTED/api/lastfm/link/callback?uid&token=Y_Phj2amqyYjmuF_REDACTED" elapsedTime="76.627µs" httpStatus=400 remoteAddr=REDACTED requestId=navidrome/0Ds7n1dJ6w-000216 responseSize=28
```

### Anything else?

I don't know when it starts to happen, but I recently disabled and reenabled the LastFM toggle and found it's broken (have been upgraded Navidrome several time since I enabled it successfully in the past)

https://github.com/navidrome/navidrome/blob/cd0cf7c12be08d8035c038138d25e3f6431df021/ui/src/personal/LastfmScrobbleToggle.jsx#L28

I believe the `callbackUrl` here must be URL-encoded, so the equal sign (`=`) should be encoded as `%3d`

This is what I get in the address bar when authorizing LastFM:
- https://www.last.fm/api/auth?api_key=REDACTED&cb=https://navidrome.REDACTED/api/lastfm/link/callback?uid

When I retried and manually set the URL-encoded `cb` param in browser address bar, it WORKS:
- https://www.last.fm/api/auth?api_key=REDACTED&cb=https://navidrome.REDACTED/api/lastfm/link/callback?uid%3dmynavidromeuseridhere

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
