### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NyTimez** [navidrome/navidrome#3578]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.2

### Current Behavior

Last track in queue repeats over and over and over again

### Expected Behavior

Music should stop after last track has played

### Steps To Reproduce

put some tracks in the queue and play

### Environment

```markdown
Ubuntu Jammy
Firefox 133.0.3
gui
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
LogLevel = "error"
MusicFolder = "/media/external/Music"
ScanSchedule = ""
UIWelcomeMessage = "Welcome to AllAlbums"
CoverArtPriority = "embedded"
DevShowArtistPage = true
SessionTimeout = "4h"
EnableFavourites = false
EnableStarRating = false
RecentlyAddedByModTime = true
EnableInsightsCollector = false
Spotify.ID = "4157a51402204742a
Spotify.Secret = "6d21d4e201274f4
LastFM.ApiKey = "58c91ef7a10b120
LastFM.Secret = "a55830fbdcf398974c291b
```

### Anything else?

This behaviour is not unique to this release.  It has been occurring in at least the 2-3 previous releases 

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
