### ISSUE TITLE
[Bug]: database migration issue

### ISSUE THREAD

**Issue by jobs62** [navidrome/navidrome#3581]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.2

### Current Behavior

Database migration crash with the following message 
```
navidrome-0  _   _             _     _
navidrome-0 | \ | |           (_)   | |
navidrome-0 |  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
navidrome-0 | . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
navidrome-0 | |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
navidrome-0 \_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
navidrome-0                  Version: 0.54.1-SNAPSHOT (851f54ea)
navidrome-0 
navidrome-0 time="2024-12-21T18:27:42Z" level=info msg="Upgrading DB Schema to latest version"
navidrome-0 time="2024-12-21T18:27:42Z" level=fatal msg="Failed to apply new migrations" error="ERROR 20241024125533_fix_sort_tags_collation_and_index.sql: failed to run SQL migration: failed to execute SQL query \"drop table album;\": disk I/O error: permission denied"
Stream closed EOF for seedbox/navidrome-0 (navidrome)
```

My ND instance in deployed on k8s with the following manifest

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: navidrome
  namespace: seedbox
spec:
  serviceName: navidrome
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: navidrome
          image: ghcr.io/navidrome/navidrome:0.54.2 # {"$imagepolicy": "flux-system:navidrome"}
          ports:
            - containerPort: 4533
          env:
            - name: ND_SCANSCHEDULE
              value: "12h"
            - name: ND_SESSIONTIMEOUT
              value: "24h"
            - name: ND_LOGLEVEL
              value: "info"
            - name: ND_ENABLETRANSCODINGCONFIG
              value: "false"
            - name: ND_TRANSCODINGCACHESIZE
              value: "512MB"
            - name: ND_ENABLESTARRATING
              value: "false"
            - name: ND_ENABLEFAVOURITES
              value: "false"
            - name: ND_MUSICFOLDER
              value: "/music"
            - name: ND_DATAFOLDER
              value: "/data"
            - name: GODEBUG
              value: "asyncpreemptoff=1"
            - name: ND_ENABLEINSIGHTSCOLLECTOR
              value: "false"
          volumeMounts:
            - name: config
              mountPath: /data
            - name: seedbox-media-music
              mountPath: /music
              #readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /ping
              port: 4533
          readynessProbe:
            httpGet:
              path: /ping
              port: 4533
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: navidrome-config
        - name: seedbox-media-music
          persistentVolumeClaim:
            claimName: seedbox-media-music
```

I had the same beahour on 0.54.0, 0.54.1 and 0.54.2 I tryed deleting the config PV to start fresh with the same problems. So my best guess is that 0,54.x require more privileges that previous versions but I don't know why. 

### Expected Behavior

Migration to succed

### Environment

```markdown
- OS:Talos 1.18.3
- Browser:not relevant
- Client:not relevant
```

### How Navidrome is installed?

Docker

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
