### ISSUE TITLE
[Bug]: Backup Error (unable to open database)

### ISSUE THREAD

**Issue by TheWrathKing** [navidrome/navidrome#3614]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.3

### Current Behavior

I don't understand why the backup is unable top open the database as Navidrome is working as expected.

### Expected Behavior

A fully working backup

### Environment

```markdown
- OS: Raspberry PI OS - Debian GNU/Linux 11 (bullseye) - arm64
- Browser: Firefox
- Client: Play:Sub
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = "/mnt/media/music"
DataFolder = "/var/lib/navidrome"
ScanSchedule = "@daily"
LogLevel = "trace"
BaseUrl = "/XXX"
SessionTimeout = "1h"
ImageCacheSize = "1GB"
PlaylistsPath = "playlists"
AutoImportPlaylists = "true"
IgnoredArticles = ""
RecentlyAddedByModTime = "true"
CoverArtPriority = "cover.*,embedded"
CoverJpegQuality = "85"
LastFM.ApiKey = "XXX"
LastFM.Secret = "XXX"
LastFM.Language = "fr"
Spotify.ID = "XXX"
Spotify.Secret = "XXX"
EnableDownloads = "false"
EnableGravatar = "true"
DefaultTheme = "Spotify-ish"
DefaultLanguage = "fr"
PasswordEncryptionKey = "XXX"
EnableInsightsCollector = "false"
Backup.Path = "/mnt/backup/navidrome"
Backup.Schedule = "00 11 * * 4"
Backup.Count = "2"
```

### Relevant log output

```shell
janv. 02 10:40:36 PI8 navidrome[1052550]:     Backup:                           conf.backupOptions{Count:2, Path:"/mnt/backup/navidrome", Schedule:"45 10 * * 4"},
janv. 02 10:40:36 PI8 navidrome[1052550]:     DbPath:                          "/var/lib/navidrome/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on",
.../...
janv. 02 10:40:37 PI8 navidrome[1052550]: time="2025-01-02T10:40:37+01:00" level=info msg="Scheduling periodic backup" schedule="45 10 * * 4"
janv. 02 10:40:37 PI8 navidrome[1052550]: time="2025-01-02T10:40:37+01:00" level=debug msg="Scheduler: added" entry=2 next="2025-01-02 10:45:00 +0100 CET" now="2025-01-02 10:40:37.203802664 +0100 CET"
.../...
janv. 02 10:45:00 PI8 navidrome[1052550]: time="2025-01-02T10:45:00+01:00" level=debug msg="Scheduler: wake" now="2025-01-02 10:45:00.000197644 +0100 CET"
janv. 02 10:45:00 PI8 navidrome[1052550]: time="2025-01-02T10:45:00+01:00" level=debug msg="Scheduler: run" entry=2 next="2025-01-09 10:45:00 +0100 CET" now="2025-01-02 10:45:00.000197644 +0100 CET"
janv. 02 10:45:00 PI8 navidrome[1052550]: time="2025-01-02T10:45:00+01:00" level=error msg="Error backing up database" elapsed="589.971µs" error="unable to open database file: no such file or directory"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
