### ISSUE TITLE
[Bug]: Jukebox works, but playlist stops after a long song

### ISSUE THREAD

**Issue by anhell** [navidrome/navidrome#3637]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.3 (734eb30a)

### Current Behavior

The next song won't play after a long song.

I've tested it in shuffle mode and in order, after this 9:03 song, the next one won't play, after a 8:26 song the next one will play normally, and a 11:13 song is cut short near the end around 10:12 and the next one don't play.

The playlist will keep going until one of those songs, then it stops completely, the Subsonic client can't control the server anymore (I don't think the client is very optimized for Jukebox anyway, but I couldn't find another with this mode) and I have to restart the container.

### Expected Behavior

The current song will end normally independently of it's length and the next one on the list starts playing.

### Steps To Reproduce

- Start Navidrome container
- Open Subsonic client (iSub) on my phone
- Activate Jukebox mode (it's already activated from previous sessions)
- Go to Playlists > Server
- Select Playlist and select the song in question 
- Song plays (or is cut short) and the next one don't

### Environment

```markdown
- OS: 
- Browser:
- Client: iSub (iOS)
```

### How Navidrome is installed?

Docker

### Configuration

```toml
#================ toml file

#PlaylistsPath = "/"
DefaultPlaylistPublicVisibility = true
MaxSidebarPlaylists = 500
EnableCoverAnimation = false
MPVPath = "/usr/bin/mpv"
FFmpegPath = "/usr/bin/ffmpeg"
#LogLevel = "debug"
Jukebox.Enabled = true
Jukebox.Devices = [
    # "symbolic name", "device"
    [ "default", "alsa/default:CARD=PCH" ],
    [ "optical", "alsa/iec958:CARD=PCH,DEV=0" ]
]
Jukebox.Default = "optical"


#================ compose file

services:
  navidrome_server:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "navidrome_server"

    devices:
      - "/dev/snd:/dev/snd"

    entrypoint:
      - "/app/navidrome"

    environment:
      - "ND_MUSICFOLDER=/music/Songs"
      - "ND_CONFIGFILE=/data/navidrome.toml"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "ND_DATAFOLDER=/data"
      - "ND_PORT=4533"
      - "GODEBUG=asyncpreemptoff=1"

    group_add:
      - "29" # audio group ID (gid)

    image: "deluan/navidrome:latest"

    labels:
      maintainer: "deluan@navidrome.org"
      org.opencontainers.image.created: "2024-12-21T04:41:38.361Z"
      org.opencontainers.image.description: "\U0001F3A7☁️ Your Personal Streaming Service"
      org.opencontainers.image.licenses: "GPL-3.0"
      org.opencontainers.image.revision: "851f54ea5741990d7df359a3f9df6fb7a91a084c"
      org.opencontainers.image.source: "https://github.com/navidrome/navidrome"
      org.opencontainers.image.title: "navidrome"
      org.opencontainers.image.url: "https://github.com/navidrome/navidrome"
      org.opencontainers.image.version: "0.54.1"

    network_mode: "bridge"

    ports:
      - "4533:4533/tcp"

    restart: "unless-stopped"

    volumes:
      - "/mnt/extra2/Media:/music"
      - "navidrome_data:/data"

    working_dir: "/app"

version: "3.6"

volumes:
  navidrome_data:
    external: true
```

### Relevant log output

```shell
_   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                          Version: 0.54.3 (734eb30a)
time="2025-01-10T10:40:13Z" level=info msg="goose: no migrations to run. current version: 20241024125533\n"
time="2025-01-10T10:40:13Z" level=info msg="Starting signaler"
time="2025-01-10T10:40:13Z" level=error msg="Agent not available. Check configuration" name=lastfm
time="2025-01-10T10:40:13Z" level=error msg="Agent not available. Check configuration" name=spotify
time="2025-01-10T10:40:13Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music/Songs
time="2025-01-10T10:40:13Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg
time="2025-01-10T10:40:13Z" level=info msg="Setting Session Timeout" value=24h
time="2025-01-10T10:40:13Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=2
time="2025-01-10T10:40:13Z" level=info msg="Spotify integration is not enabled: missing ID/Secret"
time="2025-01-10T10:40:13Z" level=info msg="Creating Image cache" maxSize="100 MB" path=/data/cache/images
time="2025-01-10T10:40:13Z" level=info msg="Starting Insight Collector"
time="2025-01-10T10:40:13Z" level=info msg="Mounting Native API routes" path=/api
time="2025-01-10T10:40:13Z" level=error msg="Agent not available. Check configuration" name=lastfm
time="2025-01-10T10:40:13Z" level=error msg="Agent not available. Check configuration" name=spotify
time="2025-01-10T10:40:13Z" level=info msg="Mounting Subsonic API routes" path=/rest
time="2025-01-10T10:40:13Z" level=error msg="Agent not available. Check configuration" name=lastfm
time="2025-01-10T10:40:13Z" level=error msg="Agent not available. Check configuration" name=spotify
time="2025-01-10T10:40:13Z" level=info msg="Mounting Public Endpoints routes" path=/share
time="2025-01-10T10:40:13Z" level=info msg="Mounting LastFM Auth routes" path=/api/lastfm
time="2025-01-10T10:40:13Z" level=info msg="Mounting ListenBrainz Auth routes" path=/api/listenbrainz
time="2025-01-10T10:40:13Z" level=info msg="Mounting Background images routes" path=/backgrounds
time="2025-01-10T10:40:13Z" level=info msg="Mounting WebUI routes" path=/app
time="2025-01-10T10:40:13Z" level=info msg="Starting scheduler"
time="2025-01-10T10:40:13Z" level=info msg="Starting Jukebox service"
time="2025-01-10T10:40:13Z" level=info msg="2 audio devices found"
time="2025-01-10T10:40:13Z" level=info msg="Using audio device: alsa/iec958:CARD=PCH,DEV=0"
time="2025-01-10T10:40:13Z" level=error msg="Agent not available. Check configuration" name=lastfm
time="2025-01-10T10:40:13Z" level=error msg="Agent not available. Check configuration" name=spotify
time="2025-01-10T10:40:13Z" level=info msg="Scheduling periodic scan" schedule="@every 1m"
time="2025-01-10T10:40:13Z" level=warning msg="Periodic backup is DISABLED"
time="2025-01-10T10:40:13Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/data/cache/transcoding
time="2025-01-10T10:40:13Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime="161.771µs" maxSize=100MB
time="2025-01-10T10:40:13Z" level=info msg="Creating backgrounds cache" maxSize="100 MB" path=/data/cache/backgrounds
time="2025-01-10T10:40:13Z" level=info msg="Finished initializing cache" cache=backgrounds elapsedTime="362.677µs" maxSize=100MB
time="2025-01-10T10:40:13Z" level=info msg="----> Navidrome server is ready!" address="0.0.0.0:4533" startupTime=62.2ms tlsEnabled=false
time="2025-01-10T10:40:13Z" level=info msg="Finished initializing cache" cache=Image elapsedTime=170.3ms maxSize=100MB
time="2025-01-10T10:40:15Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music/Songs
time="2025-01-10T10:40:38Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000002
time="2025-01-10T10:40:48Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000006
time="2025-01-10T10:40:51Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000009
time="2025-01-10T10:40:59Z" level=info msg="JukeboxControl request received" action=clear requestId=1d2d608287e5/STDZSGDmGY-000011
time="2025-01-10T10:40:59Z" level=info msg="JukeboxControl request received" action=clear requestId=1d2d608287e5/STDZSGDmGY-000012
time="2025-01-10T10:40:59Z" level=info msg="JukeboxControl request received" action=add requestId=1d2d608287e5/STDZSGDmGY-000013
time="2025-01-10T10:40:59Z" level=info msg="JukeboxControl request received" action=skip requestId=1d2d608287e5/STDZSGDmGY-000014
time="2025-01-10T10:40:59Z" level=info msg="Found mpv" path=/usr/bin/mpv
time="2025-01-10T10:41:00Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000015
time="2025-01-10T10:41:00Z" level=info msg="JukeboxControl request received" action=start requestId=1d2d608287e5/STDZSGDmGY-000016
time="2025-01-10T10:41:00Z" level=info msg="Starting trackSwitcher goroutine" requestId=1d2d608287e5/STDZSGDmGY-000016
time="2025-01-10T10:41:01Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000017
time="2025-01-10T10:41:31Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000019
time="2025-01-10T10:42:01Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000021
time="2025-01-10T10:42:31Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000023
time="2025-01-10T10:43:01Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000025
time="2025-01-10T10:43:31Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000028
time="2025-01-10T10:43:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000031
time="2025-01-10T10:44:24Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000033
time="2025-01-10T10:44:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000035
time="2025-01-10T10:45:24Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000037
time="2025-01-10T10:45:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000039
time="2025-01-10T10:46:24Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000041
time="2025-01-10T10:46:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000043
time="2025-01-10T10:47:24Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000045
time="2025-01-10T10:47:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000047
time="2025-01-10T10:48:24Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000049
time="2025-01-10T10:48:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000051
time="2025-01-10T10:49:24Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000053
time="2025-01-10T10:49:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000055
time="2025-01-10T10:50:24Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000057
time="2025-01-10T10:50:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000059
time="2025-01-10T10:51:24Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000061
time="2025-01-10T10:51:54Z" level=info msg="JukeboxControl request received" action=get requestId=1d2d608287e5/STDZSGDmGY-000063
```

### Anything else?

This log is from the 11:13 song, and after sending it, client gave me a -1001 request timed out error.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
