### ISSUE TITLE
[Bug]: ND does not respect ND_LASTFM_ENABLED = false

### ISSUE THREAD

**Issue by de666** [navidrome/navidrome#3648]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.4

### Current Behavior

similar issue of https://github.com/navidrome/navidrome/issues/2634
Navidrome shows the following error at startup despite the environment ND_LASTFM_ENABLED is set to false
```
time="2025-01-15T09:21:38Z" level=error msg="Agent not available. Check configuration" name=lastfm
```

### Expected Behavior

no error shown

### Steps To Reproduce

1. start Navidrome container with ND_LASTFM_ENABLED set to false
2. check the logfile

### Environment

```markdown
- OS: N.A.
- Browser: N.A.
- Client: N.A.
```

### How Navidrome is installed?

Docker

### Configuration

```yaml
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 502:102
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: "30 3 * * *"
      ND_SPOTIFY_ID: ***
      ND_SPOTIFY_SECRET: ***
      ND_SMARTPLAYLISTREFRESHDELAY: "10m"
      ND_LASTFM_ENABLED: false
    volumes:
      - "/navidrome:/data"
      - "/music:/music:ro"
```

### Relevant log output

```shell
time="2025-01-15T09:21:38Z" level=error msg="Agent not available. Check configuration" name=lastfm
```
```


### Anything else?

Can't comment to ask reopening the other issue so I opened another one.
Sorry about that.
Anyway it seems it is a slightly different behaviour.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct
