### ISSUE TITLE
[Bug]: disk I/O error: no such device

### ISSUE THREAD

**Issue by Quassin** [navidrome/navidrome#3669]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.4

### Current Behavior

# Faulty output

I was trying to run Navidrome using the docker image and this `compose.yaml` file:
```yaml
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: debug  
      ND_BASEURL: ""
    user: "1000:1000"    
    volumes:
      - "/home/${USER}/storage/Navidrome/Data:/data"
      - "/home/${USER}/storage/Navidrome/Muzyka:/music"
```
When I run:
```bash
docker compose up
```
Running this for the first time I get the following error and create some files described in **Files Created**:
```
time="2025-01-25T20:50:05Z" level=fatal msg="Failed to apply new migrations" error="disk I/O error: no such device"
```
And when I run it second and any next time:
```
time="2025-01-25T20:50:10Z" level=error msg="Error disabling foreign_keys" error="disk I/O error: no such device"
time="2025-01-25T20:50:10Z" level=fatal msg="Database could not be opened!" error="disk I/O error: no such device"
```
Result is the same when I ran it with normal command:
```bash
docker run -d \
   --name navidrome \
   --restart=unless-stopped \
   --user $(id -u):$(id -g) \
   -v /home/${USER}/storage/Navidrome/Muzyka:/music \
   -v /home/${USER}/storage/Navidrome/Data:/data \
   -p 4533:4533 \
   -e ND_LOGLEVEL=info \
   deluan/navidrome:latest
```

# Files created
Running this for the first time also creates following files:

![Image](https://github.com/user-attachments/assets/98a20643-568c-4440-85f0-15cf364204a0)

# What I tried

1. Permissions are set correctly.
2. Directories exist.
3. I tried `user 1000:1000` with quotation marks and without. And running as root as well.

### Expected Behavior

Navidrome runs correctly :)

### Steps To Reproduce

1. Create a directory with this file `compose.yaml` in it:
```yaml
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: debug  
      ND_BASEURL: ""
    user: "1000:1000"    
    volumes:
      - "/home/${USER}/storage/Navidrome/Data:/data"
      - "/home/${USER}/storage/Navidrome/Muzyka:/music"
```
3. Make sure that `volumes` are mapped propertly to existing directories. 
4. Run:
```bash
docker compose up
```

### Environment

```markdown
- OS: Linux Mint 20.3
- Browser: N/A
- Client: N/A
```

### How Navidrome is installed?

Docker

### Configuration

```toml
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: debug  
      ND_BASEURL: ""
    user: "1000:1000"    
    volumes:
      - "/home/${USER}/storage/Navidrome/Data:/data"
      - "/home/${USER}/storage/Navidrome/Muzyka:/music"
```

### Relevant log output

```shell
Running this for the first time I get the following error and create some files described in **Files Created**:

time="2025-01-25T20:50:05Z" level=fatal msg="Failed to apply new migrations" error="disk I/O error: no such device"

And when I run it second and any next time:

time="2025-01-25T20:50:10Z" level=error msg="Error disabling foreign_keys" error="disk I/O error: no such device"
time="2025-01-25T20:50:10Z" level=fatal msg="Database could not be opened!" error="disk I/O error: no such device"
```

### Anything else?

It has worked before, I tried updating to the latest version (I don't remember the one I had previously) and now it isn't even starting.

1. Permissions are set correctly.
2. Directories exist.
3. I tried `user 1000:1000` with quotation marks and without. And running as root as well.

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct

**Comment by CrazyVito11** [comment]
I don't think I've ever seen a volume mapping with `${USER}` inside of it before, can you try replacing that with the desired username and see if the issue persists?

Can you also verify that `1000` is correct for your system in terms of user and group ID?
You should be able to check that with `id -u USERNAME` and `getent group GROUPNAME`.

**Comment by Quassin** [comment]
The path had my username, just didn't want to post it on the internet so i replaced it with `${USER}` before posting. Just checked my user and group ID and they're both `1000`.

**Comment by zardini123** [comment]
@Quassin Did you end up finding a solution to this?  I am running into the same issue.

**Comment by Tootam** [comment]
I was struggling with having rootless docker accessing files with little bit different errors (but still related to permissions?) and setting user to 0:0 solved my issues.
[attempt to write a readonly database](https://github.com/navidrome/navidrome/discussions/3309)
Previously I tried with $(id -u):$(id -g) or 1000:1000 and ended up with unstable container.
I haven't got time to check why it's working properly with that config however maybe it'll help you

```
services:
    navidrome:
      image: deluan/navidrome:latest
      user: 0:0
      ports:
        - 4533:4533
      environment:
      # ND_LOGLEVEL: debug
      restart: unless-stopped
      volumes:
        - "/(.../)navidrome/data:/data"
        - "/media/music:/music:ro"
```
