### ISSUE TITLE
[Bug]: Albums > Favourites shows nothing

### ISSUE THREAD

**Issue by wsdookadr** [navidrome/navidrome#3683]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [ ] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.4

### Current Behavior

I've favorited various songs and I can't find a place to see all of them. My goal was to build a playlist of songs I've favorited (with the heart icon showing at the bottom of the screen). If I click "Albums > Favourites" I get "No results found". I've looked at the database and couldn't find any table that would store them either.

### Expected Behavior

The "Albums >Favourites" should show the songs I've marked as favorite

### Steps To Reproduce

See above

### Environment

```markdown
- OS: Windows 11
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
- Client:
```

### How Navidrome is installed?

Docker

### Configuration

```yaml
services:
  navidrome:
    container_name: "navidrome"
    image: deluan/navidrome:0.54.4
    restart: always
    ports:
      - "4533:4533"
    volumes:
      - "./data:/data:rw"
      - "/home/nas/music:/music/music-nas:ro"
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
