### ISSUE TITLE
[Bug]: When having a fresh user, recently played may have too few results and display improperly.

### ISSUE THREAD

**Issue by Rycia** [navidrome/navidrome#3740]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

v0.54.4 

### Current Behavior

![Image](https://github.com/user-attachments/assets/bea57278-58b0-4e9f-af72-d80bf639743c)
On the home page, if "recently played" isn't populated out yet, the other cards simply infinitely load.

### Expected Behavior

Don't show these "loading" cards if they don't fetch anything.

### Steps To Reproduce

1. Open up Audioling.
2. View home on a fresh account with none or only a few/lack of recently played history.
3. The cards that don't show anything, because there's no history, just infinitely load because there is no history.. but it doesn't stop because there's no call to prevent it.

### Environment

```markdown
- OS: Windows 11 Pro
- Browser: None, using downloadable client.
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
# https://www.navidrome.org/docs/usage/configuration-options/

# cd /d S:
# cd "Navidrome"
# navidrome.exe

# Address = "localhost"

ScanSchedule = '@every 4h'
LogLevel = 'DEBUG'
TranscodingCacheSize = '150MiB'

EnableSharing = true

Spotify.ID = "redacted"
Spotify.Secret = "redacted"

LastFM.Enabled = true
LastFM.ApiKey = "redacted"
LastFM.Secret = "redacted"
LastFM.Language = "en"

MusicFolder = 'M:/Music'
DataFolder = 'S:/Navidrome/data'
```

### Relevant log output

```shell
None, UI issue with the client; not server sided
```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
