### ISSUE TITLE
[Bug]: Follow location header on status 401 to be redirect on SSO instead of default login page

### ISSUE THREAD

**Issue by edaubert** [navidrome/navidrome#3767]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.5-SNAPSHOT (287079a)

### Current Behavior

I have set navidrome behind traefik and using authelia as SSO provider.
After some time, my credentials has been deprecated and I need to reauthenticate myself.

By default navidrome sent me to its own login page however I want to use my SSO.
Traefik and Authelia is configured to add a redirect `location` header when a status code 401 is thrown.

But navidrome on the client side (inside the browser) doesn't take the header into account and still redirect me to its own login page.

### Expected Behavior

If a `Location` header is given, navidrome should follow him and if not redirects to its own login page

### Steps To Reproduce

- I logged in using my SSO 
- Navidrome display the default page
- I restarted my SSO to clear all existing credentials
- I try to play something from navidrome and its default page (e.g. an album, a title)
- Navidrome sent me to its login page

I would like the last step to be replace by the redirect location given on header and I would be redirected on my SSO login page.

### Environment

```markdown
- OS:Archlinux
- Browser: Firefox 135.0.1
```

### How Navidrome is installed?

Docker

### Configuration

```toml
LogLevel = 'DEBUG'
EnableInsightsCollector = 'false'

ScanSchedule = '@every 1h'
TranscodingCacheSize = '5GiB'

MusicFolder = '***'
DataFolder = '***'
CacheFolder = '***'

EnableDownloads = 'false'
EnableFavourites = 'false'
EnableSharing = 'true'
EnableStarRating = 'false'
EnableTranscodingConfig = 'true'

#DefaultLanguage = 'uk'
EnableExternalervices = 'true'
EnableGravatar = 'false'
EnableMediaFileCoverArt = 'false'

Address = '127.0.0.1'

Jukebox.Enabled = true

Spotify.ID = '***'
Spotify.Secret = '***'
ListenBrainz.Enabled = 'false'
LastFM.Enabled = 'false'

ReverseProxyWhitelist = '0.0.0.0/0'
EnableUserEditing = 'false'
```

### Relevant log output

```shell

```

### Anything else?

It is my traefik and authelia services that handle the credentials and respond with a 401 and the `Location` header with the url to reconnect.
Nothing goes through navidrome directly : everything is done through traefik.

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
