### ISSUE TITLE
[Bug]: getAlbumList2 omitting album sortName

### ISSUE THREAD

**Issue by mattneub** [navidrome/navidrome#3774]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.54.4-SNAPSHOT (pr-2709/b4fd8d52)

### Current Behavior

As promised (elsewhere), I'm writing my own Navidrome client / player. It's working great (Navidrome is super-fast). However, now that I'm talking directly to the server, I've found a little problem: when calling `getAlbumList2` (or `getAlbumList`) using `alphabeticalByName`, in the `album` array that is returned, every album has an empty `sortName` (i.e. `""`).

This is in spite of the fact that every album _has_ a `sortName`, and that the `album` list that is returned _is in fact sorted by that `sortName`._ I know this because when you call `getAlbum`, the returned `album`_does_ provide its `sortName` correctly (and so do all the songs). So clearly the database does have this information, but it is just failing to return it on the `getAlbumList[2]` call.

### Expected Behavior

When we do a `getAlbumList2`, the `sortName` value should be the actual `sortName` value, and not an empty string.

### Steps To Reproduce

Do a `getAlbumList2.view` request with `type` equal to `alphabeticalByName` and look at the `album` array in the response. All the `sortName` values are empty strings.

### Environment

```markdown
- OS: Navidrome is running on MacOS High Sierra; client is running on iOS 18.4
- Browser: None
- Client: I'm calling it "Dromio" :)
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/Volumes/TomThumb/music'
ScanSchedule = '@every 12h'
EnableExternalServices = false
DataFolder = '/Volumes/Humlet/Users/matt/navidrome'
Jukebox.Enabled = true
MPVPath = '/Applications/mpv.app/Contents/MacOS/mpv'
MPVCmdTemplate = 'mpv --audio-device=%d --no-audio-display --pause %f --input-ipc-server=%s --gapless-audio=yes'
LogLevel = 'DEBUG'
RecentlyAddedByModTime = false
LastFM.Enabled = true
LastFM.ApiKey = '<redacted>'
LastFM.Secret = '<redacted>'
PID.Album = 'album_legacy'
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
