### ISSUE TITLE
[Bug]: No longer showing original and actual release date in album list

### ISSUE THREAD

**Issue by phw** [navidrome/navidrome#3800]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.0

### Current Behavior

Navidrome before 0.55.0 used to show both the original release date and the actual release date for the album version in the album list on an artist page.

0.55.0 only shows the actual date. The original date is still shown on the album page:

![Image](https://github.com/user-attachments/assets/698f4c55-a84e-401d-9658-47a17f480bf0)

Is it possible to get the old display back?

### Expected Behavior

Show both dates in the list as below (screenshot from earlier navidrome version):

![Image](https://github.com/user-attachments/assets/89b3cf90-3484-46e3-a0ee-0543700775dd)

### Environment

```markdown

```

### How Navidrome is installed?

Docker

### Configuration

```toml

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Thanks for reporting. There were some changes in how dates are imported, and the old "tagged as Picard" hack for parsing dates was removed. 

Anyway, can you attach one of the files of this album, do I can take a look? Thanks

**Comment by phw** [comment]
After some further tinkering I found out that Navidrome now displays `TDRC` (or `date` for Vorbis) and `TDRL` (or `releasedate` for Vorbis) in the album list, if they are different, and it seems to consider `TDRC` true to the original name as the date the songs got recorded.

The dates when songs got recorded is often more difficult to source. But if I set this I now get:

![Image](https://github.com/user-attachments/assets/2dce7008-d84f-49b2-a54f-8deb2315139c)

So the change in behavior is that previously it would show the original date and whatever it considered the release date, now it explicitly shows the date of recording and release date (and ignores the original date).

I actually think if one really fully tags the collection like this the view will become rather busy, as the date of recording quite often is a year ahead of the release date (it takes usually takes a couple of months from studio recording sessions to final album release). You can also see this for both of the original releases in the screenshot, which after tagging change now also show two dates.

IMHO it was more useful before to see the actual original release date. That would mean to show the release date primarily, and the original release date if it differs. The date of the recording better fits into a detail view.

Could we at least have this an option?

The trouble of course is that `TDRC` / `date` has been traditionally just used as **the date**, whatever this means. And it usually just got set to whenever the audio got available, so usually the release date. And it is often the only date field set on downloaded music and written by ripping software etc. So when Navidrome decides for the release date it should still be `TDRL` with fallback to `TDRC`. But this is what already seems to happen.

**Comment by phw** [comment]
Sorry for the many comments, I just keep digging deeper. I think it is clear what the goal is (but correct me if I'm wrong). Navidrome tries to support three separate field names:

- `originaldate`: The date the album or maybe recording was originally released
- `recordingdate`: The date the audio got recorded
- `releasedate`: The date the specific release got actually released (for original releases same as `originaldate`, for re-releases or compilations later)

And there is this mapping:

```yaml
  originaldate:
    aliases: [ tdor, originaldate, ----:com.apple.itunes:originaldate, wm/originalreleasetime, tory, originalyear, ----:com.apple.itunes:originalyear, wm/originalreleaseyear ]
    type: date
  recordingdate:
    aliases: [ tdrc, date, icrd, ©day, wm/year, year ]
    type: date
  releasedate:
    aliases: [ tdrl, releasedate ]
    type: date
```

I think `originaldate` is fine. Wasn't used much in the past, works to be used like this. The trouble starts with `recordingdate`.

`TDRC` was early on misused for the releasedate. And this is very universal. If I look at the original metadata of downloads from Amazon Music, Bandcamp, Google Play, 7 digital etc., but also at CD rips which sourced data from CDDB, TDRC is always the release date. Similar is true for `DATE` in Vorbis comments, even though this was also [defined as "Date the track was recorded"](https://xiph.org/vorbis/doc/v-comment.html)

Ok, but if we want to break with the past, move on to a saner definition (and Navidrome seems to try to do this) and go by the intention of the ID3 spec and Vorbis comment recommendation this distinction of tags is fine. The mapping for ID3 and Vorbis is also good. But then the rest of the values does not fit:

- `©day` was originally defined by apple as "Release Date: YYYY-MM-DD format string (may be incomplete, i.e. only year)". No field for "recording date" seems to be officially defined. Not sure if modern itunes / apple music uses something for this.
- `wm/year` is [defined as](https://learn.microsoft.com/en-us/previous-versions/ms867702(v=msdn.10)?redirectedfrom=MSDN#wmyear) "The WM/Year attribute contains the year the content was published.". No field for "recording date" seems to be officially defined.
- For [APE tags](https://wiki.hydrogenaud.io/index.php?title=APE_key) `Year` was actually defined as `Release Date`, so this clashes with the Vorbis definition. There would be `Record Date` as a separate tag. 

Hence I think if the intention is really to use the fields as above it is not enough to just change the use of `TDRC` and bring it back to its original meaning, but to also maintain the meaning of other tags. A better mapping would hence be:

```yaml
  originaldate:
    aliases: [ tdor, originaldate, ----:com.apple.itunes:originaldate, wm/originalreleasetime, tory, originalyear, ----:com.apple.itunes:originalyear, wm/originalreleaseyear ]
    type: date
  recordingdate:
    aliases: [ tdrc, date, icrd, "record date" ]
    type: date
  releasedate:
    aliases: [ tdrl, releasedate, ©day, wm/year, year ]
    type: date
```

For display of `releasedate` Navidrome could still fall back to `recordingdate`.

The above mapping would be true to the definitions and offer a clear distinction between all three tags. It is a break with existing metadata practice for ID3 and Vorbis, but this was already done and I generally think it is a good move.

Let's update this mapping in Navidrome and I will make the same changes in Picard as well. We'll need to make it an option, but maybe we can even make it the default with Picard 3.
