### ISSUE TITLE
[Bug]: Error creating data path

### ISSUE THREAD

**Issue by pmezhuev** [navidrome/navidrome#3831]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.1

### Current Behavior

Full scan is not performed after upgrading to version 0.55.*, the application is malfunctioning. Rolling back to version 0.54.5 restores normal operation.

### Expected Behavior

Upgrade completes without errors.

### Steps To Reproduce

1. Have a working application version lower than 0.55.  
2. Upgrade to version 0.55.

### Environment

```markdown
- OS: FreeBSD 14.2
```

### How Navidrome is installed?

Built from sources

### Configuration

```toml
AlbumPlayCountMode = "normalized"
AutoImportPlaylists = false
Backup.Count = 15
Backup.Path = "/var/db/navidrome/backup"
Backup.Schedule = "@daily"
BaseUrl = "https://music.example.com"
DefaultLanguage = "ru"
DevShowArtistPage = true
EnableFavourites = false
EnableGravatar = true
EnableInsightsCollector = false
EnableStarRating = false
EnableSharing = true
ImageCacheSize = "3GB"
ListenBrainz.Enabled = false
PasswordEncryptionKey = "secret"
MusicFolder = "/var/samba/Музыка"
Scanner.Schedule = "@every 1h"
TranscodingCacheSize = "10GB"
```

### Relevant log output

```shell
level=warning msg="Full scan required after migration"
FATAL: Error creating data path: mkdir .: permission denied
level=error msg="Scan failed" error="failed to read status from scanner: /usr/local/bin/navidrome scan --nobanner --subprocess --configfile /usr/local/etc/navidrome.toml --full exited with non-zero status code: exit status 1"
```

### Anything else?

Start command: `/usr/local/bin/navidrome --configfile /usr/local/etc/navidrome.toml --datafolder /var/db/navidrome`. The owner of the `datafolder` and all nested files is the user under which the process is running. The music directory is read-only.

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
