### ISSUE TITLE
[Bug]: Internal Server Error: can't connect to mpv's socket

### ISSUE THREAD

**Issue by MRodneyMcKay** [navidrome/navidrome#3852]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.1 (beb768cd)

### Current Behavior

Jukebox is broken. In the logs, i see this:
```
2025-03-18 18:35:36.119173+01:00time="2025-03-18T17:35:36Z" level=error msg="Error opening new connection" error="can't connect to mpv's socket: dial unix /tmp/mpv-ctrl-betgm4dqYO26jmsxlMkOii.socket: connect: connection refused"
2025-03-18 18:35:36.119908+01:00time="2025-03-18T17:35:36Z" level=warning msg="API: Failed response" endpoint=/rest/jukeboxControl.view error=0 message="Internal Server Error: can't connect to mpv's socket: dial unix /tmp/mpv-ctrl-betgm4dqYO26jmsxlMkOii.socket: connect: connection refused" requestId=nas/pHmhCbHYgz-000006
```

### Expected Behavior

Expected to have jukebox working

### Steps To Reproduce

1. Launch the server
2. Connect to the jukebox from DSub

### Environment

```markdown
- OS: TrueNAS's docker
- Browser: -
- Client: -
```

### How Navidrome is installed?

Docker

### Configuration

```toml
Jukebox.Enabled = true
Jukebox.Devices = [
         [ "SMSL-SU8",     "alsa/front:CARD=DAC,DEV=0" ]
]
Jukebox.Default = "SMSL-SU8"
MPVPath = ""
MPVCmdTemplate = 'mpv  --no-audio-display --volume=100  --replaygain=album --replaygain-preamp=-10 --pause %f --input-ipc-server=%s'
```

### Relevant log output

```shell
2025-03-18 18:35:36.119173+01:00time="2025-03-18T17:35:36Z" level=error msg="Error opening new connection" error="can't connect to mpv's socket: dial unix /tmp/mpv-ctrl-betgm4dqYO26jmsxlMkOii.socket: connect: connection refused"
2025-03-18 18:35:36.119908+01:00time="2025-03-18T17:35:36Z" level=warning msg="API: Failed response" endpoint=/rest/jukeboxControl.view error=0 message="Internal Server Error: can't connect to mpv's socket: dial unix /tmp/mpv-ctrl-betgm4dqYO26jmsxlMkOii.socket: connect: connection refused" requestId=nas/pHmhCbHYgz-000006
```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
