### ISSUE TITLE
[Bug]: Duplicated albums after 0.54.5 upgrade to 0.55.1

### ISSUE THREAD

**Issue by kopf** [navidrome/navidrome#3854]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.1

### Current Behavior

After upgrading to 0.55.1, all albums are duplicated - each album has one displayed with artist name, and another without. When clicked, the one without an artist also appears empty. 

The upgrade went without any problems. I let the DB upgrade and full library scan complete successfully. I didn't see any errors in the logs. 

### Expected Behavior

I expected to see one album entry per album instead of two.

### Steps To Reproduce

Not sure if it's reproducible, but here are the steps I took:

1. Ran 0.54.5 without problems. 
2. Stopped navidrome. 
3. Replaced the navidrome binary with 0.55.1 (NOT 0.55.0)
4. Started navidrome.
5. Waited for the scan to complete. 
6. Visited my navidrome site and saw all albums duplicated.

### Environment

```markdown
- OS: OpenWrt 24.10.0 r28427-6df0e3d02a running on Linksys WRT3200ACM (ARMv7)
- Browser: Chrome
- Client: Chrome
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/music'
DataFolder = '/overlay/navidrome'
CacheFolder = '/overlay/cache/navidrome'

Scanner.Schedule = '0 2 * * *'
LogLevel = 'WARN'
SessionTimeout = '168h'
PlaylistsPath = 'Playlists'
LastFM.ApiKey = 'REDACTED'
LastFM.Secret = 'REDACTED'
# spotify required to scrape artist images:
Spotify.ID = 'REDACTED'
Spotify.Secret = 'REDACTED'
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
