### ISSUE TITLE
[Bug]: Album cover not showing

### ISSUE THREAD

**Issue by guim31** [navidrome/navidrome#3855]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.1-SNAPSHOT (b0464730)

### Current Behavior

Following my messages on reddit : 

I use Navidrome on my Unraid server. 
The album covers are not showing. The log says : 
error=stat /music/music/BJÖRK/Vespertine/03-It's_Not_Up_To_You.flac: no such file or directory

It seems that there is a problem with this `/music/music` file path

### Expected Behavior

Album cover showing in the web UI

### Environment

```markdown
- OS:Unraid
- Browser:Firefox, Chromium
- Client: / webUI
```

### How Navidrome is installed?

Docker

### Configuration

```toml
My Unraid template for docker : 

docker run
  -d
  --name='navidrome'
  --net='proxynet'
  --cpuset-cpus='2,3,4,5'
  --pids-limit 2048
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="NASDOURY"
  -e HOST_CONTAINERNAME="navidrome"
  -e 'ND_CONFIGFILE'='/data/navidrome.toml'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://192.168.100.150:4533'
  -l net.unraid.docker.icon='https://pbs.twimg.com/profile_images/1310671419240583170/5lhEh5KF_400x400.jpg'
  -p '4533:4533/tcp'
  -v '/mnt/user/musique/':'/music':'ro'
  -v '/mnt/user/appdata/navidrome/':'/data':'rw' 'deluan/navidrome:develop'


And my TOML file : 

# Chemin vers le dossier de données
DataFolder = "/data"

# URL de l'image de fond de la page de connexion
UILoginBackgroundUrl = 'https://wallpapers.com/images/file/oled-4k-h'

# Désactive l'importation automatique des playlists
AutoImportPlaylists = false

# Priorité de l'art de la couverture
CoverArtPriority = 'embedded'

# Active ReplayGain
EnableReplayGain = true

# Active la configuration de transcodage
EnableTranscodingConfig = true

# Theme par defaut
DefaultTheme = 'Dark'

# PID pour les albums
PID_Album = 'musicbrainz_albumid|albumartistid,album,albumversion,releasedate'

# PID pour les pistes
PID_Track = 'musicbrainz_trackid|albumid,discnumber,tracknumber,title'

ImageCacheSize = '0'
LogLevel = 'info'
[DevLogLevels]
'core[/](http://192.168.100.150:8765/fs/)artwork' = 'trace'
'utils/cache/' = 'trace'
'core/ffmpeg' = 'trace'
```

### Relevant log output

```shell
error=stat /music/music/BJÖRK/Vespertine/03-It's_Not_Up_To_You.flac: no such file or directory
```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
