### ISSUE TITLE
[Bug]: Only the first artist is displayed via Subsonic

### ISSUE THREAD

**Issue by TanqBQZ** [navidrome/navidrome#3877]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.1

### Current Behavior

If you have set a delimiter for the ARTIST tag, even though a song has ARTIST and ARTISTS tags, the display artist sent via the Subsonic API will be the the first artist before the delimiter.

Example (I added "&" as a delimiter) : 
The tags are : 

![Image](https://github.com/user-attachments/assets/e54f7619-59b8-4e3f-8202-e7a4f55298f9)

In the Navidrome UI, it shows :

![Image](https://github.com/user-attachments/assets/eb7bf1bc-9359-44a6-a1a8-a4ea7d53370f)

But in Symfonium, only the first artist is shown in the display field. The second artist is present when tapping on the artist field, so that it shows all artists

![Image](https://github.com/user-attachments/assets/5e968923-a7ae-440a-9414-7a4c2bfc5d21)

### Expected Behavior

The display artist sent to clients should always be the full ARTIST tag.

### Environment

```markdown
- OS:Docker
- Browser:
- Client: Symfonium
```

### How Navidrome is installed?

Docker

### Configuration

```toml
MusicFolder = "/music"
DataFolder = "/data"
LogLevel = "debug"
AutoImportPlaylists = true
ArtistArtPriority = "artist.*, external"
CoverArtPriority = "embedded"
CoverJpegQuality = 90
EnableCoverAnimation = false
EnableMediaFileCoverArt = true
EnableReplayGain = false
ImageCacheSize = "10GB"
Subsonic.ArtistParticipations = true
Subsonic.DefaultReportRealPath = true
Tags.Artist.Split = [" / ", " feat. ", " feat ", " ft. ", " ft ", "; ", " & ", ", "]
Tags.Albumartist.Split = [" / ", " feat. ", " feat ", " ft. ", " ft ", "; ", " & ", ", "]
Tags.Composer.Aliases = ['tcom', 'composer', '©wrt', 'wm/composer', 'imus', 'writer', 'txxx:writer', 'iwri', 'author']
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
