### ISSUE TITLE
[Bug]: Extractor 'ffmpeg' is not implemented, using 'taglib'

### ISSUE THREAD

**Issue by gesu92** [navidrome/navidrome#3906]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

55.1

### Current Behavior

I had less tags on my library songs, after update the last version just 3 days ago, after doing some quick and full scans on the library same problem.
When I doing full scan library from the terminal, I see the message "_Extractor 'ffmpeg' is not implemented, using 'taglib'_", I had only oga files, taglib don't handle very well tags on that files, but now, why suddenly ffmpeg it's no implemented??
I use archlinux, the package from extra repo and the build from aur had the same problem, I don't know if this is a build problem or a problem of this version of navidrome.

### Expected Behavior

Just all ok with tags, all working well like the past week when I had no problems with this

### Steps To Reproduce

1. Install last version of navidrome
2. Configure it
3. set Scanner.Extractor = "ffmpeg"
4. do navidrome -c "my conf file path" scan -f
5. view the first line message after Navidrome logo and version.

### Environment

```markdown
- OS: Arch Linux x86_64
- Browser:Firefox 136.0.4 (64-bit)
- Client:Navidrome Music Server 0.55.1
```

### How Navidrome is installed?

Package

### Configuration

```toml
#
# https://www.navidrome.org/docs/usage/configuration-options/
#

# Folder to store application data (DB, cache…)
DataFolder = "/var/lib/navidrome"
MusicFolder = "/mnt/music"
CacheFolder = "/var/lib/navidrome/cache"
Port = "4747"
Scanner.Extractor = "ffmpeg"
FFmpegPath = "/usr/bin/ffmpeg"
SubsonicArtistParticipations = "true"
EnableSharing = "true"
RecentlyAddedByModTime = "true"
TranscodingCacheSize = "500MB"
ScanSchedule = 0
```

### Relevant log output

```shell
_   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
Version: 0.55.1 (beb768cd9cd00f01581fe190a345ccf8617950db)

WARN[0000] Extractor 'ffmpeg' is not implemented, using 'taglib' 
INFO[0000] Scanner: Starting scan                        fullScan=true numLibraries=1
```

### Anything else?

![Image](https://github.com/user-attachments/assets/82af8bd0-c2b9-4c15-9c62-d0e07babbc2a)

No artist column...

![Image](https://github.com/user-attachments/assets/abb75fed-27c9-4f04-8e67-51979ca3b560)

No artist in whole database, taglib don't handle my files, but ffmpeg always doing, and now is not implemented?

PD= Sorry my bad english I hope you understand me

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
