### ISSUE TITLE
[Bug]: VERSION vorbis comments are use for identifying albums

### ISSUE THREAD

**Issue by undu** [navidrome/navidrome#3917]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.1

### Current Behavior

I've been using the VERSION tag for my collection of flac files for quite a few years, according to the documentation I've found online about it:

https://xiph.org/vorbis/doc/v-comment.html
> VERSION
> The version field may be used to differentiate multiple versions of the same track title in a single collection. (e.g. remix info)

https://age.hobba.nl/audio/mirroredpages/ogg-tagging.html
> VERSION
>   Make sure you don't put DATE or LOCATION information in this tag. "live", "acoustic", "Radio Edit" "12 inch remix" might be typical values of this tag

On the hydrogenaudio is classified under "title grouping": https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping

However, this tag, under version 0.55.1, navidrome uses it to split the songs that are tag with it into a different album.

![Image](https://github.com/user-attachments/assets/7f80b38b-066a-4856-8fbc-56e2907f7f42)

### Expected Behavior

I would expect that the VERSION vorbis comment is used to distinguish between several songs in the same album, while keeping them in the same album.

Note that this means VERSION is different from ALBUMVERSION, which is the one that is used to tell apart between different versions of an album.

### Environment

```markdown
The issue is visible on the web interface, as well as opensubsonic client, like Symfonium
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
I believe this configuration-independent
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct

**Comment by DameGAD** [comment]
I had a similar issue (I asked about it [here](https://github.com/navidrome/navidrome/discussions/3901)).

And from what I understand, in the meantime it can be fixed with the following lines in a config file:
Tags.Albumversion.Aliases = ['albumversion', 'musicbrainz_albumcomment', 'musicbrainz album comment']
Tags.Version.Aliases = ['version']

**Comment by deluan** [comment]
I understand you're using the VERSION tag for track subtitles (like "live", "acoustic", "Radio Edit", etc.) following the Vorbis comment standard. Currently, Navidrome maps the VERSION tag as an album-level tag through this mapping in `mappings.yaml`:

```yaml
albumversion:
  aliases: [albumversion, musicbrainz_albumcomment, musicbrainz album comment, version]
  album: true
```

For your use case, you should use the SUBTITLE tag instead, which is specifically designed for this purpose. However, if you want to keep using VERSION tags in your existing files, you can override this behavior using Navidrome's custom tag configuration. Add the following to your `navidrome.toml` configuration file:

```toml
# Map VERSION tag to be treated as a subtitle, keeping all existing subtitle aliases
Tags.Subtitle.Aliases = ["tit3", "subtitle", "----:com.apple.itunes:subtitle", "wm/subtitle", "version"]
Tags.Subtitle.Album = false

# Keep album version related tags separate
Tags.AlbumVersion.Aliases = ["albumversion", "musicbrainz_albumcomment", "musicbrainz album comment"]
Tags.AlbumVersion.Album = true
```

This configuration will:
1. Treat VERSION tags as track subtitles, just like the SUBTITLE tag
2. Keep proper album versioning tags separate for album disambiguation
3. Match your intended usage of the VERSION tag for distinguishing different versions of tracks within the same album

After making these changes:
1. Make sure your config file is properly loaded (if using Docker, map it to `/data/navidrome.toml` and set `ND_CONFIGFILE=/data/navidrome.toml`)
2. Perform a full rescan of your library (quick scan won't process the updated tag configurations)

For future tagging, I would recommend using the SUBTITLE (TIT3) tag instead of VERSION for this purpose, as it's more widely supported and won't cause confusion with album versioning. However, this configuration will allow your existing VERSION tags to work as intended.

Let me know if you need any clarification or run into issues with this configuration.

**Comment by deluan** [comment]
I understand you're using the VERSION tag for track subtitles (like "live", "acoustic", "Radio Edit", etc.) following the Vorbis comment standard. Currently, Navidrome maps the VERSION tag as an album-level tag through this mapping in `mappings.yaml`:

```yaml
albumversion:
  aliases: [albumversion, musicbrainz_albumcomment, musicbrainz album comment, version]
  album: true
```

For your use case, you should use the SUBTITLE tag instead, which is specifically designed for this purpose. However, if you want to keep using VERSION tags in your existing files, you can override this behavior [using Navidrome's custom tag configuration](https://www.navidrome.org/docs/usage/customtags/). Add the following to your `navidrome.toml` configuration file:

```toml
# Map VERSION tag to be treated as a subtitle, keeping all existing subtitle aliases
Tags.Subtitle.Aliases = ["tit3", "subtitle", "----:com.apple.itunes:subtitle", "wm/subtitle", "version"]
Tags.Subtitle.Album = false

# Keep album version related tags separate
Tags.AlbumVersion.Aliases = ["albumversion", "musicbrainz_albumcomment", "musicbrainz album comment"]
Tags.AlbumVersion.Album = true
```

This configuration will:
1. Treat VERSION tags as track subtitles, just like the SUBTITLE tag
2. Keep proper album versioning tags separate for album disambiguation
3. Match your intended usage of the VERSION tag for distinguishing different versions of tracks within the same album

After making these changes:
1. Make sure your config file is properly loaded (if using Docker, map it to `/data/navidrome.toml` and set `ND_CONFIGFILE=/data/navidrome.toml`)
2. Perform a full rescan of your library (quick scan won't process the updated tag configurations)

For future tagging, I would recommend using the SUBTITLE (TIT3) tag instead of VERSION for this purpose, as it's more widely supported and won't cause confusion with album versioning. However, this configuration will allow your existing VERSION tags to work as intended.

Let me know if you need any clarification or run into issues with this configuration.
