### ISSUE TITLE
[Bug]: Metadata stuck somewhere in the db

### ISSUE THREAD

**Issue by sickmitch** [navidrome/navidrome#3921]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.1 (beb768cd)

### Current Behavior

Artist and Album get indexed as Unknown Artist and Unknown Album

### Expected Behavior

Pick up values from tags

### Steps To Reproduce

Don't really know if is reproduceable but I tried many ways to modify the tag and reading it return right values but navidrome show as unknown.

### Environment

```markdown
- OS: Ubuntu 24.04
- Browser: Firefox 
- Client: Symfonium
```

### How Navidrome is installed?

Docker

### Configuration

```toml
{navidrome.toml}
LogLevel = 'DEBUG'
ScanSchedule = '@every 1h'
EnableTranscodingConfig = true
TranscodingCacheSize = '1024MiB'

[lastfm]
enabled = true
apiKey = "XXXX"
secret = "XXXX"

[spotify]
enabled = true
ID = "XXXX"
Secret = "XXXX"


{compose.yaml}
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 0:0 
    ports:
      - 4533:4533
    volumes:
      - /home/mike/docker/navidrome/data:/data
      - /home/mike/data/media/music/:/music:ro
    environment:
      - ND_CONFIGFILE=/data/navidrome.toml
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.routers.navidrome.entrypoints=web, websecure
      - traefik.http.routers.navidrome.rule=Host(`navidrome.XXXXX.cc`)
      - traefik.http.routers.navidrome.tls=true
      - traefik.http.routers.navidrome.tls.certresolver=production
      - traefik.http.services.navidrome.loadbalancer.server.port=4533
        # - "traefik.http.routers.navidrome.middlewares=authMiddle"
        # - "traefik.http.middlewares.authMiddle.basicauth.users=XXXXX"  
    networks:
      - proxy
networks:
  proxy:
    external: true
```

### Relevant log output

```shell
No errors or anything on logs when reproducing the track, all looks normal. Can't get into the db to see tables.
```

### Anything else?

Tried to remove the file from the media folder, removed from missing files UI tab and rescanned it back in but still unknown. I'd love to produce more log but can't get into the db. 

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
