### ISSUE TITLE
[Bug]: incorrect displayArtist for albums

### ISSUE THREAD

**Issue by mattneub** [navidrome/navidrome#3944]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.2

### Current Behavior

If all the artists in an album's tracks are the same, and if the artist contains a semicolon, the displayArtist for that album is only what precedes the semicolon. For example, if all the album's tracks say that the artist is "hey; ho", the album's displayArtist is "hey".

### Expected Behavior

What I expect is no surprises. If I say the artist for every track is "hey; ho", the artist should be _displayed_ as "hey; ho". 

Please note that my albums have no album artist. I expect navidrome to get the artist from the individual tracks. If these are different, I expect navidrome to give the album a displayArtist "Various Artists", which it does. But if they are all the same, navidrome should supply the album's displayArtist exactly as I have set it for all the tracks.

### Steps To Reproduce

You should be able to test this with an album of one track whose artist is "hey; ho".

### Environment

```markdown
- OS: Mac OS 10.13.6
- Browser: none
- Client: Dromio
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/Volumes/TomThumb/music'
ScanSchedule = '@every 12h'
EnableExternalServices = false
DataFolder = '/Volumes/Humlet/Users/matt/navidrome'
LogLevel = 'DEBUG'
RecentlyAddedByModTime = false
LastFM.Enabled = true
LastFM.ApiKey = '<redacted>'
LastFM.Secret = '<redacted>'
PID.Album = 'album_legacy'
Subsonic.ArtistParticipations = true
Jukebox.Devices = [
    [ "duet",     "coreaudio/AppleFWAudioEngineGUID:1085260926344054" ],
    [ "internal", "coreaudio/AppleHDAEngineOutput:1B,0,1,1:0" ]
]
Jukebox.Default = "duet"
Jukebox.Enabled = true
MPVPath = '/Applications/mpv.app/Contents/MacOS/mpv'
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct

**Comment by deluan** [comment]
Hi @mattneub,

Thanks for reporting this issue. What you're experiencing is actually the expected behavior based on Navidrome's default configuration.

Navidrome includes "; " (semicolon + space) in its default set of artist name splitters:

```yaml
artists:
  split: [" / ", " feat. ", " feat ", " ft. ", " ft ", "; "]
```

Navidrome uses the AlbumArtist tag as displayAlbumArtist, or the first album artist when there are multiple artists. In your case, because of the default splitter configuration, it is considering the album/tracks to have two artists: `hey` and `ho`. Since there are multiple artists detected (due to the semicolon splitting), it's using only the first one (`hey`) as the album artist.

You can resolve this in two ways:

1. **Override the default splitters** in your `navidrome.toml` configuration:
   ```toml
   [Tags.Artist]
   Split = [" / ", " feat. ", " feat ", " ft. ", " ft "]  # Remove "; " from the list
   ```
   After making this change, you'll need to do a full rescan of your library.

2. **Add AlbumArtist tags** to your music files (recommended long-term solution)
   Setting explicit AlbumArtist tags in your files would ensure Navidrome displays the artist exactly as intended, regardless of splitters.

3. **Use a different character** instead of semicolons for organizing artist names if these are meant to be distinct parts of the name.

This behavior is by design to handle cases where artists are separated by common delimiters, but I understand it may not be what you want in your particular use case.

**Comment by deluan** [comment]
Hi @mattneub,

Thanks for reporting this issue. What you're experiencing is actually the expected behavior based on Navidrome's default configuration.

Navidrome includes "; " (semicolon + space) in its default set of artist name splitters:

```yaml
artists:
  split: [" / ", " feat. ", " feat ", " ft. ", " ft ", "; "]
```

Navidrome uses the AlbumArtist tag as displayAlbumArtist, or the first album artist when there are multiple artists. In your case, because of the default splitter configuration, it is considering the album/tracks to have two artists: `hey` and `ho`. Since there are multiple artists detected (due to the semicolon splitting), it's using only the first one (`hey`) as the album artist.

You can resolve this in a couple of ways:

1. **Override the default splitters** in your `navidrome.toml` configuration:
   ```toml
   [Tags.Artist]
   Split = [" / ", " feat. ", " feat ", " ft. ", " ft "]  # Remove "; " from the list
   ```
   After making this change, you'll need to do a full rescan of your library.

   For more details on customizing tag configurations, see the [Custom Tags documentation](https://www.navidrome.org/docs/usage/customtags/) and [Configuration Options](https://www.navidrome.org/docs/usage/configuration-options/#tags).

2. **Add AlbumArtist tags** to your music files (recommended long-term solution)
   Setting explicit AlbumArtist tags in your files would ensure Navidrome displays the artist exactly as intended, regardless of splitters.

   This is covered in the [Tagging Guidelines](https://www.navidrome.org/docs/usage/tagging-guidelines/) and [FAQ](https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist).

3. **Use a different character** instead of semicolons for organizing artist names if these are meant to be distinct parts of the name.

This behavior is by design to handle cases where artists are separated by common delimiters, but I understand it may not be what you want in your particular use case.
