### ISSUE TITLE
[Bug]: compilation album explosion in 0.55.2

### ISSUE THREAD

**Issue by mattneub** [navidrome/navidrome#3949]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.2-SNAPSHOT (pr-3946/bb8dd575)

### Current Behavior

It is important to understand that in 0.55.1 everything was fine.

In order to test the snapshot build listed above, I stopped Navidrome, threw away the database, and started Navidrome again and let it create the database completely fresh. When I did this, all my compilation albums (albums for which compilation=1) exploded into multiple albums.

### Expected Behavior

The new build should not cause album explosion. This seems like a form of regression.

### Steps To Reproduce

You need to do what I did. Stop navidrome. Install the snapshot build. Throw away the database. Start navidrome so that it builds the database from scratch. Now use some interface (the web interface will do) to check your albums.

Note that in my config I have album_legacy turned on. That _might_ be a prerequisite for seeing the issue (in case you are having difficulty seeing it).

### Environment

```markdown
- OS: MacOs 10.13.6
- Browser: Safari
- Client: Dromio
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/Volumes/TomThumb/music'
ScanSchedule = '@every 12h'
EnableExternalServices = false
DataFolder = '/Volumes/Humlet/Users/matt/navidrome'
LogLevel = 'DEBUG'
RecentlyAddedByModTime = false
LastFM.Enabled = true
LastFM.ApiKey = '<redacted>'
LastFM.Secret = '<redacted>'
PID.Album = 'album_legacy'
Subsonic.ArtistParticipations = true
Tags.Artist.Split = []
Tags.Artists.Split = []
Jukebox.Enabled = true
MPVPath = '/Applications/mpv.app/Contents/MacOS/mpv'
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
