### ISSUE TITLE
[Bug]: Some songs in some albums are ordered by year at the end of the album's song listing.

### ISSUE THREAD

**Issue by mattneub** [navidrome/navidrome#3962]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.2

### Current Behavior

I'm trying to adopt 0.55.2 but I'm finding its behavior very odd. The particular issue now is that in some albums, some tracks are being separated out into Year sections:

![Image](https://github.com/user-attachments/assets/7b585c62-80f2-401b-81e9-07c67aee2838)

This is not disastrous for this experimental album, because the track order is the year order. But in some albums, some songs are not separated by year, and then a bunch of songs _are_ separated by year, and the result is that songs are not presented in track order — not in the web ui, but even more important, not in the actual list of songs provided to the client app (such as Dromio).

### Expected Behavior

I expect the order of songs in an album to be the track order, e.g. 1/10, 2/10, 3/10 etc. And I do _not_ expect some albums to break themselves into year groupings like this.

### Steps To Reproduce

I don't know how to reproduce it. I can send you those four songs in the screenshot if you want. But they weren't behaving like this before; it just started happening when I added some songs to an existing album. I don't understand why this is happening only to albums that I'm just now creating.

I'm going to revert to 0.55.1 and see whether it does the same thing. — No, it doesn't. I keep trying to switch to 0.55.2 but it does weird things so I keep coming back to 0.55.1. I'm going to stay there for a while, I guess. 

### Environment

```markdown
- OS:
- Browser:
- Client:
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/Volumes/TomThumb/music'
ScanSchedule = '@every 12h'
EnableExternalServices = false
DataFolder = '/Volumes/Humlet/Users/matt/navidrome'
LogLevel = 'DEBUG'
RecentlyAddedByModTime = false
LastFM.Enabled = true
LastFM.ApiKey = '<redacted>'
LastFM.Secret = '<redacted>'
PID.Album = 'album'
Subsonic.ArtistParticipations = true
Tags.Artist.Split = []
Tags.iTunes_CDDB_1.Ignore = true
Tags.iTunes_CDDB_TrackNumber.Ignore = true
Tags.iTunSMPB.Ignore = true
Jukebox.Enabled = true
MPVPath = '/Applications/mpv.app/Contents/MacOS/mpv'
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
