### ISSUE TITLE
[Bug]: Unable to stream m3u8 radio station file

### ISSUE THREAD

**Issue by candideu** [navidrome/navidrome#3988]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.1

### Current Behavior

I'm trying to stream The Lot radio on my Navidrome web UI, but it's not working...

I'm able to play the file in VLC (Win 10) and on Symfonium (Android), but not in Navidrome itself. All of my other radio streaming links work.

Here's the streaming link: https://sto-prod-catalyst-0.lp-playback.studio:443/hls/video+85c28sa2o8wppm58/index.m3u8?video=false

### Expected Behavior

Streaming works

### Steps To Reproduce

1. In the Radios page, create a new station
2. Add The Lot's audio-only stream as the stream URL: https://sto-prod-catalyst-0.lp-playback.studio:443/hls/video+85c28sa2o8wppm58/index.m3u8?video=false
3. Hit "Save"
4. Attempt to play back the radio station

### Environment

```markdown
- OS: Raspberry Pi 4
- Browser: Firefox 137.0.1
- Client: Navidrome web UI
```

### How Navidrome is installed?

Docker

### Configuration

```toml

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct

**Comment by mattn** [comment]
I use my hls mp3 proxy.

https://github.com/mattn/hls2mp3

**Comment by deluan** [comment]
Hey @mattn, thanks for the link! We do have an [old PR](https://github.com/navidrome/navidrome/pull/2187) (that we may be revisiting soon), that should handle not only M38U, but also CORS issues and better radio icons. Do you use Navidrome with your proxy? 

By the way, thanks for your awesome work on the SQLite3 driver!

**Comment by mattn** [comment]
>Do you use Navidrome with your proxy?

The current behavior of navidrome differs between PCs and Android devices. On Android, hls plays without any problems. However, this is not the case on PCs. This is just my guess, but I think it is probably because the html5 audio tag in the PC version of Google Chrome does not support hls. I also tried HLS.js, but it did not solve the problem. So I wrote a proxy that can treat hls as a stream like mp3. Currently, there are no particular problems.

**Comment by fabiosirna** [comment]
I'm using racoder as a workaround.
Added this at the end of my navidrome compose:

```
[...]
  racoder:
    image: paulgalow/racoder:latest
    container_name: racoder
    restart: unless-stopped
    ports:
      - "4534:3000/tcp"
    environment:
      INPUT_STREAM: "https://radio-url-to-convert.m3u8"
      TZ: Europe/Paris
      LOG_LEVEL: DEBUG
    read_only: true
    cap_drop:
      - ALL
```

change the ports according to your setup:
`3000:3000` is the default for racoder but I have other services running.

In my case the converted url is at `http://localhost:4534`.
