### ISSUE TITLE
[Bug]: Navidrome adopts album art from one "unknown album" track for all "unknown album" tracks

### ISSUE THREAD

**Issue by TheHYPO35** [navidrome/navidrome#3989]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.2

### Current Behavior

I have one track that has (or had) no id3 tag for album or artist, and therefore appeared in the "unknown album"/"unknown artist" listing in Navidrome. However, this mp3 had album art in it. As a result, every other track in my library with a blank album/artist tag adopted this album art image.

### Expected Behavior

At least for unknown album/artist, I don't think this should be expected behaviour. The embedded art should only apply to that specific file.

I can understand the premise of adopting art from one mp3 from "BandName" "AlbumTitle" and adopting it for other tracks by "BandName" from "AlbumTitle" that might have had missed having their artwork embedded (though I can also envision someone wanting no album art on a specific file on purpose in certain cases). But for unknown artist and/or unknown album specifically, I don't envision a situation where an embedded artwork in one file would be wanted to be used for all such files.

### Steps To Reproduce

Presumably load a file with artwork embedded but no album/artist id3 tags (not sure if any other tags have to be blank - in my case, there was no id3 tag info other than the artwork) - then check the artwork in navidrome for other unknown album/artist songs.

### Environment

```markdown
- OS: Debian 12
- Browser: Chrome
- Client: Web and others

But I don't think any of this is relevant to this issue
```

### How Navidrome is installed?

Docker

### Configuration

```toml
LogLevel = 'info'

ScanSchedule = '@every 24h'
AutoImportPlaylists = 'true'
PlaylistsPath = 'Playlists'

CoverArtPriority = 'embedded, cover.*, folder.*, front.*, external'
IgnoredArticles = 'The El La Los Las Le Le Os As A ( ) [ ] < >'

Scanner.Extractor = 'ffmpeg'

TranscodingCacheSize = '150MiB'
BaseUrl = '/navidrome'

LastFM.Enabled = 'true'
LastFM.ApiKey = [redacted]
LastFM.Secret = [redacted]

Spotify.ID = [redacted]
Spotify.Secret = [redacted]

# EnableDownloads = 'false'
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
