### ISSUE TITLE
[Bug]: Custom tags defined as floats appear to be treated as strings in smart playlists

### ISSUE THREAD

**Issue by pruperting** [navidrome/navidrome#4055]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.2

### Current Behavior

Custom tags appear to be treated as strings in smart playlists, not float when defined as such in the config file. This is evidenced when using gt and lt functions in smart playlists, where the outputs don't work as expected. 

### Expected Behavior

Custom tags defined as floats should work correctly with Numeric functions such as gt, lt and inTheRange.

### Steps To Reproduce

1. Define new custom tags in the config file, one as string, one as float:
Tags.ABTonalChordsChangeRate.Aliases = ['ab:lo:tonal:chords_changes_rate']
Tags.ABTonalChordsChangeRate.Type = 'float'
Tags.ABTonalChordsChangeRate.Album = false
Tags.ABTonalChordsChangeRate.Split = [',']

Tags.CamelotKey.Aliases = ['camelot_key']
Tags.CamelotKey.Type = 'string'
Tags.CamelotKey.Album = false
Tags.CamelotKey.Split = [',']
 
2. Create smartplaylist to search where abtonalchordschangerate is less than 6. {
  "name": "Chords Changes",
  "comment": "High chord changes",
  "all": [
    {"lt": {"abtonalchordschangerate": 6}}
    ],
    "sort": "random",
    "order": "desc",
    "limit": 25
}
 
3. Tracks where abtonalchordschangerate is 10, 200, 30 etc will be included. 

### Environment

```markdown
- OS: DietPi 9.12.1
- Browser: Chrome Version 136.0.7103.93 (Official Build) (64-bit)
- Client: n/a
```

### How Navidrome is installed?

Package

### Configuration

```toml
DataFolder = '/mnt/dietpi_userdata/navidrome/data'
MusicFolder = '/mnt/sda/FLAC'
ImageCacheSize = '1000MiB'

LogLevel = 'debug'
SessionTimeout = '24h'
AuthRequestLimit = '5'
AuthWindowLength = '20s'
ScanSchedule = '@every 24h'
EnableLogRedacting = false
Scanner.Extractor = 'taglib'
TranscodingCacheSize = '1GB'

CoverJpegQuality = '75'
CoverArtPriority = 'folder.*, Folder.*, cover.*. Cover.*, embedded, external'

LastFM.Enabled = true
LastFM.ApiKey = ''
LastFM.Secret = ''

Jukebox.Enabled = false
MPVPath = '/usr/bin/mpv'
Jukebox.Devices = [
    [ "internal",     'alsa/sysdefault:CARD=DAC' ]
]
Jukebox.Default = 'internal'
#MPVCmdTemplate = "mpv --log-file=/tmp/mpv.log --msg-level=all=info --no-audio-display --pause '%f' --input-ipc-server=%s --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16 --ao=pcm --ao-pcm-file=/tmp/mpd"
MPVCmdTemplate = "mpv --no-audio-display '%f' --input-ipc-server=%s"
#MPVCmdTemplate = "mpv --no-audio-display --pause %f --input-ipc-server=%s --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16 --ao=pcm --ao-pcm-file=/tmp/mpd"
EnableTranscodingConfig = true

#Customn tags
Tags.ABDanceabilityDanceability.Aliases = ['ab:hi:danceability:danceability']
Tags.ABDanceabilityDanceability.Type = 'float'
Tags.ABDanceabilityDanceability.Album = false
Tags.ABDanceabilityDanceability.Split = [',']

Tags.ABBeatsCount.Aliases = ['ab:lo:rhythm:beatscount']
Tags.ABBeatsCount.Type = 'float'
Tags.ABBeatsCount.Album = false
Tags.ABBeatsCount.Split = [',']

Tags.ABDanceabilityDanceable.Aliases = ['ab:hi:danceability:danceable']
Tags.ABDanceabilityDanceable.Type = 'float'
Tags.ABDanceabilityDanceable.Album = false
Tags.ABDanceabilityDanceable.Split = [',']

Tags.ABIsMale.Aliases = ['ab:hi:gender:male']
Tags.ABIsMale.Type = 'float'
Tags.ABIsMale.Album = false
Tags.ABIsMale.Split = [',']

Tags.ABIsFemale.Aliases = ['ab:hi:gender:female']
Tags.ABIsFemale.Type = 'float'
Tags.ABIsFemale.Album = false
Tags.ABIsFemale.Split = [',']

Tags.ABIsVoice.Aliases = ['ab:hi:voice_instrumental:voice']
Tags.ABIsVoice.Type = 'float'
Tags.ABIsVoice.Album = false
Tags.ABIsVoice.Split = [',']

Tags.ABIsInstrumental.Aliases = ['ab:hi:voice_instrumental:instrumental']
Tags.ABIsInstrumental.Type = 'float'
Tags.ABIsInstrumental.Album = false
Tags.ABIsInstrumental.Split = [',']

Tags.ABMoodAcoustic.Aliases = ['ab:hi:mood_acoustic:acoustic']
Tags.ABMoodAcoustic.Type = 'float'
Tags.ABMoodAcoustic.Album = false
Tags.ABMoodAcoustic.Split = [',']

Tags.ABMoodAggressive.Aliases = ['ab:hi:mood_aggressive:aggressive']
Tags.ABMoodAggressive.Type = 'float'
Tags.ABMoodAggressive.Album = false
Tags.ABMoodAggressive.Split = [',']

Tags.ABMoodElectronic.Aliases = ['ab:hi:mood_electronic:electronic']
Tags.ABMoodElectronic.Type = 'float'
Tags.ABMoodElectronic.Album = false
Tags.ABMoodElectronic.Split = [',']

Tags.ABMoodHappy.Aliases = ['ab:hi:mood_happy:happy']
Tags.ABMoodHappy.Type = 'float'
Tags.ABMoodHappy.Album = false
Tags.ABMoodHappy.Split = [',']

Tags.ABMoodSad.Aliases = ['ab:hi:mood_sad:sad']
Tags.ABMoodSad.Type = 'float'
Tags.ABMoodSad.Album = false
Tags.ABMoodSad.Split = [',']

Tags.ABMoodParty.Aliases = ['ab:hi:mood_party:party']
Tags.ABMoodParty.Type = 'float'
Tags.ABMoodParty.Album = false
Tags.ABMoodParty.Split = [',']

Tags.ABMoodRelaxed.Aliases = ['ab:hi:mood_relaxed:relaxed']
Tags.ABMoodRelaxed.Type = 'float'
Tags.ABMoodRelaxed.Album = false
Tags.ABMoodRelaxed.Split = [',']

Tags.ABMoodMirexCluster1.Aliases = ['ab:hi:moods_mirex:passionate, rousing, confident, boisterous, rowdy']
Tags.ABMoodMirexCluster1.Type = 'float'
Tags.ABMoodMirexCluster1.Album = false
Tags.ABMoodMirexCluster1.Split = [',']

Tags.ABMoodMirexCluster2.Aliases = ['ab:hi:moods_mirex:rollicking, cheerful, fun, sweet, amiable/good natured']
Tags.ABMoodMirexCluster2.Type = 'float'
Tags.ABMoodMirexCluster2.Album = false
Tags.ABMoodMirexCluster2.Split = [',']

Tags.ABMoodMirexCluster3.Aliases = ['ab:hi:moods_mirex:literate, poignant, wistful, bittersweet, autumnal, brooding']
Tags.ABMoodMirexCluster3.Type = 'float'
Tags.ABMoodMirexCluster3.Album = false
Tags.ABMoodMirexCluster3.Split = [',']

Tags.ABMoodMirexCluster4.Aliases = ['ab:hi:moods_mirex:humorous, silly, campy, quirky, whimsical, witty, wry']
Tags.ABMoodMirexCluster4.Type = 'float'
Tags.ABMoodMirexCluster4.Album = false
Tags.ABMoodMirexCluster4.Split = [',']

Tags.ABMoodMirexCluster5.Aliases = ['ab:hi:moods_mirex:aggressive, fiery, tense/anxious, intense, volatile, visceral']
Tags.ABMoodMirexCluster5.Type = 'float'
Tags.ABMoodMirexCluster5.Album = false
Tags.ABMoodMirexCluster5.Split = [',']

Tags.ABMoodMirex.Aliases = ['ab:hi:moods_mirex']
Tags.ABMoodMirex.Type = 'string'
Tags.ABMoodMirex.Album = false
Tags.ABMoodMirex.Split = [',']

Tags.ABHiEnergyScore.Aliases = ['ab:hi_energy_score']
Tags.ABHiEnergyScore.Type = 'float'
Tags.ABHiEnergyScore.Album = false
Tags.ABHiEnergyScore.Split = [',']

Tags.ABLowEnergyScore.Aliases = ['ab:low_energy_score']
Tags.ABLowEnergyScore.Type = 'float'
Tags.ABLowEnergyScore.Album = false
Tags.ABLowEnergyScore.Split = [',']

Tags.ABTonalKeyKey.Aliases = ['ab:lo:tonal:key_key']
Tags.ABTonalKeyKey.Type = 'string'
Tags.ABTonalKeyKey.Album = false
Tags.ABTonalKeyKey.Split = [',']

Tags.ABTonalKeyScale.Aliases = ['ab:lo:tonal:key_scale']
Tags.ABTonalKeyScale.Type = 'string'
Tags.ABTonalKeyScale.Album = false
Tags.ABTonalKeyScale.Split = [',']

Tags.ABTonalChordsKey.Aliases = ['ab:lo:tonal:chords_key']
Tags.ABTonalChordsKey.Type = 'string'
Tags.ABTonalChordsKey.Album = false
Tags.ABTonalChordsKey.Split = [',']

Tags.ABTonalChordsScale.Aliases = ['ab:lo:tonal:chords_scale']
Tags.ABTonalChordsScale.Type = 'string'
Tags.ABTonalChordsScale.Album = false
Tags.ABTonalChordsScale.Split = [',']

Tags.ABTonalChordsChangeRate.Aliases = ['ab:lo:tonal:chords_changes_rate']
Tags.ABTonalChordsChangeRate.Type = 'float'
Tags.ABTonalChordsChangeRate.Album = false
Tags.ABTonalChordsChangeRate.Split = [',']

Tags.CamelotKey.Aliases = ['camelot_key']
Tags.CamelotKey.Type = 'string'
Tags.CamelotKey.Album = false
Tags.CamelotKey.Split = [',']

Tags.PlayStyleXEnergyIntensity.Aliases = ['play_style_x_energy_intensity']
Tags.PlayStyleXEnergyIntensity.Type = 'float'
Tags.PlayStyleXEnergyIntensity.Album = false
Tags.PlayStyleXEnergyIntensity.Split = [',']

Tags.PlayStyleYMoodTimbralColor.Aliases = ['play_style_y_mood_timbral_color']
Tags.PlayStyleYMoodTimbralColor.Type = 'float'
Tags.PlayStyleYMoodTimbralColor.Album = false
Tags.PlayStyleYMoodTimbralColor.Split = [',']
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
