### ISSUE TITLE
[Bug]: All artists are listed in Album Artists role, while Artists role is empty

### ISSUE THREAD

**Issue by emodric** [navidrome/navidrome#4063]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.2

### Current Behavior

Data from Artist tag is shown when selecting Album Artists role on Artists page. At the same time, Artists role is empty.

This has an unfortunate sideeffect that the list of album artists is overpopulated with performers who e.g. have only one track from a random compilation album.

I also took a quick look at the database, and entries in `album_artists` table look correct. Only one `albumartist` role for the album I checked as an example (as it should be), and all other artists are marked with `artist` role.

### Expected Behavior

I would expect that data from Artist tag is shown only when selecting Artists role on Artists page and data from Album Artist tag is shown only when selecting Album Artists role.

### Environment

```markdown
- OS: Ubuntu 24.04
- Browser: Chrome 136.0.7103.92 (Official Build) (64-bit) 
- Client: Navidrome web player, Feishin 0.12.7
```

### How Navidrome is installed?

Package

### Configuration

```toml
DataFolder = "/var/lib/navidrome"
MusicFolder = "/mnt/google-drive-music"
EnableInsightsCollector = false
Scanner.Enabled = false
Scanner.Schedule = 0
Scanner.ScanOnStartup = false
TranscodingCacheSize = 0
CoverArtPriority = "cover.*, albumart.*"
EnableStarRating = false
EnableMediaFileCoverArt = false
EnableGravatar = true
Spotify.ID = "<redacted>"
Spotify.Secret = "<redacted>"
EnableCoverAnimation = false
SessionTimeout = "86400h"
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
