### ISSUE TITLE
[Bug]: Tracks are incorrectly splitted across different albums

### ISSUE THREAD

**Issue by awsms** [navidrome/navidrome#4068]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.2 (a057a680)

### Current Behavior

Navidrome considers that, for an identical `ALBUMARTIST` and `ALBUM` tags, EVEN if they're in the same directory, the album is different.

![Image](https://github.com/user-attachments/assets/4330fd93-cf4b-476d-9c3d-fa1ee554ec4f)

### Expected Behavior

It used to work fine in earlier versions of Navidrome.
It was even better: if the `ALBUMARTIST` and `ALBUM` were identical for any files, this would combine everything in the same Album on Navidrome, regardless of where the files were located.

### Steps To Reproduce

For this example, tracks 2, 3 & 4 are in an album entry on Navidrome, and track 1 is in its standalone album entry.
These 4 files are located in the same folder.
metaflac of Track 1:
```
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 425
  vendor string: reference libFLAC 1.4.3 20230623
  comments: 16
    comment[0]: COMPOSER=Keja vs Kan10
    comment[1]: YEAR=2023
    comment[2]: COPYRIGHT=2023 Keja vs Kan10 2023 Keja vs Kan10
    comment[3]: ISRC=FRDKW2300918
    comment[4]: COMPRESSION=8
    comment[5]: TITLE=Orbital (Uzi Remix)
    comment[6]: ARTIST=Keja
    comment[7]: ALBUM=Tribe Du Sud 03
    comment[8]: DATE=2022
    comment[9]: albumartist=Various Artists
    comment[10]: TRACKNUMBER=1
    comment[11]: publisher=Tribe Du Sud
    comment[12]: label=Tribe Du Sud
    comment[13]: publisher=MackiTek Records
    comment[14]: label=MackiTek Records
    comment[15]: genre=Hardtek;Tribe
```

Track 2:
```
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 308
  vendor string: reference libFLAC 1.4.3 20230623
  comments: 12
    comment[0]: COMPRESSION=8
    comment[1]: TITLE=Scary Noise
    comment[2]: ARTIST=Khenda
    comment[3]: ALBUM=Tribe Du Sud 03
    comment[4]: DATE=2022
    comment[5]: albumartist=Various Artists
    comment[6]: TRACKNUMBER=2
    comment[7]: publisher=Tribe Du Sud
    comment[8]: label=Tribe Du Sud
    comment[9]: publisher=MackiTek Records
    comment[10]: label=MackiTek Records
    comment[11]: genre=Hardtek;Tribe
```

Track 3:
```
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 316
  vendor string: reference libFLAC 1.4.3 20230623
  comments: 12
    comment[0]: COMPRESSION=8
    comment[1]: TITLE=Black Swan Theory
    comment[2]: ARTIST=Dismatik
    comment[3]: ALBUM=Tribe Du Sud 03
    comment[4]: DATE=2022
    comment[5]: albumartist=Various Artists
    comment[6]: TRACKNUMBER=3
    comment[7]: publisher=Tribe Du Sud
    comment[8]: label=Tribe Du Sud
    comment[9]: publisher=MackiTek Records
    comment[10]: label=MackiTek Records
    comment[11]: genre=Hardtek;Tribe
```

### Environment

```markdown
- OS: Ubuntu 24.04
- Browser: with any
- Client: with any
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
UIWelcomeMessage=".."
Scanner.Schedule = "@every 1h"
Scanner.Watcher = true
Scanner.Enabled = true
Scanner.WatcherWait = "15s"
TranscodingCacheSize = '250MiB'
MusicFolder = '/media/music'
Address = '127.0.0.1'
BaseUrl = '/navidrome'
EnableDownloads = false
DefaultTheme = 'Spotify-ish'
LastFM.ApiKey = '..'
LastFM.Secret = '..'
Spotify.ID = '..'
Spotify.Secret = '..'
AutoImportPlaylists = false
CoverArtPriority="folder.jpg, cover.jpg, embedded, cover.*, Cover.*, folder.*, front.*, Folder.*, Folder.*, Front.*,*Front.*, *front.*, *.jpg, *.png"
IgnoredArticles="The El La Los Las Le Les Os As O A Der Die Das"
EnableFavourites=true
SearchFullString=true
SessionTimeout="720h"
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
