### ISSUE TITLE
[Bug]: Navidrome scan stops at 999 folders

### ISSUE THREAD

**Issue by Rafaeltheraven** [navidrome/navidrome#4111]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.55.2

### Current Behavior

I have a lot of music. When doing a full scan in navidrome, it stops at 999 folders even though I know for a fact that I have more. Looking at song count there also seem to be a couple thousand missing so I don't think it's just a visual bug.

### Expected Behavior

For navidrone to scan all my directories regardless of how many I have

### Steps To Reproduce

1. Have more than 999 directories
2. Perform a full scan
3. See the counter stop at 999

### Environment

```markdown
- OS: Raspbian 12
- Browser: Firefox
- Client: Web client
```

### How Navidrome is installed?

Package

### Configuration

```toml
DataFolder = "/var/lib/navidrome"
MusicFolder = "/data/syncthing/Music"

LastFM.ApiKey = "CENSORED"
LastFM.Secret = "CENSORED"
AutoImportPlaylists = false
```

### Relevant log output

```shell
May 24 12:39:42 raven navidrome[529003]: time="2025-05-24T12:39:42+02:00" level=info msg="Scanner: Finished refreshing albums" refreshed=46 skipped=896
May 24 12:39:42 raven navidrome[529003]: time="2025-05-24T12:39:42+02:00" level=info msg="Scanner: Finished scanning all libraries" duration=1m14s
```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
