### ISSUE TITLE
[Bug]: Rest API getArtists does not respond with data (Ultrasonic)

### ISSUE THREAD

**Issue by ThecaTTony** [navidrome/navidrome#4140]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.56.0

### Current Behavior

The latest version of the Ultrasonic Android client displays "No results, please try again" in the Artists tab.

I checked the reverse proxy logs (nginx) and there are no errors, the following URL is called:

`https://host.tld/musica/rest/getArtists.view?u=REDACTED&c=Ultrasonic&f=json&v=1.16.0&t=REDACTED=REDACTED`

`"GET /musica/rest/getArtists.view?u=REDACTED&c=Ultrasonic&f=json&v=1.16.0&t=REDACTED=REDACTED HTTP/2.0" 200 203 "-" "okhttp/4.11.0"`

Navidrome's response:

`{"subsonic-response":{"status":"ok","version":"1.16.1","type":"navidrome","serverVersion":"0.56.0 (b19d5f0d)","openSubsonic":true,"artists":{"lastModified":1748540381194,"ignoredArticles":"The El La Los Las Le Les Os As O A"}}}`

The artist search (also albums and songs) works well.

### Expected Behavior

getArtists should return the list of artists in the response.

### Environment

```markdown
- OS: Ubuntu 24.04
- Browser: Vivaldi 7.4.3684.43
- Client: Ultrasonic 4.8.0
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
Address = "localhost"
BaseUrl = "/musica"
LogLevel = "warn"
EnableLogRedacting = true
EnableInsightsCollector = true
Backup.Count = 7
Backup.Path = "/var/lib/navidrome/backup"
Backup.Schedule = "0 0 * * *"
PasswordEncryptionKey = "REDACTED"
SessionTimeout = "24h"
LastFM.ApiKey = "REDACTED"
LastFM.Secret = "REDACTED"
LastFM.Language = "en"
Spotify.ID = "REDACTED"
Spotify.Secret = "REDACTED"
Scanner.Schedule = "@every 12h"
Scanner.ScanOnStartup = false
Scanner.PurgeMissing = "always"
MusicFolder = "/mnt/datos/musica"
DataFolder = "/var/lib/navidrome/data"
CacheFolder = "/var/lib/navidrome/cache"
ImageCacheSize = "128MiB"
TranscodingCacheSize = "1024MiB"
FFmpegPath = "/usr/bin/ffmpeg"
CoverArtPriority = "folder.jpg"
LyricsPriority = ".lrc,.txt"
ArtistArtPriority = "artist.jpg, album/artist.jpg, external"
EnableMediaFileCoverArt = false
SubsonicArtistParticipations = true
DefaultTheme = "Spotify-ish"
UILoginBackgroundUrl = "https://host.tld/fondo/"
UIWelcomeMessage = '<img src="/logo/REDACTED.png" alt="REDACTED">'
MaxSidebarPlaylists = 10
EnableDownloads = true
EnableSharing = true
DefaultShareExpiration = "720h"
EnableStarRating = false
EnableTranscodingConfig = false
DefaultDownsamplingFormat = "mp3"
EnableUserEditing = true
Jukebox.Enabled = false
ListenBrainz.Enabled = false
Prometheus.Enabled = false
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
