### ISSUE TITLE
[Bug]: Albums from the same sorted alphabetically and not on full date

### ISSUE THREAD

**Issue by jsaathof** [navidrome/navidrome#4152]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.56.1

### Current Behavior

Two albums from the same year are sorted alphabetically by the looks of it. This happens for the DATE tags with full date in form of YYYY-MM-DD. I have changed the tags to the "official" names as described in the code https://github.com/navidrome/navidrome/blob/master/resources/mappings.yaml. I have even set both the RECORDINGDATE and RELEASEDATE tags to full dates to see if the RELEASEDATE only being a year messed things up. But still the older album is shown first. My guess since the name begins with a "B" and the other one with a "C".

<img width="452" alt="Image" src="https://github.com/user-attachments/assets/ea25b524-9d0a-43f7-92b9-aa7a97bd8571" />

<img width="607" alt="Image" src="https://github.com/user-attachments/assets/d2345fcf-2ef5-4c5b-8eb5-7d8b759b58f2" />

<img width="596" alt="Image" src="https://github.com/user-attachments/assets/eef069a0-2c1b-47e9-bae6-aebc1095ba6d" />

### Expected Behavior

Albums from the same year sorted correctly by full date, not only by year and album name as it looks like it does right now.

### Steps To Reproduce

1. Tag the albums with RELEASEDATE and RECORDINGDATE in the same year
2. View in the GUI

### Environment

```markdown
- OS: openSUSE Leap 15.6
- Browser: Firefox 138.0.4
- Client: -
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = "/data/music"
DataFolder = "/var/lib/navidrome/data"
CacheFolder = "/var/lib/navidrome/cache"
ImageCacheSize = "4GB"
IgnoredArticles = "The El La Los Las Le Les Os As O A De"
LastFM.ApiKey = "xxxxx"
LastFM.Secret = "xxxxx"
Spotify.ID = "xxxxx"
Spotify.Secret = "xxxxx"
EnableStarRating = false
EnableFavourites = false
PasswordEncryptionKey = "xxxxx"
Address = "127.0.0.1"
EnableInsightsCollector = false
```

### Relevant log output

```shell

```

### Anything else?

I have found an earlier ticket in which the same issues is raised: https://github.com/navidrome/navidrome/issues/1452. This references a merge request in which the ordering should be fixed: https://github.com/navidrome/navidrome/pull/2162. But this does not work as I expected as seen in the screenshots I uploaded. Or please let me know what I'm doing wrong.

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
