### ISSUE TITLE
[Bug]: user jukeboxRole is always true

### ISSUE THREAD

**Issue by mattneub** [navidrome/navidrome#4160]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.56.1

### Current Behavior

Even if a user is not an admin user, `getUser` returns a user whose `jukeboxRole` is `true`. This is contrary to the contract we settled on earlier: the rule should be that, since there is no web interface for determining whether or not a user is to be permitted to treat the navidrome server as a jukebox, we simply draw a line based on whether or not the user is admin.

### Expected Behavior

I expect a non-admin user to return `jukeboxRole`  as `false`.

### Steps To Reproduce

Well, try it yourself. Make a new user who is not an admin user and throw a `getUser` rest call at the server.

### Environment

```markdown
- OS: MacOS 10.13.6
- Browser: Safari
- Client: Dromio (iPhone)
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder = '/Volumes/TomThumb/music'
ScanSchedule = '@every 12h'
EnableExternalServices = false
DataFolder = '/Volumes/Humlet/Users/matt/navidrome'
LogLevel = 'DEBUG'
RecentlyAddedByModTime = false
LastFM.Enabled = true
LastFM.ApiKey = '<redacted>'
LastFM.Secret = '<redacted>'
PID.Album = 'album'
Subsonic.ArtistParticipations = true
Tags.Artist.Split = []
Tags.AlbumArtist.Split = []
Tags.iTunes_CDDB_1.Ignore = true
Tags.iTunes_CDDB_TrackNumber.Ignore = true
Tags.iTunSMPB.Ignore = true
Jukebox.Devices = [
    [ "duet",     "coreaudio/AppleFWAudioEngineGUID:1085260926344054" ],
    [ "internal", "coreaudio/AppleHDAEngineOutput:1B,0,1,1:0" ]
]
Jukebox.Default = "duet"
Jukebox.Enabled = true
MPVPath = '/Applications/mpv.app/Contents/MacOS/mpv'
MPVCmdTemplate = 'mpv --audio-device=%d --no-audio-display --pause /Volumes/TomThumb/music/%f --input-ipc-server=%s --gapless-audio=yes'
```

### Relevant log output

```shell
DEBU[1259] API: New request /rest/getUser.view           client=Dromio requestId=humlet.local/vOr69ODsFN-000137 username=greenie version=1.16.1
DEBU[1259] API: Successful response                      endpoint=/rest/getUser.view requestId=humlet.local/vOr69ODsFN-000137 status=OK
DEBU[1259] HTTP: GET http://mattneub.ddns.net:4533/rest/getUser.view?u=greenie&s=[REDACTED]&t=[REDACTED]&v=1.16.1&c=Dromio&f=json  elapsedTime=2.4ms httpStatus=200 remoteAddr="192.168.0.1:57219" requestId=humlet.local/vOr69ODsFN-000137 responseSize=429 userAgent="Dromio/1 CFNetwork/3826.500.131 Darwin/24.5.0"
```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
