### ISSUE TITLE
[Bug]: All messed up after updating 0.53 to 0.56.1

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [navidrome/navidrome#4183]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.56.1

### Current Behavior

After Full Scan everything is messed up
- Duplicated Albums (Same one with, without Cover)
- Duplicated Albums (Same one shows 20 Tracks and 200 Tracks, but 20 is correct and there are only 20 Tracks)
- Album Cover missing (But has embedded)
- Same Album split in two (Disc 1 and Disc2 but name is 100% same and Discnumbers are tagged correctly)
- Recently Added no longer in old order but all randomly mixed
- Database doubled in Size
- There were 414 Album Pages before now suddenly 819 Album Pages

### Expected Behavior

Everything should be like before update

### Steps To Reproduce

Updating from 0.53 to 0.56.1 and restart.

### Environment

```markdown
- OS:
- Browser:
- Client:
Ubuntu 24.04
```

### How Navidrome is installed?

Docker

### Configuration

```toml
LogLevel = "DEBUG"
EnableSharing = "true"
Scanner.Schedule = "@every 1h"
PID.Track = "track_legacy"
PID.Album = "album"
TranscodingCacheSize = "150MiB"
CoverArtPriority = "embedded, folder.*, cover.*, front.*, external"
MusicFolder = "/data/Music Library"
AutoImportPlaylists = "false"
Address = "0.0.0.0"
BaseUrl = "/navidrome"
PasswordEncryptionKey = ""
LastFM.Enabled = "true"
LastFM.Language = "en"
LastFM.ApiKey = ""
LastFM.Secret = ""
Spotify.ID = ""
Spotify.Secret = ""
```

### Relevant log output

```shell

```

### Anything else?

I only changed Scanner.Schedule, PID.Track, PID.Album from 0.53 to match requirements for 0.56.
The old Database from 0.53 was ok and everything displayed correctly and in right order.

I now dunno how to fix that without full roll back.

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
