### ISSUE TITLE
[Bug]: Database update for `player` results in "context deadline exceeded" in logs

### ISSUE THREAD

**Issue by Kunsi** [navidrome/navidrome#4190]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.56.1 (fa2cf362)

### Current Behavior

I'm getting these messages in my log file:
```
Sun 2025-06-08 11:59:37 UTC nas.home.kunbox.net navidrome[3890450]: time="2025-06-08T11:59:37Z" level=error msg="SQL: `UPDATE player SET client = {:p0}, id = {:p1}, ip = {:p2}, last_seen = {:p3}, max_bit_rate = {:p4}, name = {:p5}, report_real_path = {:p6}, scrobble_enabled = {:p7}, transcoding_id = {:p8}, user_agent = {:p9}, user_id = {:p10} WHERE id = {:p11}`" args="map[p0:NavidromeUI p1:orPu4726UjrJpHfIfTKZch p10:iF95NKcUvCHsX1zhMeTHlU p11:orPu4726UjrJpHfIfTKZch p2: p3:2025-06-08 11:59:33.451766612 +0000 UTC m=+920.123147838 p4:0 p5:NavidromeUI [Firefox/macOS] p6:false p7:true p8: p9:Firefox/macOS]" elapsedTime=4.04s error="context deadline exceeded" requestId=nas.home.kunbox.net/ecAIPbrpDY-000638 rowsAffected=0
...

Sun 2025-06-08 12:01:01 UTC nas.home.kunbox.net navidrome[3890450]: time="2025-06-08T12:01:01Z" level=error msg="SQL: `UPDATE player SET client = {:p0}, id = {:p1}, ip = {:p2}, last_seen = {:p3}, max_bit_rate = {:p4}, name = {:p5}, report_real_path = {:p6}, scrobble_enabled = {:p7}, transcoding_id = {:p8}, user_agent = {:p9}, user_id = {:p10} WHERE id = {:p11}`" args="map[p0:NavidromeUI p1:orPu4726UjrJpHfIfTKZch p10:iF95NKcUvCHsX1zhMeTHlU p11:orPu4726UjrJpHfIfTKZch p2: p3:2025-06-08 12:00:46.572756717 +0000 UTC m=+993.244137942 p4:0 p5:NavidromeUI [Firefox/macOS] p6:false p7:true p8: p9:Firefox/macOS]" elapsedTime=15.02s error="database is locked" requestId=nas.home.kunbox.net/ecAIPbrpDY-000662 rowsAffected=0
Sun 2025-06-08 12:01:01 UTC nas.home.kunbox.net navidrome[3890450]: time="2025-06-08T12:01:01Z" level=warning msg="Could not save player" client=NavidromeUI error="database is locked" id=orPu4726UjrJpHfIfTKZch requestId=nas.home.kunbox.net/ecAIPbrpDY-000662 type=Firefox/macOS username=kunsi
Sun 2025-06-08 12:01:01 UTC nas.home.kunbox.net navidrome[3890450]: time="2025-06-08T12:01:01Z" level=error msg="Could not register player" client=NavidromeUI error="database is locked" requestId=nas.home.kunbox.net/ecAIPbrpDY-000662 username=kunsi
```

I've searched the issues and found https://github.com/navidrome/navidrome/issues/3409 for the "database is locked" error, which *might* be related to this one.

I'm running my music collection of a RAID-Z2 (aka ZFS RAID6) of 6TB WD Red Pro HDDs, with navidrome itself and the database residing on a mirrored (RAID1) set of intel datacentre SATA SSDs, so read/write performance for the database should not be an issue.

Due to me currently running a collection merge i'm writing new music files to the music directory constantly, thus re-triggering a quick scan every time the previous one finishes.

Neither the HDDs nor the SSDs come anywhere close to their theoretical I/O-limit, from what i can tell.

The web frontend seems to be unaffected by these log messages, browsing and media playback work as i'd expect. There are also no visible errors in the browser console (apart from a couple 206es for `/stream` which seem unrelated).

### Expected Behavior

No errors shown in logs (and thus no issues with the player update)

### Environment

```markdown
- OS: MacOS (client), debian 12 (server)
- Browser: Firefox
- Client: Web
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
Address = "127.0.0.1"
BaseUrl = "https://navidrome.home.kunbox.net"
DataFolder = "/var/opt/navidrome"
EnableExternalServices = true
EnableInsightsCollector = false
EnableSharing = true
EnableStarRating = false
IgnoredArticles = "The El La Los Las Le Les Os As O A Der Die Das"
"LastFM.Enabled" = false
"ListenBrainz.Enabled" = false
MusicFolder = "/storage/nas/music"
PasswordEncryptionKey = "extrasecure"
Port = 4533

[Scanner]
Schedule = "@every 72h"

[Spotify]
ID = "very"
Secret = "secret"
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
