### ISSUE TITLE
[Bug]: some composers are displayed in albumartist list

### ISSUE THREAD

**Issue by chryuvski** [navidrome/navidrome#4242]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.56.1

### Current Behavior

In the artist page, when i filter albumartist, some tracks' composers are displayed in the result wtih the albumartists. 
This doesn't happen to all composers.
When I re-edited the track and  change nothing, then did a quick scan, the composer was back in the composer list
(track file type is m4a, and all the tracks are downloaded from iTunes.)

### Expected Behavior

all the composers are in the right place.

### Environment

```markdown
- OS: debian/Docker
- Browser: chrome 118
- Client: Web Client
```

### How Navidrome is installed?

Docker

### Configuration

```toml
services:
    navidrome:
        container_name: navidrome
        restart: unless-stopped
        volumes:
            - "/mnt/nas_share/Audios/Music/Libraries:/music:ro"
            - "./data:/data"
            - "./cache:/cache"
        ports:
            - "4533:4533"
        environment:
            - TZ=Asia/Shanghai
            - ND_CONFIGFILE=/data/navidrome.toml
            - ND_CACHEFOLDER=/cache
        image: deluan/navidrome:latest






LogLevel = 'info'

Backup.Path = "/data/backup"
Backup.Schedule = "0 0 * * *"
Backup.Count = 7

CoverArtPriority = "cover.*, folder.*, front.*, embedded, external"
EnableSharing = true

SearchFullString = true
ImageCacheSize = "2000MB"
TranscodingCacheSize = "4000MB"
EnableTranscodingConfig = true


LastFM.Enabled = true
LastFM.ApiKey = "x"
LastFM.Secret = "x"
LastFM.Language = "zh"

DefaultTheme = "Spotify-ish"
DefaultLanguage = "zh-Hans"

PID.Album = "musicbrainz_albumid|albumartistid,album,albumversion"


ListenBrainz.BaseURL = "http://192.168.123.14:42010/apis/listenbrainz/1/"


Tags.grouping.Split = [" / ", " & "]
Tags.artist.Split = [" / ", " feat. ", " feat ", " ft. ", " ft ", "; ", ", ", " & "]
Tags.albumartist.Split = [" / ", " ft. ", " ft ", "; ", ", ", " & "]
Tags.composer.Split = [" / ", "; ", ", ", " & "]


Scanner.ArtistJoiner = " / "
```

### Relevant log output

```shell

```

### Anything else?

![Image](https://github.com/user-attachments/assets/87619aa1-7d82-4eb9-b2b0-fecc6a38dddc)

![Image](https://github.com/user-attachments/assets/d1f099dc-9458-46cb-8c68-329a38c412c1)

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
