### ISSUE TITLE
[Bug]: Navidrome can't read song lenght

### ISSUE THREAD

**Issue by K0SS4** [navidrome/navidrome#4270]
### I confirm that:

- [x] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [x] I'm using the latest version (your issue may have been fixed already)

### Version

0.56.1

### Current Behavior

Navidrome cannot read song length properly:

![Image](https://github.com/user-attachments/assets/68432e51-06df-4cb0-a876-b2faab1ae8ca)

But mp3tag can:

![Image](https://github.com/user-attachments/assets/4c4e81a0-2482-4e7d-b542-70b1a0c78e46)

### Expected Behavior

Navidrome should show duration like mp3tag does.

### Steps To Reproduce

- Download the file: https://we.tl/t-txyJ6mmeMS (It's 41MB so yeah)
- Put it in your library
- Check the length

The link will expire in 3 days so let me know if it expired or if I should use different service for file hosting.

### Environment

```markdown
- OS: Debian 12
- Browser: Floorp 11.27.0
- Client: webclient
```

### How Navidrome is installed?

Binary (from downloads page)

### Configuration

```toml
MusicFolder="/opt/media/music"
DataFolder="/opt/media/navidrome"
CacheFolder="/opt/media/navidrome/cache"
AuthRequestLimit=3
AuthWindowLength="60s"
EnableDownloads=false
EnableStarRating=false
ReverseProxyWhitelist="127.0.0.1"
DefaultTheme="Spotify-ish"
ArtistArtPriority="external"
Spotify.ID="REDACTED"
Spotify.Secret="REDACTED"
LogLevel="debug"
```

### Relevant log output

```shell

```

### Anything else?

The song is an MPEG-4 Audio file and it's the first such in my library. I tagged it myself using mp3tag(length was already wrong) and then resaved it with musicbrainz picard to fix multivalued ARTIST tag but it did not help with the lenght. Also worth mentioning that musicbrainz picard also cannot check the length showing ?:??:

![Image](https://github.com/user-attachments/assets/d79bb4aa-102e-4e33-bcf5-a0225a3da3b5)

**EDIT**:
Maybe worth mentioning that the song itself plays normally via navidrome and that when I play it then it shows the length on the "play bar":

![Image](https://github.com/user-attachments/assets/571ee8d9-db9e-4ebf-859e-2057b87944d6)

### Code of Conduct

- [x] I agree to follow Navidrome's Code of Conduct
