### ISSUE TITLE
add a docker compose example with https support

### ISSUE THREAD

**Issue by tcurdt** [navidrome/navidrome#476]
I'll just leave me config here:

```

version: "3"
services:

  traefik:
    image: "traefik:2.2.8"
    restart: unless-stopped
    container_name: "traefik"
    command:
      - "--log.level=ERROR"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.tc.acme.tlschallenge=true"
      #- "--certificatesresolvers.tc.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.tc.acme.email=foo@foo.com"
      - "--certificatesresolvers.tc.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  navidrome:
    image: deluan/navidrome:0.31.0
    restart: unless-stopped
    container_name: "navidrome"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`foo.com`)"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.routers.navidrome.tls=true"
      - "traefik.http.routers.navidrome.tls.certresolver=tc"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
    user: 1000:1000
    ports:
      - "4533:4533"
    environment:
      GODEBUG: asyncpreemptoff=1
      ND_SCANINTERVAL: 6h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 168h
      ND_BASEURL: ""
    volumes:
      - "/srv/navidrome:/data"
      - "/mnt/public/music:/music:ro"

```

**Comment by deluan** [comment]
If this example works as is (without the need to additional steps), it could be added to the `/contrib` folder. Or else we could have a page in the [docs](https://github.com/navidrome/website) describing the steps to install/use it

**Comment by tcurdt** [comment]
Well, you need to adjust the external URL and the email :) but other than that it should just work (tm).

**Comment by andrewzah** [comment]
This is what I use for caddy v2 (running in another docker container):

```Caddyfile
https://your.website {
  reverse_proxy * navidrome:4533 {
    header_up Host {http.reverse_proxy.upstream.hostport}
    header_up X-Forwarded-For {http.request.remote}
    header_up X-Real-IP {http.reverse_proxy.upstream.port}
  }
}
```

**Comment by fringillidaes** [comment]
Here is one for the https://github.com/nginx-proxy/nginx-proxy setup if anyone comes across this in the feature. Automatically generates configs for new containers. 

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nginx-proxy/certs:/etc/nginx/certs:ro"
      - "/opt/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw"
      - "/opt/nginx-proxy/htpasswd:/etc/nginx/htpasswd:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/usr/share/nginx/html"
      - "/opt/nginx-proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nginx-proxy/certs:/etc/nginx/certs:rw"
      - "/opt/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    volumes:
      - /opt/navidrome:/data
      - /mnt/unionfs/Media/Music:/music:ro
    environment:
      - VIRTUAL_HOST=navidrome.foo.com
      - VIRTUAL_PORT=4533
      - LETSENCRYPT_HOST=navidrome.foo.com
      - LETSENCRYPT_EMAIL=email@email.com

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
```
