### ISSUE TITLE
Implement podcast subsonic api

### ISSUE THREAD

**Issue by Code-Slave** [navidrome/navidrome#793]
this would fill out the functionality from my standpoint. Be nice to support the podcast api. it would require a secondary directory for sure

**Comment by behzad1248** [comment]
Behzad1248

**Comment by obbardc** [comment]
Do you know of the best opensource Subsonic podcast apps for linux/android/web to start doing testing with?

The subsonic backend would be a good place to start implementation ;-)

**Comment by Code-Slave** [comment]
most subsonix mobile apps support podcasts

**Comment by delightfuldude** [comment]
+1 
A navidrome podcast support as a gpodder alternative would be great!

**Comment by williamkray** [comment]
i just stumbled across [this project] which is a golang-based podcast fetching application, i feel like the opportunity for these projects to join forces would be exceptional.

**Comment by deluan** [comment]
Not a proper solution, more of a hack/workaround, but may interest some of you folks: https://github.com/allanjamesvestal/Cousin-IDDD

**Comment by Code-Slave** [comment]
Yea podcast api has has support in clients so its needed for bookmarking, etc etc

**Comment by deluan** [comment]
Navidrome already support bookmarks. The only piece missing for full Podcast support is managing them (add, downloading, etc..)

**Comment by Code-Slave** [comment]
like the person above, i use podgrab. works incredibly well. What id love is to run a seperate navidrom instance just on that folder that my play:sub or other subsonic app see as a podcast. I dont know from a server perspective what designates via the api that its a podcast. Navidrome is great at what it does. podgrab is as well. i like having seperate tools

**Comment by iSwiftLiu** [comment]
Support podcast is great

**Comment by kevinkdev** [comment]
+1
it would be great if this feature gets implemented

**Comment by spouradrix** [comment]
I'd also love to have this feature

**Comment by RyanGreenup** [comment]
> like the person above, i use podgrab. works incredibly well. What id love is to run a seperate navidrom instance just on that folder that my play:sub or other subsonic app see as a podcast. I dont know from a server perspective what designates via the api that its a podcast. Navidrome is great at what it does. podgrab is as well. i like having seperate tools

I use docker to get similar behaviour, using [podgrab](https://github.com/akhilrex/podgrab) to pull the podcasts and Navidrome to host them, this is the  `docker-compose.yml`:


<details><summary>Click to unfold </summary>

---

```yaml
version: "3"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
     # - PASSWORD=password     ## Uncomment to enable basic authentication, username = podgrab
    volumes:
      - ./podgrab_config:/config
      - /media/Podcasts/:/assets
    ports:
      - 4532:8080
    restart: unless-stopped
  navidrome_music:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
      # Outside:Inside container
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./navidrome_data/music_instance:/data"
      - "/media/Podcasts/:/music:ro"
  navidrome_podcasts:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4534:4533"
    restart: unless-stopped
    volumes:
      - "./navidrome_data/podcast_instance:/data"
      - "/media/Music/:/music:ro"
```

### Usage


```bash
cd ~/Applications/Docker
mkdir -p ./navidrome_data/music_instance \
    ./navidrome_data/podcast_instance    \
    podgrab_config
sudo docker-compose up -d
sudo docker container list
```

---

</details>

That way I can point [DSub](https://f-droid.org/en/packages/github.daneren2005.dsub/) to separate instances:

| Service              | URL                   |
|----------------------|-----------------------|
| Podgrab              | http://localhost:4532 |
| Podcasts (Navidrome) | http://localhost:4533 |
| Music (Navidrome)    | http://localhost:4534 |
